"""Round 23 pSEO data — sipi.bot (2026-08-08).

Fourth gap-fill (417 URLs → ~459). Depth round: high-intent queries within
established page types. All pages land in EXISTING repo-root dirs — no new
plumbing (no api.py / Dockerfile / rebuild_sitemap edits beyond the walk).

Content rules unchanged: honest copy (sipi.bot doesn't win every dimension),
no fabricated stats/urgency/tiers; cost figures labeled approximate with
"verify current pricing"; $99/$499 flat, unlimited evals, MIT core, ~5 ms,
3 decisions, 6 rule types, HTTP+MCP+CLI, rail-agnostic, queryable audit log.
"""

INTEGRATIONS = [
    dict(
        slug="windsurf",
        title="Windsurf Agent Spend Control — sipi.bot Integration",
        desc="Put a real budget around Windsurf agents. sipi.bot's MCP tool and HTTP API cap spending on compute, APIs, and payments.",
        h1="Spend Control for Windsurf",
        lead="Windsurf's agents run autonomously in your editor — and autonomous agents buy things. A usage meter tells you after; sipi.bot decides before.",
        sections=[
            ("Why Windsurf agents overspend",
             ["Agent mode runs long autonomous sessions that consume usage fast.",
              "Agents can trigger paid tool calls and purchases beyond the editor.",
              "Provider limits only cover one vendor; the rest is ungoverned."]),
            ("How it works",
             ["Register the sipi.bot MCP tool in Windsurf. Before any spend, the agent calls sipi_guard and gets a deterministic APPROVED, BLOCKED, or FLAGGED in ~5 ms."]),
            ("Rules that fit coding workflows",
             ["Per-transaction cap on compute and API credits.",
              "Merchant allowlist for known vendors.",
              "Approval threshold so big purchases route to a human."]),
        ],
        code=dict(
            title="Guard call",
            lang="json",
            body='{\n  "tool": "sipi_guard",\n  "arguments": {\n    "amount": 1200,\n    "merchant": "gpu-provider.com",\n    "category": "compute"\n  }\n}\n\n# {"decision": "BLOCKED", "reason": "Merchant not on allowlist"}',
            caption="One tool call, one deterministic decision.",
        ),
        faqs=[
            ("Does sipi.bot slow Windsurf down?",
             "No — about 5 ms per check, and only on spend actions."),
            ("Is this the same as Windsurf's usage limits?",
             "No. Usage limits are per-vendor and reactive. sipi.bot governs transactions across every merchant before they settle."),
            ("Can it block specific merchants?",
             "Yes — the merchant allowlist blocks anything you haven't approved."),
        ],
        related=[("sipi.bot vs Cursor", "/vs/cursor"), ("Claude Code integration", "/integrations/claude-code"), ("How to stop runaway agents", "/how-to/how-to-stop-runaway-agents")],
    ),
    dict(
        slug="openai-codex",
        title="OpenAI Codex Agent Spend Control — sipi.bot Integration",
        desc="Cap what OpenAI Codex agents spend. sipi.bot guards compute, API, and payment calls before they settle — deterministic, no prompt trust.",
        h1="Spend Control for OpenAI Codex",
        lead="Codex is OpenAI's autonomous coding agent — and it ships with the ability to act. Acting includes spending. A guard tool makes the spending policy real.",
        sections=[
            ("Why Codex agents overspend",
             ["Long autonomous runs call tools thousands of times.",
              "Paid tool calls and purchases compound during agent loops.",
              "OpenAI's own usage limits only cover OpenAI."]),
            ("How it works",
             ["Add sipi.bot as an MCP tool. Before any spend — compute, API credits, payments — Codex calls the guard and gets APPROVED, BLOCKED, or FLAGGED."]),
            ("Rules that fit Codex workflows",
             ["Per-transaction cap for compute purchases.",
              "Merchant allowlist for known vendors.",
              "Velocity limit so retry loops die in seconds."]),
        ],
        code=dict(
            title="MCP registration",
            lang="json",
            body='{\n  "mcpServers": {\n    "sipi": {\n      "command": "npx",\n      "args": ["-y", "@sipi/bot-mcp"]\n    }\n  }\n}',
            caption="Codex discovers the tool on startup.",
        ),
        faqs=[
            ("Does this replace OpenAI's own limits?",
             "No — keep them for OpenAI. sipi.bot covers every merchant, including purchases outside OpenAI."),
            ("Is the decision model-free?",
             "Yes — deterministic rules only, ~5 ms, nothing to inject."),
            ("What happens on BLOCKED?",
             "The agent stops, the money doesn't move, and the attempt is logged."),
        ],
        related=[("Claude Code integration", "/integrations/claude-code"), ("OpenAI Agents SDK", "/integrations/sipi-bot-plus-openai-agents-sdk"), ("Prompt is not a control", "/blog/prompt-not-a-control")],
    ),
    dict(
        slug="aider",
        title="Aider Agent Spend Control — sipi.bot Integration",
        desc="Give Aider coding agents a real spending policy. sipi.bot's guard returns APPROVED, BLOCKED, or FLAGGED before any purchase.",
        h1="Spend Control for Aider",
        lead="Aider is the terminal-native AI pair programmer — scriptable, headless, and easy to run in bulk. Bulk runs mean bulk API spend.",
        sections=[
            ("Why Aider workloads overspend",
             ["Batch runs and CI-driven Aider sessions multiply token spend.",
              "Scripts can retry loops against paid APIs without review.",
              "No built-in dollar-level budget in the CLI."]),
            ("How it works",
             ["Add sipi.bot as a tool (HTTP or MCP). Before any spend, the agent calls the guard and gets a deterministic decision."]),
            ("Rules that fit Aider workflows",
             ["Per-agent daily ceiling for batch runs.",
              "Velocity limit to stop retry loops.",
              "Merchant allowlist for paid tools."]),
        ],
        code=dict(
            title="Guard call",
            lang="bash",
            body='curl -X POST https://sipi.bot/v1/transactions/evaluate \\\n  -H "Content-Type: application/json" \\\n  -d \'{"amount": 40, "merchant": "api.provider.com", "category": "api"}\'\n\n# {"decision": "APPROVED", ...}',
            caption="Aider scripts can guard spend with one call.",
        ),
        faqs=[
            ("Does sipi.bot work with terminal CLIs?",
             "Yes — the CLI and HTTP API fit scripted environments perfectly."),
            ("Can I cap CI-driven runs?",
             "Yes — per-agent ceilings apply to any agent key, including CI."),
        ],
        related=[("Pydantic AI", "/integrations/pydantic-ai"), ("How to set spend limits", "/how-to/how-to-set-spend-limits"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="openrouter",
        title="OpenRouter Spend Control — sipi.bot Integration",
        desc="Gate what OpenRouter agents spend. sipi.bot adds dollar-level policy on top of OpenRouter's single-API access to 100+ models.",
        h1="Spend Control for OpenRouter",
        lead="OpenRouter gives agents one API to hundreds of models — and one bill for all of them. The bill needs a budget; that's the firewall's job.",
        sections=[
            ("Why OpenRouter workloads overspend",
             ["Model-hopping: agents try pricier models as defaults change.",
              "Retry loops multiply per-request costs.",
              "A single API key can serve many agents with no per-agent budget."]),
            ("How it works",
             ["sipi.bot evaluates the proposed transaction before the request hits OpenRouter: amount, merchant, category → APPROVED, BLOCKED, or FLAGGED."]),
            ("Rules that fit OpenRouter workloads",
             ["Per-agent daily ceiling.",
              "Category rule: inference budgets separate from other spend.",
              "Velocity limit for retry loops."]),
        ],
        code=dict(
            title="Stack",
            lang="text",
            body="Agent -> sipi.bot (decide) -> OpenRouter (route) -> model\n\nsipi.bot caps the dollars; OpenRouter routes the requests.",
            caption="Compose: firewall first, router second.",
        ),
        faqs=[
            ("Does sipi.bot replace OpenRouter?",
             "No — it's a decision layer in front of it. See the full comparison."),
            ("Can I budget per agent on one OpenRouter key?",
             "Yes — per-agent rules in sipi.bot split one key's spend into budgets."),
        ],
        related=[("sipi.bot vs OpenRouter", "/vs/openrouter"), ("OpenRouter cost", "/cost-of/openrouter-api-cost"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
]

FOR = [
    dict(
        slug="compliance-officers",
        title="AI Spend Controls for Compliance Officers | sipi.bot",
        desc="Compliance officers: get a defensible audit trail for AI agent spend. Every transaction decision logged with the rule that fired.",
        h1="Agent Spend Controls for Compliance Officers",
        lead="Compliance questions about AI are coming: who authorized this spend, from whom, under which policy? sipi.bot turns 'we were careful' into a queryable answer.",
        sections=[
            ("The compliance problem",
             ["Agent spend is a new third-party risk with no procurement paper trail.",
              "Regulators and auditors want evidence, not assurances.",
              "Recovering 'what happened' after the fact is guesswork without logs."]),
            ("What compliance teams get",
             ["A queryable audit log: every decision, amount, merchant, and the rule that fired.",
              "Policy enforcement that's deterministic — rules can't be argued with or injected around.",
              "Merchant allowlists that make vendor spend explicit and approved."]),
            ("The honest caveat",
             ["sipi.bot is a control and an evidence source — not a compliance certification. Pair it with your org's governance framework."]),
        ],
        table=dict(
            headers=["Compliance need", "sipi.bot answer"],
            rows=[
                ["Authorization evidence", "Rule-level audit log"],
                ["Vendor controls", "Merchant allowlist"],
                ["Policy enforcement", "Deterministic rules engine"],
                ["Approval trails", "FLAGGED → human queue"],
            ],
        ),
        faqs=[
            ("What exactly is in the audit log?",
             "Every decision: amount, merchant, category, decision, and the rule that fired — queryable via API and dashboard."),
            ("Is sipi.bot SOC 2 certified?",
             "sipi.bot provides controls and logs; certification status is separate — check the current compliance posture before relying on it."),
            ("Can auditors query the logs?",
             "Yes — the audit log is API-queryable and timestamped on hosted plans."),
        ],
        related=[("Security page", "/security"), ("Agent audit trail", "/glossary/agent-audit-trail"), ("Audit checklist", "/checklists/agent-cost-audit")],
    ),
    dict(
        slug="product-managers",
        title="AI Spend Controls for Product Managers | sipi.bot",
        desc="Product managers shipping agent features: keep agent spend inside the product budget with per-agent caps and approval workflows.",
        h1="Agent Spend Controls for Product Managers",
        lead="You own the roadmap and the budget. Agent features ship fast — and their spend lands on your line. Budget enforcement shouldn't be a surprise at month-end.",
        sections=[
            ("The PM problem",
             ["Agent features generate variable cost per user action.",
              "A runaway loop in one session can eat a week of margin.",
              "Provider dashboards show the bill; they don't enforce the budget."]),
            ("What PMs get",
             ["Per-agent and per-feature budgets enforced in real time.",
              "FLAGGED transactions routed to an approval queue — the product equivalent of a spend review.",
              "Usage data (via the audit log) to price features honestly."]),
            ("How to deploy",
             ["Integrate once behind your agent's spend path; set rules per feature or plan tier."]),
        ],
        table=dict(
            headers=["PM concern", "sipi.bot answer"],
            rows=[
                ["Variable feature cost", "Per-feature budget caps"],
                ["Runaway sessions", "Velocity limits"],
                ["Plan-tier pricing", "Per-tier ceilings"],
                ["Cost visibility", "Queryable audit log"],
            ],
        ),
        faqs=[
            ("Can I cap spend per plan tier?",
             "Yes — per-agent rules let each tier or feature run its own ceiling."),
            ("Does it help price the product?",
             "The audit log shows real spend per agent, which is the data you need for honest pricing."),
        ],
        related=[("AI startups", "/use-cases/ai-startups"), ("Budget sizing calculator", "/calculators/budget-sizing-calculator"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
    dict(
        slug="procurement-teams",
        title="AI Agent Vendor Controls for Procurement | sipi.bot",
        desc="Procurement teams: extend vendor management to agent spend. Merchant allowlists make every vendor purchase explicit and approved.",
        h1="Agent Vendor Controls for Procurement",
        lead="Every agent purchase is a vendor relationship. Procurement gets the allowlist; agents get blocked from everyone else.",
        sections=[
            ("The procurement problem",
             ["Agents buy from vendors nobody approved — the equivalent of a rogue PO.",
              "Unknown vendors are the top runaway pattern in the incident database.",
              "Vendor management stops at humans; agents bypass it."]),
            ("What procurement gets",
             ["Merchant allowlists: only approved vendors can be paid.",
              "Category rules mapping spend types to approved vendors.",
              "An audit log showing exactly which vendor got what."]),
            ("How to deploy",
             ["Build the allowlist from your approved vendor list, set category rules, and let new-vendor requests flow through FLAGGED for review."]),
        ],
        table=dict(
            headers=["Procurement control", "sipi.bot equivalent"],
            rows=[
                ["Approved vendor list", "Merchant allowlist"],
                ["PO approval", "FLAGGED → approval queue"],
                ["Category policy", "Category rules"],
                ["Vendor spend record", "Queryable audit log"],
            ],
        ),
        faqs=[
            ("What happens when an agent needs a new vendor?",
             "The purchase is FLAGGED and waits in the approval queue — procurement reviews it like a PO."),
            ("Can I block entire categories?",
             "Yes — category rules can block or cap whole spend types (e.g. no crypto, no wire transfers)."),
        ],
        related=[("Merchant allowlists", "/guides/merchant-allowlists"), ("Merchant blocklist template", "/templates/merchant-blocklist"), ("Merchant allowlist template", "/templates/merchant-allowlist-template")],
    ),
    dict(
        slug="accounting-teams",
        title="AI Agent Spend Controls for Accounting | sipi.bot",
        desc="Accounting teams: make agent spend reconcilable. Every transaction decision logged with amount, merchant, and rule — ready for the ledger.",
        h1="Agent Spend Controls for Accounting",
        lead="Agent transactions hit your ledger with no invoice and no approver. sipi.bot makes them reconcilable: every decision logged, every category attributable.",
        sections=[
            ("The accounting problem",
             ["Agent purchases arrive as mystery line items.",
              "No approval trail, no category, no vendor code.",
              "Month-end reconciliation becomes archaeology."]),
            ("What accounting gets",
             ["A timestamped audit log of every decision: amount, merchant, category, rule.",
              "Category rules that keep spend in defined buckets for the ledger.",
              "Approval thresholds so material amounts wait for review."]),
            ("How to deploy",
             ["Map your ledger categories to sipi.bot category rules; export the audit log for reconciliation."]),
        ],
        table=dict(
            headers=["Accounting need", "sipi.bot answer"],
            rows=[
                ["Attribution", "Category rules per bucket"],
                ["Approval trail", "FLAGGED → human queue"],
                ["Reconciliation", "Queryable audit log"],
                ["Materiality", "Approval thresholds"],
            ],
        ),
        faqs=[
            ("Can I export decisions to my accounting system?",
             "The audit log is API-queryable, so exports and syncs are straightforward."),
            ("What categories can I define?",
             "Whatever maps to your ledger: compute, data, SaaS, ads, payments — cap or flag per category."),
        ],
        related=[("Cost allocation template", "/templates/cost-allocation-template"), ("Finance teams", "/for/finance-teams"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
]

USE_CASES = [
    dict(
        slug="insurtech",
        title="Insurtech Agent Spend Control | sipi.bot",
        desc="Insurtech agents handle claims, underwriting, and fraud checks — and spend on data and inference. Cap the spend, keep the speed.",
        h1="Spend Control for Insurtech Agents",
        lead="Claims agents, underwriting bots, and fraud models each buy data and compute per policy. At insurtech volume, per-check costs compound fast.",
        sections=[
            ("Where insurtech agents spend",
             ["Claims agents pulling data sources and document processing per claim.",
              "Underwriting agents running inference per application.",
              "Fraud models querying external databases per transaction."]),
            ("The failure modes",
             ["A claims workflow retrying overnight multiplies per-claim charges.",
              "New data vendors bypass procurement — allowlist them.",
              "Volume spikes (catastrophe events) hit overage tiers."]),
            ("Which rules to start with",
             ["Per-claim or per-agent daily ceiling.",
              "Merchant allowlist for approved data vendors.",
              "Category rule: claims data vs underwriting inference."]),
        ],
        table=dict(
            headers=["Insurtech spend", "Control"],
            rows=[
                ["Claims data", "Per-agent ceiling + allowlist"],
                ["Underwriting inference", "Category budget"],
                ["Fraud databases", "Merchant allowlist"],
                ["Document processing", "Daily ceiling"],
            ],
        ),
        faqs=[
            ("Can I budget per product line?",
             "Yes — per-agent rules let each product line (auto, life, health) run its own budget."),
            ("What about event-driven spikes?",
             "Set ceilings where they should be and route the rest through FLAGGED approval instead of overage."),
        ],
        related=[("Healthcare sector", "/sectors/healthcare"), ("Backoffice automation", "/use-cases/backoffice-automation"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
    dict(
        slug="ai-research-labs",
        title="AI Research Lab Spend Control | sipi.bot",
        desc="Research labs run the most expensive agent workloads: frontier-model inference at scale. Cap it without slowing the science.",
        h1="Spend Control for AI Research Labs",
        lead="Research labs burn through frontier-model tokens at a rate that makes CFOs wince. The spend is real; so is the need to keep experiments running.",
        sections=[
            ("Where research labs spend",
             ["Frontier-model inference for experiments and evals.",
              "Agent fleets running parallel research pipelines.",
              "Compute and data purchases beyond the model bill."]),
            ("The failure modes",
             ["An eval loop re-running after a prompt change multiplies inference spend.",
              "Parallel agents compound spend during a single experiment.",
              "Model drift to pricier tiers changes the bill silently."]),
            ("Which rules to start with",
             ["Per-experiment budget.",
              "Velocity limit on eval retries.",
              "Category rule: inference vs compute vs data."]),
        ],
        table=dict(
            headers=["Research spend", "Control"],
            rows=[
                ["Frontier inference", "Per-experiment ceiling"],
                ["Eval loops", "Velocity limit"],
                ["Parallel fleets", "Shared daily cap"],
                ["Data purchases", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Does the firewall slow experiments?",
             "No — ~5 ms per check, only on spend actions."),
            ("Can different projects have different budgets?",
             "Yes — per-agent rules let each project run its own ceiling."),
        ],
        related=[("ML engineers", "/for/ml-engineers"), ("LLM context cost", "/benchmarks/llm-context-window-cost-comparison"), ("Token cache savings", "/benchmarks/token-cache-hit-savings")],
    ),
    dict(
        slug="hft-trading",
        title="HFT & Trading Bot Spend Control | sipi.bot",
        desc="High-frequency and algo trading agents spend on data feeds, exchange APIs, and compute. Hard caps with microsecond-relevant latency.",
        h1="Spend Control for Trading Agents",
        lead="Trading agents buy data feeds and API credits constantly — and a retry loop during market hours is a real financial event, not a tech incident.",
        sections=[
            ("Where trading agents spend",
             ["Market data feeds billed per message or per connection.",
              "Exchange and backtesting API credits.",
              "Compute for strategy runs and simulations."]),
            ("The failure modes",
             ["A data-feed retry loop multiplies per-message charges.",
              "An unknown data vendor slips past procurement — allowlist it.",
              "Overnight backtesting burns budget before review."]),
            ("Which rules to start with",
             ["Per-transaction cap on data purchases.",
              "Velocity limit on feed retries.",
              "Time-of-day rule for unattended runs."]),
        ],
        table=dict(
            headers=["Trading spend", "Control"],
            rows=[
                ["Data feeds", "Per-transaction cap"],
                ["Exchange APIs", "Per-agent ceiling"],
                ["Backtesting compute", "Daily ceiling"],
                ["New vendors", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Is 5 ms too slow for trading?",
             "The firewall checks spend decisions, not market data — 5 ms is fine for the payment path, which is far slower than the trading loop itself."),
            ("Can it block a feed vendor mid-session?",
             "Yes — allowlist enforcement is deterministic and immediate."),
        ],
        related=[("Trading bots", "/for/ai-trading-bots"), ("Fintech sector", "/sectors/fintech"), ("Velocity limit", "/glossary/velocity-limit")],
    ),
]

GLOSSARY = [
    dict(
        slug="prompt-injection",
        term="Prompt injection",
        title="What is Prompt Injection? | sipi.bot Glossary",
        desc="Prompt injection: how attackers get AI agents to do what they want — including spending money. And the deterministic defense.",
        h1="What is Prompt Injection?",
        lead="Prompt injection is an attack where instructions hidden in data (tool output, web content, email) manipulate an AI agent into doing something unintended — including spending money.",
        sections=[
            ("How it works",
             ["Agents treat model output and tool results as trustworthy. An attacker embeds instructions inside that content.",
              "The agent follows them as if they were its own task — buying from a vendor, exfiltrating data, triggering payments."]),
            ("Why detection isn't enough",
             ["Injection detection is probabilistic; bypasses exist.",
              "Even detection needs something to stop the money from moving."]),
            ("The deterministic defense",
             ["A spend firewall's decision path is a rules engine — no model to inject. Injected instructions can't approve a purchase or add a merchant to the allowlist."]),
        ],
        faqs=[
            ("Can prompt injection make an agent spend?",
             "Yes — that's the documented pattern. The defense is a deterministic gate on the money path."),
            ("Is sipi.bot injection protection?",
             "It's the layer injection can't bypass for spending. Pair it with detection for everything else."),
        ],
        related=[("Can sipi.bot stop prompt injection", "/faq/can-sipi-bot-stop-prompt-injection"), ("Injection incident", "/incidents/chatgpt-prompt-injection-exfil-2024-06"), ("Best injection protection", "/best/best-prompt-injection-protection")],
    ),
    dict(
        slug="mcp",
        term="MCP",
        title="What is MCP (Model Context Protocol)? | sipi.bot Glossary",
        desc="MCP is how agents get tools — and tools are how they spend. The protocol explained, and why spend control over MCP matters.",
        h1="What is MCP?",
        lead="The Model Context Protocol (MCP) is an open standard that connects AI agents to tools, data, and services. It's the plumbing of the agent economy — and the plumbing carries money.",
        sections=[
            ("How it works",
             ["MCP lets any client (Claude Code, Cursor, Hermes) discover and call tools from any server.",
              "Tools can do anything — including trigger paid services and payments."]),
            ("Why MCP matters for spend",
             ["Every tool an agent calls is a potential purchase.",
              "A tool in a retry loop calls the same paid endpoint repeatedly.",
              "There's no budget enforcement in the MCP spec itself."]),
            ("The control layer",
             ["sipi.bot is a native MCP tool: agents call it before spending and get APPROVED, BLOCKED, or FLAGGED."]),
        ],
        faqs=[
            ("Does MCP have built-in spend controls?",
             "No — the protocol defines tool access, not budgets. Spend control is an extra layer."),
            ("How do I add sipi.bot to an MCP client?",
             "One config entry — see the MCP integration page."),
        ],
        related=[("MCP integration", "/integrations/mcp"), ("Best MCP spend tools", "/best/best-mcp-tools-for-ai-spend-control"), ("MCP-native spend controls", "/blog/mcp-native-spend-controls")],
    ),
    dict(
        slug="subagent",
        term="Subagent",
        title="What is a Subagent? | sipi.bot Glossary",
        desc="Subagents are child agents spawned by a coordinator — and the compounding cost risk they create. Glossary definition with spend implications.",
        h1="What is a Subagent?",
        lead="A subagent is a child agent spawned by a coordinator to complete a subtask. Subagents make spend compound: fan-out multiplies every cost.",
        sections=[
            ("How subagents work",
             ["A coordinator decomposes a task and spawns subagents in parallel.",
              "Each subagent makes its own tool calls — and its own purchases."]),
            ("Why subagents change the spend math",
             ["Cost compounds: N subagents × their retries and tool calls.",
              "No single subagent looks expensive; the fleet does."]),
            ("The control",
             ["Shared daily ceilings and velocity limits across the coordinator's agents stop fleet-wide compounding."]),
        ],
        faqs=[
            ("How do I budget for subagent fleets?",
             "Scope rules to the coordinator's agents so the whole fleet shares one ceiling."),
            ("What's the biggest subagent risk?",
             "Compounding — many agents retrying the same failure in parallel."),
        ],
        related=[("Multi-agent compounding scenario", "/scenarios/multi-agent-compounding-scenario"), ("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Multi-agent governance", "/guides/multi-agent-spend-governance")],
    ),
    dict(
        slug="retry-loop",
        term="Retry loop",
        title="What is a Retry Loop? | sipi.bot Glossary",
        desc="A retry loop is the most common runaway-agent pattern: the same failed call repeated. Why it costs money and the rule that stops it.",
        h1="What is a Retry Loop?",
        lead="A retry loop is an agent repeatedly retrying a failed operation in a tight cycle — the pattern behind the $12,400 night and several incident-database entries.",
        sections=[
            ("How it happens",
             ["An agent hits a failure (rate limit, timeout, error) and retries.",
              "Each retry re-bills the operation: tokens, API call, or purchase."]),
            ("The cost shape",
             ["Cost = single-operation cost × retries. 40 retries = 40× the base cost.",
              "Loops compound across subagents and overnight runs."]),
            ("The rule that stops it",
             ["A velocity limit caps transactions per window — the loop is BLOCKED at the cap, usually within seconds."]),
        ],
        faqs=[
            ("Why don't agents stop retrying?",
             "Retrying is what they're built to do; nothing tells them the attempt is hopeless or costly."),
            ("What's the fastest fix?",
             "A velocity limit — it kills the loop at the source, not after the bill."),
        ],
        related=[("Runaway loop anatomy", "/blog/runaway-loops-anatomy"), ("Velocity limit", "/glossary/velocity-limit"), ("Retry-loop cost patterns", "/benchmarks/agent-retry-loop-cost-patterns")],
    ),
    dict(
        slug="spend-policy",
        term="Spend policy",
        title="What is a Spend Policy? | sipi.bot Glossary",
        desc="A spend policy is the set of rules that governs what an agent may buy. Glossary definition with the rule types that make one real.",
        h1="What is a Spend Policy?",
        lead="A spend policy is the enforceable set of rules governing what autonomous agents may purchase — caps, allowlists, velocity limits, categories, and approvals.",
        sections=[
            ("What a spend policy contains",
             ["Per-transaction caps — the ceiling on any single purchase.",
              "Daily/period ceilings — the rolling budget.",
              "Velocity limits — how many transactions per window.",
              "Merchant allowlists — who may be paid.",
              "Category rules — what may be bought.",
              "Approval thresholds — what waits for a human."]),
            ("Policy vs prompt",
             ["A prompt is a suggestion; a policy is a rule. The firewall enforces the policy deterministically — a prompt can't."]),
        ],
        faqs=[
            ("How is a spend policy enforced?",
             "Deterministically, in the request path — every transaction is evaluated against the rules before settlement."),
            ("Where do I start?",
             "Three rules cover most risk: a cap, an allowlist, and a velocity limit."),
        ],
        related=[("Agent spend policy template", "/templates/agent-spend-policy-template"), ("How to create a spend policy", "/how-to/how-to-create-a-spend-policy"), ("Six rule types", "/")],
    ),
    dict(
        slug="context-window",
        term="Context window",
        title="What is a Context Window? | sipi.bot Glossary",
        desc="A context window is the tokens a model sees per call — and the biggest lever on LLM cost. Glossary definition with spend implications.",
        h1="What is a Context Window?",
        lead="A context window is the number of tokens a model processes per call — system prompt, history, and tool outputs. It's also the biggest lever on LLM cost.",
        sections=[
            ("How context drives cost",
             ["Input tokens are billed per token; a 100K-token context costs ~100× a 1K one.",
              "Agent tool outputs and conversation history pile into context every turn."]),
            ("The optimization",
             ["Trim tool outputs, summarize history, cache stable prefixes.",
              "Cap per-call spend so one oversized context can't blow the budget."]),
        ],
        faqs=[
            ("Why is context the most expensive shape?",
             "Because it scales linearly with tokens, and agents re-send the same context repeatedly."),
            ("How do I control it?",
             "Context trimming, caching, and a per-transaction cap on inference calls."),
        ],
        related=[("Context window cost", "/benchmarks/llm-context-window-cost-comparison"), ("Token cache savings", "/benchmarks/token-cache-hit-savings"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs")],
    ),
]

BENCHMARKS = [
    dict(
        slug="cost-per-1m-tokens-2026",
        title="Cost Per 1M Tokens 2026 — LLM Pricing by Provider",
        desc="What 1M tokens actually cost across providers in 2026: input, output, and cache-hit rates. Approximate public pricing with verification caveats.",
        h1="Cost Per 1M Tokens 2026",
        lead="The metric everyone quotes: cost per million tokens. Here's the honest shape across providers — and why the number alone misleads for agents.",
        sections=[
            ("The shape",
             ["Input rates run from well under a dollar to tens of dollars per million tokens, depending on provider and model tier.",
              "Output tokens typically cost 3–5× input.",
              "Cache hits cost a fraction of fresh input — the biggest discount on the page."]),
            ("Why the headline number misleads",
             ["Agents don't buy a fixed number of tokens — they generate volume. Rate × volume is the real cost.",
              "A cheap rate with a retry loop loses to a pricier rate with discipline."]),
            ("What to do",
             ["Compare rates for the exact models you use, then control volume: caps, velocity limits, and caching."]),
        ],
        table=dict(
            headers=["Provider", "Input rate", "Watch"],
            rows=[
                ["OpenAI", "Varies by model tier", "Frontier rates; overage"],
                ["Anthropic", "Varies by model tier", "Output-heavy runs"],
                ["Google Gemini", "Varies by generation", "Model drift"],
                ["DeepSeek", "Low + cache discounts", "Volume at low rates"],
                ["Mistral", "Varies by tier", "Per-tier choice"],
            ],
        ),
        faqs=[
            ("Which provider is cheapest per million tokens?",
             "Rates change frequently — check current pricing for your exact models. Cheap rates at runaway volume are still expensive."),
            ("What's the real lever for agents?",
             "Volume. Caps and velocity limits beat rate shopping."),
        ],
        related=[("LLM API pricing comparison", "/benchmarks/llm-api-pricing-comparison-2026"), ("Token cost by provider", "/benchmarks/token-cost-by-provider"), ("Token cache savings", "/benchmarks/token-cache-hit-savings")],
    ),
    dict(
        slug="ai-agent-spend-roi",
        title="AI Agent Spend ROI — How to Measure It Honestly",
        desc="How to measure ROI on AI agent spend honestly: cost per completed task, avoided incidents, and the framework that prevents self-deception.",
        h1="AI Agent Spend ROI",
        lead="'Agents pay for themselves' is a claim, not a measurement. Here's the honest framework: cost per completed task, avoided incidents, and what to stop counting.",
        sections=[
            ("The honest metric",
             ["Cost per completed task = total agent spend ÷ tasks actually completed.",
              "Include everything: inference, tools, data, and failed attempts (retries count)."]),
            ("The second metric",
             ["Avoided incidents: the runaways that didn't happen. Compare your pre-firewall incident rate to post.",
              "The incident database gives reference points for what runaways cost."]),
            ("What to stop counting",
             ["Token counts and API calls without outcomes — volume isn't value.",
              "Claimed productivity without a task denominator."]),
        ],
        table=dict(
            headers=["Metric", "Formula", "Tells you"],
            rows=[
                ["Cost per task", "Total spend ÷ tasks done", "Efficiency"],
                ["Avoided incidents", "Pre vs post firewall", "Risk reduction"],
                ["Spend per agent", "Ceiling vs actual", "Budget discipline"],
            ],
        ),
        faqs=[
            ("What's a good cost per task?",
             "It depends on your task value — the honest benchmark is your own margin, not an industry number."),
            ("How do I track failed attempts?",
             "The audit log records every decision, including BLOCKED attempts that would have been failures."),
        ],
        related=[("Agent cost per task", "/benchmarks/ai-agent-cost-per-task"), ("Runaway cost average", "/benchmarks/agent-runaway-cost-average"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
    dict(
        slug="multi-agent-fleet-cost-benchmarks",
        title="Multi-Agent Fleet Cost Benchmarks — Where the Bill Goes",
        desc="Fleet cost drivers for multi-agent systems: fan-out, retries, context, and shared ceilings. Honest framework, no invented numbers.",
        h1="Multi-Agent Fleet Cost Benchmarks",
        lead="Fleets don't spend like single agents — they compound. These are the four drivers that decide the bill, and the controls for each.",
        sections=[
            ("The four drivers",
             ["Fan-out: N subagents × their tool calls. The multiplier on everything.",
              "Retries: loops multiply single-operation cost.",
              "Context: each subagent carries its own context window.",
              "Shared credentials: one key, many agents, no per-agent budget."]),
            ("The control pattern",
             ["Shared daily ceiling across the fleet.",
              "Velocity limit per agent.",
              "Category rules separating inference, data, and compute."]),
        ],
        table=dict(
            headers=["Driver", "Effect", "Control"],
            rows=[
                ["Fan-out", "Multiplies all costs", "Shared ceiling"],
                ["Retries", "Multiplies single ops", "Velocity limit"],
                ["Context", "Big per-call tokens", "Cap + trimming"],
                ["Shared keys", "No attribution", "Per-agent rules"],
            ],
        ),
        faqs=[
            ("What drives fleet bills most?",
             "Fan-out — it multiplies everything else. Control it with a shared ceiling."),
            ("Are these real benchmark numbers?",
             "No — this is the framework. Measure your own fleet with the audit log; that's the benchmark that matters."),
        ],
        related=[("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Multi-agent compounding scenario", "/scenarios/multi-agent-compounding-scenario"), ("Multi-agent governance", "/guides/multi-agent-spend-governance")],
    ),
]

BEST = [
    dict(
        slug="best-llm-cost-optimization-tools",
        title="Best LLM Cost Optimization Tools 2026 — Honest List",
        desc="The best tools for cutting LLM costs: gateways, caching, observability, and the spend firewall. Honest criteria-based list.",
        h1="Best LLM Cost Optimization Tools 2026",
        lead="LLM cost optimization splits into three jobs: reduce rate, reduce volume, stop waste. The best tools map to those jobs.",
        sections=[
            ("Reduce rate",
             ["Gateways and routers (LiteLLM, OpenRouter, Cloudflare AI Gateway) that send traffic to cheaper models.",
              "Caching layers that turn repeat input into cache hits."]),
            ("Reduce volume",
             ["Observability platforms (Langfuse, Helicone, LangSmith) that show where volume goes.",
              "Context-trimming practices and prompt engineering."]),
            ("Stop waste",
             ["sipi.bot — the only tool in this list that acts before the transaction: caps, velocity limits, allowlists, approvals."]),
        ],
        table=dict(
            headers=["Tool", "Job", "Acts"],
            rows=[
                ["LiteLLM", "Route to cheaper models", "At request time"],
                ["Langfuse", "Show cost drivers", "After usage"],
                ["Cloudflare AI Gateway", "Cache + rate limit", "At request time"],
                ["sipi.bot", "Enforce the budget", "Before spend"],
            ],
        ),
        faqs=[
            ("What's the highest-impact optimization?",
             "Model right-sizing first, then volume control, then enforcement. sipi.bot is the enforcement layer."),
            ("Do I need all three layers?",
             "Ideally — rate, volume, and waste are different problems."),
        ],
        related=[("LLM cost playbook", "/templates/llm-cost-optimization-playbook"), ("Best LLM API gateways", "/best/best-llm-api-gateways"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs")],
    ),
    dict(
        slug="best-agent-budgeting-tools",
        title="Best Agent Budgeting Tools 2026 — Honest Comparison",
        desc="The best tools for setting and enforcing agent budgets: provider limits, gateways, dashboards, and pre-spend firewalls.",
        h1="Best Agent Budgeting Tools 2026",
        lead="Budgeting for agents means two things: setting the number and enforcing it. Most tools do one; sipi.bot does the second.",
        sections=[
            ("Set the number",
             ["Provider dashboards and usage limits (OpenAI, Anthropic, cloud consoles).",
              "Cost management platforms (CloudZero, Vantage, Datadog)."]),
            ("Enforce it",
             ["Gateway budgets (LiteLLM has per-key budgets).",
              "sipi.bot — per-agent ceilings, velocity limits, and approvals enforced before the transaction."]),
            ("The honest gap",
             ["Provider limits are per-provider; gateways are per-route; cost platforms report after. Only a pre-spend layer enforces the dollar across all merchants."]),
        ],
        table=dict(
            headers=["Tool", "Sets", "Enforces", "Scope"],
            rows=[
                ["Provider limits", "Yes", "Partial", "One provider"],
                ["LiteLLM budgets", "Yes", "Yes", "Routed traffic"],
                ["CloudZero/Vantage", "Yes", "No", "Reporting"],
                ["sipi.bot", "Yes", "Yes", "All merchants"],
            ],
        ),
        faqs=[
            ("Can I set a budget per agent?",
             "Yes — sipi.bot rules are per-agent or per-key."),
            ("What's the minimum viable budget control?",
             "A daily ceiling per agent plus a per-transaction cap."),
        ],
        related=[("Budget sizing calculator", "/calculators/budget-sizing-calculator"), ("How to set AI agent budget", "/faq/how-to-set-ai-agent-budget"), ("Agent budget", "/glossary/agent-budget")],
    ),
    dict(
        slug="best-mcp-servers",
        title="Best MCP Servers 2026 — The Ones Worth Installing",
        desc="The most useful MCP servers in 2026, honestly assessed: filesystem, GitHub, browsers, databases — and the spend guard every fleet needs.",
        h1="Best MCP Servers 2026",
        lead="MCP servers give agents tools. Some are essential; some are risk. Here's the honest shortlist — and the guard that belongs in every fleet.",
        sections=[
            ("The useful ones",
             ["Filesystem and code tools — the everyday workhorses for coding agents.",
              "GitHub and CI servers — repo access, issue management.",
              "Browser automation — web research and testing.",
              "Database connectors — query access with permissions."]),
            ("The risk layer",
             ["Every server is third-party code with tool access. Vetting matters — see the MCP red flags.",
              "Any server can expose paid endpoints. The spend guard covers that."]),
            ("The guard",
             ["sipi.bot's MCP tool: one registration, and every agent in the fleet asks before it spends."]),
        ],
        table=dict(
            headers=["Server type", "Use", "Risk"],
            rows=[
                ["Filesystem", "Everyday coding", "Low"],
                ["GitHub", "Repo ops", "Low–medium"],
                ["Browser", "Web research", "Medium"],
                ["Paid tools", "Any purchase", "High — needs guard"],
            ],
        ),
        faqs=[
            ("How do I vet an MCP server?",
             "Review source, check permissions, pin versions — and gate its spend."),
            ("Is sipi.bot an MCP server?",
             "Yes — a decision tool, not a data connector."),
        ],
        related=[("MCP integration", "/integrations/mcp"), ("Red flags in MCP servers", "/redflags/red-flags-in-mcp-servers"), ("Best MCP spend tools", "/best/best-mcp-tools-for-ai-spend-control")],
    ),
]

TEMPLATES = [
    dict(
        slug="merchant-allowlist-template",
        title="Merchant Allowlist Template",
        desc="A copy-paste merchant allowlist template: vendor, category, limits, owner. Turn it into sipi.bot rules in minutes.",
        h1="Merchant Allowlist Template",
        lead="The allowlist is the single most effective rule against unknown-vendor spend. This template structures it.",
        sections=[
            ("The template",
             ["Vendor name | Category | Per-transaction limit | Daily limit | Owner | Notes",
              "Example rows:",
              "openai.com | inference | $200 | $2,000 | ML team | Primary LLM",
              "anthropic.com | inference | $200 | $2,000 | ML team | Secondary",
              "data-vendor.com | data | $100 | $500 | Research | Negotiated 2026",
              "gpu-market.com | compute | — | — | — | NOT APPROVED"]),
            ("Turning it into rules",
             ["Approved rows become allowlist entries; 'NOT APPROVED' vendors are simply absent — unknown merchants get BLOCKED by default."]),
        ],
        code=dict(
            title="Rule",
            lang="json",
            body='{\n  "type": "merchant_allowlist",\n  "action": "block",\n  "params": {\n    "allowed": ["openai.com", "anthropic.com", "data-vendor.com"]\n  },\n  "label": "Approved vendors only"\n}',
            caption="Everything else: BLOCKED.",
        ),
        faqs=[
            ("What if a vendor is legitimately new?",
             "Route new vendors through FLAGGED approval instead of hard-blocking — review then allowlist."),
            ("How often should it be reviewed?",
             "Quarterly, or when procurement approves a new vendor."),
        ],
        related=[("Merchant allowlist", "/glossary/merchant-allowlist"), ("Merchant blocklist template", "/templates/merchant-blocklist"), ("Merchant allowlists guide", "/guides/merchant-allowlists")],
    ),
    dict(
        slug="vendor-onboarding-policy",
        title="AI Vendor Onboarding Policy Template",
        desc="A template for onboarding vendors that agents will pay: due diligence, allowlist entry, limits, and review cadence.",
        h1="AI Vendor Onboarding Policy",
        lead="Every vendor your agents can pay needs an onboarding step. This policy makes it explicit.",
        sections=[
            ("The policy",
             ["1. Request — engineer submits vendor with category and expected spend.",
              "2. Review — procurement checks reputation, pricing, and contract.",
              "3. Approve — vendor added to the allowlist with limits.",
              "4. Monitor — audit log reviewed quarterly; limits adjusted.",
              "5. Remove — offboarding when unused or risky."]),
            ("What to record",
             ["Vendor, category, limits, owner, approval date, review date."]),
        ],
        code=dict(
            title="Enforcement",
            lang="text",
            body="New vendor purchases = FLAGGED until the vendor is allowlisted.\nAllowlisted vendor spend = enforced caps per category.",
            caption="The policy runs itself.",
        ),
        faqs=[
            ("Who approves vendors?",
             "Procurement or the budget owner — whoever owns vendor relationships."),
            ("What happens to unapproved vendor spend?",
             "BLOCKED if hard-allowlist, FLAGGED if you use approval thresholds."),
        ],
        related=[("Procurement teams", "/for/procurement-teams"), ("Merchant allowlist template", "/templates/merchant-allowlist-template"), ("Vendor risk", "/redflags/red-flags-in-agent-spend")],
    ),
    dict(
        slug="agent-incident-report",
        title="Agent Incident Report Template",
        desc="A template for documenting agent spend incidents: what happened, what it cost, the rule that was missing, and the fix.",
        h1="Agent Incident Report Template",
        lead="Every runaway agent incident deserves a report — it's how the pattern stops repeating. This template structures it.",
        sections=[
            ("The report",
             ["Incident: [date, time, agent]",
              "What happened: [sequence of events]",
              "Financial impact: [amount, vendor, category]",
              "Root cause: [retry loop / unknown vendor / no cap / ...]",
              "Missing control: [rule that would have stopped it]",
              "Fix: [rule added, code change]",
              "Review date: [follow-up]"]),
            ("Why it works",
             ["Each incident maps to a missing rule — the fix is usually one rule."]),
        ],
        code=dict(
            title="One-line summary",
            lang="text",
            body="Pattern: retry loop → missing velocity limit → added max 10/60s → prevented.",
            caption="Reports that end in a rule are the useful kind.",
        ),
        faqs=[
            ("Should every block be an incident?",
             "No — only actual incidents (money moved or nearly moved). BLOCKED attempts are the firewall working."),
            ("Where do I see blocked attempts?",
             "The audit log records every decision, including BLOCKED."),
        ],
        related=[("Incident response plan template", "/templates/incident-response-plan-template"), ("Runaway loop anatomy", "/blog/runaway-loops-anatomy"), ("Incident database", "/incidents/")],
    ),
    dict(
        slug="weekly-spend-review-template",
        title="Weekly Agent Spend Review Template",
        desc="A 15-minute weekly review of agent spend: what changed, what was flagged, what needs a rule. Template included.",
        h1="Weekly Agent Spend Review Template",
        lead="Fifteen minutes a week on agent spend catches drift before it becomes damage. Here's the agenda.",
        sections=[
            ("The agenda",
             ["1. Total spend vs ceiling (per agent).",
              "2. Flagged transactions — approved or denied, and why.",
              "3. Blocked attempts — legitimate or not? Adjust rules.",
              "4. New merchants — add to allowlist or block.",
              "5. Rule changes — one change max per week, reviewed."]),
            ("The output",
             ["A short log: what you reviewed, what you changed, what you're watching."]),
        ],
        code=dict(
            title="Weekly log line",
            lang="text",
            body="W34: spend 82% of ceiling. 3 flagged (all approved). 12 blocked attempts (2 legit → allowlisted). Rule: raised data cap 15%.",
            caption="One line, complete audit trail.",
        ),
        faqs=[
            ("How long should the review take?",
             "15 minutes with the audit log — it's queryable."),
            ("What's the most important number?",
             "Blocked legitimate attempts — that's where rule-tuning matters."),
        ],
        related=[("Daily budget alert template", "/templates/daily-budget-alert"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending"), ("Agent cost audit", "/checklists/agent-cost-audit")],
    ),
]

REDFLAGS = [
    dict(
        slug="red-flags-in-llm-api-bills",
        title="Red Flags in LLM API Bills — 6 Signs of Trouble",
        desc="Six red flags in your LLM API bill: unexplained volume, tier jumps, unknown providers, and more. What each one means.",
        h1="Red Flags in LLM API Bills",
        lead="Your LLM bill is a signal. These six patterns say something's wrong — usually an agent doing more than you think.",
        sections=[
            ("The six flags",
             ["1. Volume without output — spend up, deliverables flat.",
              "2. Tier jumps — usage crossing into pricier bands silently.",
              "3. Unknown line items — providers or endpoints nobody recognizes.",
              "4. Overnight spikes — activity outside business hours.",
              "5. Retry-shaped patterns — the same charge repeating in tight clusters.",
              "6. One agent's bill — a single key dominating the account."]),
            ("What to do",
             ["Each flag maps to a rule: caps, velocity limits, time-of-day rules, and per-agent budgets."]),
        ],
        table=dict(
            headers=["Red flag", "Likely cause", "Rule"],
            rows=[
                ["Volume without output", "Runaway loops", "Velocity limit"],
                ["Tier jumps", "Model drift", "Per-agent cap"],
                ["Unknown line items", "Unvetted tools", "Merchant allowlist"],
                ["Overnight spikes", "Unattended runs", "Time-of-day rule"],
            ],
        ),
        faqs=[
            ("How fast should I react to these?",
             "Same day for overnight spikes and unknown line items — they're the urgent ones."),
            ("Can the firewall stop these before the bill?",
             "Yes — the rules act on the transaction, not the invoice."),
        ],
        related=[("Red flags in agent spend", "/redflags/red-flags-in-agent-spend"), ("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="red-flags-in-agent-logs",
        title="Red Flags in Agent Logs — What to Look For",
        desc="Six red flags in agent logs that precede runaway spend: retry clusters, tool-call storms, permission escalations, and more.",
        h1="Red Flags in Agent Logs",
        lead="Agent logs tell you what's about to happen before the bill does. These six patterns are the ones to automate detection for.",
        sections=[
            ("The six flags",
             ["1. Retry clusters — the same call repeating in tight bursts.",
              "2. Tool-call storms — hundreds of tool calls in minutes.",
              "3. Permission escalations — an agent reaching for more access.",
              "4. New tool adoption — tools never seen before in the session.",
              "5. Off-hours activity — calls at 2 AM.",
              "6. Error-rate spikes — failures multiplying."]),
            ("What to do",
             ["Watch for the flags, but enforce with rules: velocity limits stop retry clusters, allowlists stop new tools, time-of-day rules stop 2 AM."]),
        ],
        table=dict(
            headers=["Red flag", "Rule"],
            rows=[
                ["Retry clusters", "Velocity limit"],
                ["Tool-call storms", "Daily ceiling"],
                ["Permission escalations", "Least-privilege + review"],
                ["New tool adoption", "Merchant allowlist"],
                ["Off-hours activity", "Time-of-day rule"],
            ],
        ),
        faqs=[
            ("Do I need log monitoring plus a firewall?",
             "Monitoring tells you what's happening; the firewall stops the damage. Run both."),
            ("Which flag is most predictive?",
             "Retry clusters — they precede most runaway incidents."),
        ],
        related=[("Red flags in LLM bills", "/redflags/red-flags-in-llm-api-bills"), ("Retry loop", "/glossary/retry-loop"), ("Runaway loop anatomy", "/blog/runaway-loops-anatomy")],
    ),
]

SCENARIOS = [
    dict(
        slug="merchant-category-drift-scenario",
        title="Scenario: An Agent Drifts Into a Category It Shouldn't Touch",
        desc="Eval Gym scenario: a research agent starts buying compute. What a category rule does when agents drift.",
        h1="Scenario: Merchant Category Drift",
        lead="A research agent is approved to buy datasets — and starts buying compute. Nobody changed the code; the agent just drifted.",
        sections=[
            ("What happens without a firewall",
             ["The compute purchases settle under the same key as the datasets. The bill grows; the categories blur; procurement finds out at month-end."]),
            ("What happens with sipi.bot",
             ["The category rule says research agents may spend on data only. The compute purchase → BLOCKED."]),
            ("The rule set",
             ["category_rule (data = allowed, compute = blocked for this agent) + per-agent daily ceiling."]),
        ],
        code=dict(
            title="The decision",
            lang="json",
            body='{\n  "decision": "BLOCKED",\n  "reason": "Category compute not allowed for this agent",\n  "rule_id": "rul_cat_03",\n  "transaction_id": "txn_77aa01"\n}',
            caption="Category rules keep agents in their lane.",
        ),
        faqs=[
            ("Is category drift common?",
             "Yes — agents pick tools and services based on task, not policy. Category rules make the policy explicit."),
            ("What if the agent legitimately needs compute?",
             "Change the rule deliberately — the point is that drift requires a decision, not an accident."),
        ],
        related=[("Category-based spending", "/glossary/category-based-spending"), ("Red flags in agent spend", "/redflags/red-flags-in-agent-spend"), ("Agent spend policy", "/glossary/spend-policy")],
    ),
    dict(
        slug="legit-workflow-false-positive-scenario",
        title="Scenario: The Firewall Blocks Something Legitimate",
        desc="Eval Gym scenario: a real purchase hits a rule. How FLAGGED and approval queues handle false positives without slowing the team.",
        h1="Scenario: Legitimate Work Blocked",
        lead="A legitimate $700 dataset purchase hits the $500 approval threshold. The workflow pauses. What happens next is the whole point of FLAGGED.",
        sections=[
            ("What happens",
             ["The transaction returns FLAGGED, not BLOCKED — it's held, not denied.",
              "It lands in the approval queue with amount, merchant, category, and the rule that fired.",
              "A human approves it in minutes; the agent proceeds."]),
            ("Why FLAGGED beats hard-blocking",
             ["Hard rules stop bad spend but also stop legitimate edge cases.",
              "Approval thresholds keep agents fast while material purchases wait for a human."]),
            ("The honest note",
             ["False positives are the cost of control. The queue makes them minutes, not blockers — and the log makes them reviewable."]),
        ],
        code=dict(
            title="The decision",
            lang="json",
            body='{\n  "decision": "FLAGGED",\n  "reason": "Over approval threshold $500",\n  "rule_id": "rul_apr_02",\n  "transaction_id": "txn_88b2c4"\n}\n\n# Human approves in the queue -> agent proceeds',
            caption="Held for review, not denied.",
        ),
        faqs=[
            ("How long does approval take?",
             "As long as your team takes — the queue is designed for minutes, and can be owned by whoever holds the budget."),
            ("Can I tune the threshold?",
             "Yes — thresholds are rules. Raise them if reviews are noise; lower them if approvals are rare."),
        ],
        related=[("Spend approval", "/glossary/spend-approval"), ("Approval workflow template", "/templates/approval-workflow"), ("How to set up an approval workflow", "/how-to/how-to-set-up-an-approval-workflow")],
    ),
    dict(
        slug="new-agent-onboarding-scenario",
        title="Scenario: A New Agent Starts Spending Before Rules Exist",
        desc="Eval Gym scenario: a freshly deployed agent spends with no rules. Why the onboarding brief and default rules matter.",
        h1="Scenario: New Agent, No Rules",
        lead="A team ships a new agent on Friday. It can spend. Nobody set a budget. The weekend passes; the bill arrives.",
        sections=[
            ("What happens without rules",
             ["The agent buys tools and data freely. Nothing screens the transactions; the first review is the invoice."]),
            ("What happens with defaults",
             ["Default rules apply to any new agent: a per-transaction cap, an allowlist of common vendors, and an approval threshold.",
              "The agent works — but every material purchase waits for a human until its own rules exist."]),
            ("The rule set",
             ["Default policy: per_transaction_cap $200 + merchant allowlist (common vendors) + approval threshold $500."]),
        ],
        code=dict(
            title="The onboarding gate",
            lang="text",
            body="Ship gate: every agent key gets default rules at creation.\nOwner adds agent-specific rules within the first week.",
            caption="Defaults cover the gap between deploy and governance.",
        ),
        faqs=[
            ("Do default rules slow new agents?",
             "Slightly — until the team tunes them. That's the trade for not having an ungoverned weekend."),
            ("Who sets defaults?",
             "The platform or finance owner — see the onboarding brief template."),
        ],
        related=[("Agent onboarding spend brief", "/templates/agent-onboarding-spend-brief"), ("Agent production readiness", "/checklists/agent-production-readiness"), ("Platform engineers", "/for/platform-engineers")],
    ),
]

COST_OF = [
    dict(
        slug="openrouter-api-cost",
        title="OpenRouter API Cost — Pricing and Agent Spend Control",
        desc="OpenRouter API cost: per-token pricing across 100+ models, the single-bill catch, and how to control agent spend.",
        h1="How Much Does the OpenRouter API Cost?",
        lead="OpenRouter gives you one API to many models — and one bill. The cost is whatever the underlying models cost, plus the convenience of a single integration.",
        sections=[
            ("How OpenRouter pricing works",
             ["Per-token pricing per model — the same rates the underlying providers charge, billed through OpenRouter.",
              "A single API key and bill across many providers."]),
            ("The hidden cost",
             ["Model-hopping: agents try pricier models as defaults change.",
              "No per-agent budget on a shared key means fleet spend is one blob."]),
            ("What it really costs",
             ["Model rate × volume. Control the volume per agent and the bill stays predictable."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Per-model rates", "Pin model choices"],
                ["Retry loops", "Velocity limits"],
                ["Shared key spend", "Per-agent budgets"],
                ["Unknown endpoints", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Is OpenRouter cheaper than direct APIs?",
             "Rates are set by the underlying providers; OpenRouter adds the aggregation. Compare current rates for the models you use."),
            ("Can I budget per agent on one key?",
             "Yes — per-agent rules in sipi.bot split the key's spend into budgets."),
        ],
        related=[("sipi.bot vs OpenRouter", "/vs/openrouter"), ("OpenRouter integration", "/integrations/openrouter"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="perplexity-api-cost",
        title="Perplexity API Cost — Pricing and Agent Spend Control",
        desc="Perplexity API cost: what the search API charges, what drives the bill, and how to control agent spend on it.",
        h1="How Much Does the Perplexity API Cost?",
        lead="Perplexity's API gives agents grounded search answers. The cost is per-request with model-dependent pricing — and search-happy agents generate requests.",
        sections=[
            ("How Perplexity pricing works",
             ["Per-request pricing tied to the model used, with web-search queries billed per call.",
              "Usage scales directly with how often agents ask."]),
            ("The hidden cost",
             ["Retry loops re-ask the same question — each one billed.",
              "Agents that search excessively in loops multiply requests."]),
            ("What it really costs",
             ["Per-request rate × request volume. Velocity limits and per-agent caps control the volume."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Per-request rates", "Model selection"],
                ["Retry loops", "Velocity limit"],
                ["Excessive search", "Per-agent daily ceiling"],
            ],
        ),
        faqs=[
            ("Is Perplexity API priced per token or per request?",
             "Per-request for search queries, with model-based pricing. Check current docs for exact rates."),
            ("Can I cap a research agent's search spend?",
             "Yes — per-agent ceilings and category rules."),
        ],
        related=[("Research agents", "/use-cases/research-agents"), ("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="xai-grok-api-cost",
        title="xAI Grok API Cost — Pricing and Agent Spend Control",
        desc="xAI Grok API cost: token pricing, what drives the bill, and how to control agent spend on Grok models.",
        h1="How Much Does the Grok API Cost?",
        lead="Grok's API is priced per token like other frontier APIs. For agents, the bill is rate × volume — with the usual loop risks.",
        sections=[
            ("How Grok pricing works",
             ["Per-token pricing by model, with input and output rates.",
              "Check xAI's current pricing for exact numbers — rates move."]),
            ("The hidden cost",
             ["Retry loops and fan-out multiply volume on whatever rate you chose.",
              "Long-context agent runs make input tokens the dominant cost."]),
            ("What it really costs",
             ["Rate × volume × context. Caps and velocity limits control all three."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Token rates", "Model selection"],
                ["Retry loops", "Velocity limit"],
                ["Long contexts", "Context caps + trimming"],
                ["Fleet volume", "Per-agent ceilings"],
            ],
        ),
        faqs=[
            ("Is Grok competitive on price?",
             "Rates vary by model and change over time — compare current per-token pricing for your workload."),
            ("Can sipi.bot control Grok spend?",
             "Yes — category rules, per-agent caps, and velocity limits apply to any API merchant."),
        ],
        related=[("Cost per 1M tokens", "/benchmarks/cost-per-1m-tokens-2026"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs"), ("LLM API pricing comparison", "/benchmarks/llm-api-pricing-comparison-2026")],
    ),
    dict(
        slug="mistral-api-cost",
        title="Mistral API Cost — Pricing and Agent Spend Control",
        desc="Mistral API cost: token pricing, what drives the bill, and how to control agent spend on Mistral models.",
        h1="How Much Does the Mistral API Cost?",
        lead="Mistral's API is per-token, with competitive rates and a range of model sizes. For agent fleets, model choice is the first lever.",
        sections=[
            ("How Mistral pricing works",
             ["Per-token pricing by model size — compact models cost less than frontier tiers.",
              "Rates are competitive; volume is the variable."]),
            ("The hidden cost",
             ["Agents drifting to larger models silently raise the rate.",
              "Retry loops and parallel fleets multiply volume."]),
            ("What it really costs",
             ["Model rate × volume. Pin the model, cap the volume."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Model size", "Route to right-size models"],
                ["Retry loops", "Velocity limit"],
                ["Fleet volume", "Per-agent ceilings"],
            ],
        ),
        faqs=[
            ("Is Mistral cheaper than other providers?",
             "Competitive rates, especially on compact models — but total cost is rate × volume. Verify current pricing."),
            ("Can I cap Mistral spend per agent?",
             "Yes — per-agent ceilings and category rules."),
        ],
        related=[("Cost per 1M tokens", "/benchmarks/cost-per-1m-tokens-2026"), ("ML engineers", "/for/ml-engineers"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
]

HOW_TO = [
    dict(
        slug="how-to-set-up-an-approval-workflow",
        title="How to Set Up an Approval Workflow for Agent Spend",
        desc="Set up a human-in-the-loop approval workflow for agent spend in minutes: thresholds, queue, owners, and review cadence.",
        h1="How to Set Up an Approval Workflow",
        lead="Approval workflows are how agents stay fast without spending unreviewed. Here's the setup in four steps.",
        sections=[
            ("Step 1 — Set the threshold",
             ["Pick the amount above which purchases wait for a human. Start with your largest 'no review needed' purchase."]),
            ("Step 2 — Configure the rule",
             ["Set an approval threshold rule with action=flag. Transactions over the threshold return FLAGGED and route to the queue."]),
            ("Step 3 — Name the owner",
             ["Assign the queue to the budget owner. Decide the response-time target and escalation path."]),
            ("Step 4 — Review weekly",
             ["Review the queue weekly: approve, deny, and tune the threshold. The audit log shows the whole history."]),
        ],
        code=dict(
            title="Rule",
            lang="json",
            body='{\n  "type": "approval_threshold",\n  "action": "flag",\n  "params": {"over": 500, "currency": "USD"},\n  "label": "Flag purchases over $500"\n}',
            caption="Over the threshold → FLAGGED → human decides.",
        ),
        faqs=[
            ("What if approvals pile up?",
             "Raise the threshold — or add more reviewers. The queue is designed to be minutes, not days."),
            ("Can different agents have different thresholds?",
             "Yes — rules are per-agent."),
        ],
        related=[("Approval workflow template", "/templates/approval-workflow"), ("Spend approval", "/glossary/spend-approval"), ("Agent spend approval policy", "/templates/agent-spend-approval-policy")],
    ),
    dict(
        slug="how-to-create-a-spend-policy",
        title="How to Create an Agent Spend Policy",
        desc="Create an agent spend policy in five steps: inventory, rules, defaults, approvals, review. Template included.",
        h1="How to Create an Agent Spend Policy",
        lead="A spend policy is a small document that maps to real rules. Five steps, one afternoon.",
        sections=[
            ("Step 1 — Inventory",
             ["List your spend-capable agents: what they buy, from whom, with whose money."]),
            ("Step 2 — Set the rules",
             ["Per agent: a cap, an allowlist, a velocity limit, an approval threshold. Start with three rules."]),
            ("Step 3 — Set defaults",
             ["Default rules for new agents so ungoverned weekends don't happen."]),
            ("Step 4 — Define approvals",
             ["Who reviews FLAGGED transactions and how fast."]),
            ("Step 5 — Review monthly",
             ["Tune rules against the audit log. One change at a time, measured."]),
        ],
        code=dict(
            title="Minimum viable policy",
            lang="text",
            body="Every agent gets: a cap, an allowlist, an owner.\nNew agents inherit defaults until their own rules exist.\nThe audit log is reviewed monthly.",
            caption="Three lines, enforceable.",
        ),
        faqs=[
            ("How long should the policy document be?",
             "One page. The rules it maps to matter more than the prose."),
            ("Who owns it?",
             "The budget owner — platform lead, finance, or CTO depending on org."),
        ],
        related=[("Agent spend policy template", "/templates/agent-spend-policy-template"), ("Spend policy best practices", "/guides/agent-spend-policy-best-practices"), ("Spend policy glossary", "/glossary/spend-policy")],
    ),
    dict(
        slug="how-to-integrate-sipi-bot-with-mcp",
        title="How to Integrate sipi.bot with MCP",
        desc="Add sipi.bot's MCP tool to any MCP client: registration, first guarded call, and the rules to start with.",
        h1="How to Integrate sipi.bot with MCP",
        lead="One config block gives any MCP client a spending policy. Here's the integration in three steps.",
        sections=[
            ("Step 1 — Register the tool",
             ["Add the sipi.bot MCP server to your client config. Claude Code, Cursor, and Hermes register it natively."]),
            ("Step 2 — Guard the spend",
             ["In your agent's code, call the tool before any purchase with amount, merchant, and category. Branch on APPROVED / BLOCKED / FLAGGED."]),
            ("Step 3 — Start with three rules",
             ["A per-transaction cap, a merchant allowlist, and a velocity limit cover the most common runaway patterns."]),
        ],
        code=dict(
            title="Config",
            lang="json",
            body='{\n  "mcpServers": {\n    "sipi": {\n      "command": "npx",\n      "args": ["-y", "@sipi/bot-mcp"]\n    }\n  }\n}',
            caption="Register once; every agent in the client gets the guard.",
        ),
        faqs=[
            ("Which clients support MCP?",
             "Claude Code, Cursor, Hermes, and any MCP-native runtime."),
            ("Is the decision fast enough?",
             "~5 ms, no model call — negligible next to the purchase itself."),
            ("What if I don't use MCP?",
             "Use the HTTP API or CLI — same decisions, different transport."),
        ],
        related=[("MCP integration", "/integrations/mcp"), ("MCP tutorial", "/tutorials/integrate-with-claude-code"), ("MCP glossary", "/glossary/mcp")],
    ),
]

ALTERNATIVES_TO = [
    dict(
        slug="stripe-radar",
        title="Stripe Radar Alternative for Agent Spend Control",
        desc="Stripe Radar stops card fraud; it doesn't stop runaway agent spend. The alternative layer: a pre-spend firewall. Honest comparison.",
        h1="Stripe Radar Alternative — For Agent Spend",
        lead="Stripe Radar is the right tool for stolen cards and chargebacks. It's the wrong tool for 'your agent bought from an unknown vendor 40 times.' Here's the alternative layer.",
        sections=[
            ("What Stripe Radar does well",
             ["Fraud detection on card payments: stolen cards, chargebacks, identity signals.",
              "Automatic blocking of suspicious human purchases."]),
            ("Where it can't help",
             ["Radar flags fraud, not policy violations. To Stripe, a runaway agent's purchases look like legitimate API usage.",
              "No merchant allowlist, category budgets, or approval queue for agent transactions."]),
            ("The alternative",
             ["sipi.bot: a pre-spend firewall that evaluates every agent transaction against your rules before settlement."]),
        ],
        table=dict(
            headers=["Dimension", "Stripe Radar", "sipi.bot"],
            rows=[
                ["Detects", "Card fraud", "Spend policy violations"],
                ["Acts", "At payment processing", "Before settlement"],
                ["Rules", "Fraud signals", "Caps, allowlists, velocity"],
                ["Agent scope", "None", "Every transaction"],
            ],
        ),
        faqs=[
            ("Do I need both?",
             "Yes — Radar for card fraud, sipi.bot for agent spend. Different threats."),
            ("Can sipi.bot work with Stripe?",
             "Yes — agents that pay through Stripe call sipi.bot first; approved transactions settle normally."),
        ],
        related=[("sipi.bot vs Stripe Radar", "/vs/stripe-radar"), ("sipi.bot vs Stripe Billing", "/vs/stripe-billing"), ("Stripe integration", "/integrations/stripe")],
    ),
    dict(
        slug="openrouter",
        title="OpenRouter Alternative for Agent Spend Control",
        desc="OpenRouter routes to many models; it doesn't enforce spend policy. The alternative layer for controlling what agents spend. Honest comparison.",
        h1="OpenRouter Alternative — For Agent Spend",
        lead="OpenRouter is a routing layer — one API to many models. It optimizes access, not spend. Here's the layer that enforces the budget.",
        sections=[
            ("What OpenRouter does well",
             ["One API to 100+ models, usage analytics, and per-key control.",
              "Great for model flexibility and avoiding provider lock-in."]),
            ("Where it can't help",
             ["Routing isn't enforcement: no merchant allowlist, category budgets, or approval queue.",
              "Rate limits cap requests, not dollars."]),
            ("The alternative",
             ["sipi.bot: a pre-spend decision layer in front of OpenRouter — the agent asks before it spends."]),
        ],
        table=dict(
            headers=["Dimension", "OpenRouter", "sipi.bot"],
            rows=[
                ["Role", "Model routing", "Spend enforcement"],
                ["Controls", "Keys, analytics", "Caps, allowlists, approvals"],
                ["Unit", "Requests", "Dollars"],
                ["Decision", "Route to model", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Do they compete?",
             "No — they compose: sipi.bot decides, OpenRouter routes."),
            ("Can I budget per agent on OpenRouter?",
             "Per-key controls exist; per-agent dollar budgets come from the firewall layer."),
        ],
        related=[("sipi.bot vs OpenRouter", "/vs/openrouter"), ("OpenRouter integration", "/integrations/openrouter"), ("OpenRouter cost", "/cost-of/openrouter-api-cost")],
    ),
    dict(
        slug="langsmith",
        title="LangSmith Alternative for Agent Spend Control",
        desc="LangSmith traces agent runs; it doesn't stop runaway spend. The alternative layer: a pre-spend firewall. Honest comparison.",
        h1="LangSmith Alternative — For Agent Spend",
        lead="LangSmith is the observability layer for LangChain and LangGraph. It shows you what agents did — after they did it. The alternative layer stops the money.",
        sections=[
            ("What LangSmith does well",
             ["Deep tracing, evaluation, and cost tracking for LangChain workloads.",
              "The standard for debugging agent runs."]),
            ("Where it can't help",
             ["Observability is post-hoc: a chart of the $12,400 night doesn't stop it.",
              "No merchant allowlist, approval queue, or pre-spend rule engine."]),
            ("The alternative",
             ["sipi.bot: a pre-spend firewall that decides before the transaction — complementary to LangSmith, not a replacement for it."]),
        ],
        table=dict(
            headers=["Dimension", "LangSmith", "sipi.bot"],
            rows=[
                ["Role", "Trace agent runs", "Gate agent spend"],
                ["When it acts", "After requests", "Before transactions"],
                ["Controls", "Traces, evals", "Caps, allowlists, approvals"],
                ["Decision", "Insights", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Should I replace LangSmith?",
             "No — keep tracing. Add the firewall; they're different layers."),
            ("Can decisions feed into LangSmith?",
             "Yes — the audit log is API-queryable, so decisions can join traces."),
        ],
        related=[("sipi.bot vs LangSmith", "/vs/langsmith"), ("Best observability tools", "/best/best-ai-agent-observability-tools"), ("LangChain integration", "/integrations/langchain")],
    ),
]

# --- hub metadata -----------------------------------------------------------
# (all target sections already have hubs; patches add cards)
