"""Round 25 pSEO data — sipi.bot (2026-08-08).

Sixth round. Depth in the thinnest remaining sections (tutorials, policies,
limits, learn, guides) + a few targeted additions (sectors, use-cases,
glossary, scenarios). Blog posts are added separately via the generator
(lib/generate_content.py POSTS + _body_for).

All pages land in EXISTING repo-root dirs — no plumbing changes.
Content rules unchanged: honest, no fabricated stats, ~5 ms / $99-$499 /
MIT core / 3 decisions / 6 rule types / HTTP+MCP+CLI / rail-agnostic.
"""

TUTORIALS = [
    dict(
        slug="integrate-with-langchain",
        title="How to Integrate sipi.bot with LangChain",
        desc="Step-by-step: add sipi.bot's guard to a LangChain agent in minutes. One tool, three rules, deterministic spend control.",
        h1="Integrate sipi.bot with LangChain",
        lead="LangChain agents call tools; tools spend money. Adding the guard is a few lines — here's the exact walkthrough.",
        sections=[
            ("Step 1 — Get a key",
             ["Create an agent key from the dashboard (or use the evaluate endpoint anonymously on self-host)."]),
            ("Step 2 — Add the guard tool",
             ["Register sipi.bot as a tool the agent can call before any purchase."]),
            ("Step 3 — Call it before spending",
             ["In the tool that spends, call the guard with amount, merchant, and category. Branch on APPROVED / BLOCKED / FLAGGED."]),
            ("Step 4 — Start with three rules",
             ["A per-transaction cap, a merchant allowlist, and a velocity limit."]),
        ],
        code=dict(
            title="Guard call",
            lang="python",
            body='import requests\nfrom langchain.agents import tool\n\n@tool\ndef guard_spend(amount: float, merchant: str, category: str) -> str:\n    r = requests.post(\n        "https://sipi.bot/v1/transactions/evaluate",\n        json={"amount": amount, "merchant": merchant, "category": category},\n        headers={"Authorization": "Bearer YOUR_KEY"},\n    )\n    return r.json()["decision"]  # APPROVED | BLOCKED | FLAGGED',
            caption="Deterministic, ~5 ms, no model call.",
        ),
        faqs=[
            ("Does this slow the agent?",
             "No — about 5 ms per check, only on spend actions."),
            ("Is there a LangChain wrapper?",
             "A client wrapper takes a few lines — or just use the HTTP call above."),
        ],
        related=[("LangChain integration", "/integrations/langchain"), ("LangGraph", "/integrations/langgraph"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="integrate-with-crewai",
        title="How to Integrate sipi.bot with CrewAI",
        desc="Step-by-step: add a spend guard to CrewAI crews. Fleet-level budgets for role-based agent teams.",
        h1="Integrate sipi.bot with CrewAI",
        lead="CrewAI runs crews of role-based agents in parallel — which compounds spend. The guard tool gives the whole crew a budget.",
        sections=[
            ("Step 1 — Add the tool",
             ["Register the guard as a tool available to the crew's agents."]),
            ("Step 2 — Guard the spending task",
             ["In any task that spends, call the guard first and branch on the decision."]),
            ("Step 3 — Set fleet rules",
             ["A shared daily ceiling across the crew, plus a velocity limit."]),
        ],
        code=dict(
            title="Crew tool",
            lang="python",
            body='from crewai import Agent, Task, Crew\nfrom sipi_guard import sipi_guard\n\nagent = Agent(role="purchaser", tools=[sipi_guard], ...)\n# decision = sipi_guard(amount=500, merchant="api.vendor.com", category="api")',
            caption="One tool, whole-crew enforcement.",
        ),
        faqs=[
            ("Does the shared ceiling cover parallel agents?",
             "Yes — rules scoped to the crew's agents share one budget."),
            ("Can I cap per role?",
             "Yes — per-agent rules let each role run its own ceiling."),
        ],
        related=[("CrewAI integration", "/integrations/crewai"), ("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Multi-agent governance", "/guides/multi-agent-spend-governance")],
    ),
    dict(
        slug="integrate-with-n8n",
        title="How to Integrate sipi.bot with n8n",
        desc="Step-by-step: add a spend-firewall node to n8n workflows. Branch on APPROVED, BLOCKED, or FLAGGED before any paid step.",
        h1="Integrate sipi.bot with n8n",
        lead="n8n workflows run on schedules — including at 2 AM. A firewall node before any paid step keeps the automation honest.",
        sections=[
            ("Step 1 — Add an HTTP Request node",
             ["Create an HTTP Request node pointing at /v1/transactions/evaluate with your key."]),
            ("Step 2 — Branch on the decision",
             ["APPROVED → continue to the paid step. BLOCKED → stop and log. FLAGGED → pause for approval."]),
            ("Step 3 — Schedule-safe rules",
             ["Add a time-of-day rule so overnight runs wait for a human."]),
        ],
        code=dict(
            title="Node config",
            lang="text",
            body="HTTP Request → https://sipi.bot/v1/transactions/evaluate\nBody: {\"amount\": 50, \"merchant\": \"api.vendor.com\", \"category\": \"api\"}\nBranch: APPROVED → continue | BLOCKED → stop | FLAGGED → notify",
            caption="Three branches, one deterministic decision.",
        ),
        faqs=[
            ("Does this work in self-hosted n8n?",
             "Yes — it's just HTTP."),
            ("Can I cap all workflows at once?",
             "Yes — shared rules apply across workflows."),
        ],
        related=[("n8n integration", "/integrations/n8n"), ("Workflow automation", "/for/devops-automation"), ("Time-of-day rule", "/glossary/time-of-day-rule")],
    ),
    dict(
        slug="set-up-category-rules",
        title="How to Set Up Category Rules",
        desc="Step-by-step: budget agent spend by category — compute, data, SaaS, ads. Keep agents in their lane.",
        h1="Set Up Category Rules",
        lead="Category rules give each spend type its own budget. Here's the setup in three steps.",
        sections=[
            ("Step 1 — Define your categories",
             ["Map your ledger to categories: compute, data, SaaS, ads, payments, inference."]),
            ("Step 2 — Set per-category limits",
             ["For each category: allow, cap, or block. E.g. data allowed up to $200/day, compute blocked."]),
            ("Step 3 — Test with a flagged run",
             ["Send a few test transactions through the playground and confirm the decisions."]),
        ],
        code=dict(
            title="Example",
            lang="json",
            body='{\n  "category_rule": {\n    "data": {"action": "allow", "daily_max": 200},\n    "compute": {"action": "block"},\n    "ads": {"action": "flag", "over": 100}\n  }\n}',
            caption="Categories become decisions.",
        ),
        faqs=[
            ("What if a category isn't in the rule?",
             "Set a default: unspecified categories can default to allow, block, or flag."),
            ("Do categories affect the audit log?",
             "Yes — every decision records the category."),
        ],
        related=[("Category rule", "/glossary/category-rule"), ("Category drift scenario", "/scenarios/merchant-category-drift-scenario"), ("Cost allocation template", "/templates/cost-allocation-template")],
    ),
    dict(
        slug="set-up-time-of-day-rules",
        title="How to Set Up Time-of-Day Rules",
        desc="Step-by-step: restrict or flag agent spend outside business hours — the control that stops the 2 AM runaway.",
        h1="Set Up Time-of-Day Rules",
        lead="The classic runaway happens at 2 AM. A time-of-day rule makes unattended overnight spend require a human.",
        sections=[
            ("Step 1 — Pick the window",
             ["Your team's business hours, per agent or fleet."]),
            ("Step 2 — Choose the action",
             ["BLOCK outside the window (strict), or FLAG (overnight purchases wait for review)."]),
            ("Step 3 — Cover timezones",
             ["For global fleets, set windows per agent group."]),
        ],
        code=dict(
            title="Example",
            lang="json",
            body='{\n  "time_of_day": {\n    "window": ["09:00", "18:00"],\n    "tz": "Europe/Athens",\n    "outside": "flag"\n  }\n}',
            caption="Overnight = human review.",
        ),
        faqs=[
            ("What about legit overnight batch jobs?",
             "Set the action to FLAG — they wait for review instead of being blocked."),
            ("Does it apply per agent?",
             "Yes — windows can differ per agent or fleet."),
        ],
        related=[("Time-of-day rule", "/glossary/time-of-day-rule"), ("Overnight runaway scenario", "/scenarios/overnight-runaway-scenario"), ("Off-hours red flag", "/redflags/off-hours-billing-activity")],
    ),
    dict(
        slug="create-an-approval-queue",
        title="How to Create an Approval Queue",
        desc="Step-by-step: set up a human-in-the-loop approval queue for flagged agent spend — thresholds, owners, and review cadence.",
        h1="Create an Approval Queue",
        lead="Approval queues keep agents fast while material purchases wait for a human. Setup in three steps.",
        sections=[
            ("Step 1 — Set the threshold",
             ["The amount above which purchases are FLAGGED instead of auto-approved."]),
            ("Step 2 — Name the owner",
             ["Who reviews the queue, and the response-time target."]),
            ("Step 3 — Review weekly",
             ["Approve, deny, and tune the threshold against the audit log."]),
        ],
        code=dict(
            title="Rule",
            lang="json",
            body='{\n  "approval_threshold": {"over": 500, "currency": "USD", "action": "flag"}\n}',
            caption="Over the threshold → human decides.",
        ),
        faqs=[
            ("What happens to flagged items?",
             "They stay in the queue until a human approves or denies — nothing moves in between."),
            ("Can thresholds differ per agent?",
             "Yes — rules are per-agent."),
        ],
        related=[("Approval queue", "/glossary/approval-queue"), ("Approval workflow template", "/templates/approval-workflow"), ("False-positive scenario", "/scenarios/legit-workflow-false-positive-scenario")],
    ),
    dict(
        slug="self-host-in-docker",
        title="How to Self-Host sipi.bot in Docker",
        desc="Step-by-step: run the MIT-licensed sipi.bot core in Docker — volume for the store, health checks, and first rule.",
        h1="Self-Host sipi.bot in Docker",
        lead="The core is MIT-licensed and self-hosts anywhere Docker runs. Here's the container walkthrough.",
        sections=[
            ("Step 1 — Pull and run",
             ["Clone the repo and build the image (or use the published image)."]),
            ("Step 2 — Mount the store",
             ["Persist the SQLite store on a volume so rules survive restarts."]),
            ("Step 3 — Health check",
             ["The container exposes /health — wire your orchestrator's probe to it."]),
            ("Step 4 — First rule",
             ["Create your first cap via the API with the admin token."]),
        ],
        code=dict(
            title="Docker",
            lang="bash",
            body='docker build -t sipi-bot .\ndocker run -d -p 8080:8080 \\\n  -v sipi-data:/data \\\n  -e SPENDFIREWALL_DB=/data/spendfirewall.db \\\n  sipi-bot\n# health: curl localhost:8080/health',
            caption="Self-host in minutes; see the self-host guide for full config.",
        ),
        faqs=[
            ("Is the Docker image published?",
             "Build from the repo (MIT core). The self-host guide has the full config."),
            ("Do hosted features work self-hosted?",
             "The decision engine is complete; the dashboard and managed approval queue are hosted-only."),
        ],
        related=[("Self-host guide", "/self-hosted/"), ("Can I self-host", "/pricing-questions/can-i-self-host-sipi-bot"), ("Open source", "https://github.com/kindrat86/sipi-bot")],
    ),
]

POLICIES = [
    dict(
        slug="category-rule-policy",
        title="Category Rule Policy — Template",
        desc="A copy-paste category rule policy: which spend types are allowed, capped, or blocked — and how to enforce it.",
        h1="Category Rule Policy",
        lead="A category policy defines what agents may buy — by spend type. Here's the template and the enforcement.",
        sections=[
            ("The policy",
             ["Allowed categories with limits: [CATEGORY — limit].",
              "Blocked categories: [LIST].",
              "Flagged categories above threshold: [LIST].",
              "Default for unspecified categories: [allow / block / flag]."]),
            ("Enforcement",
             ["Each category maps to a category rule; transactions outside policy get BLOCKED or FLAGGED."]),
        ],
        code=dict(
            title="Policy → rule",
            lang="json",
            body='{\n  "category_rule": {\n    "data": {"action": "allow", "daily_max": 200},\n    "compute": {"action": "block"},\n    "default": "flag"\n  }\n}',
            caption="The policy becomes decisions.",
        ),
        faqs=[
            ("What's a good default for unspecified categories?",
             "FLAG — it catches drift without blocking everything."),
            ("How often to review?",
             "Monthly, or when agents change roles."),
        ],
        related=[("Category rule", "/glossary/category-rule"), ("Category drift scenario", "/scenarios/merchant-category-drift-scenario"), ("Cost allocation", "/templates/cost-allocation-template")],
    ),
    dict(
        slug="time-of-day-policy",
        title="Time-of-Day Spend Policy — Template",
        desc="A copy-paste policy for when agents may spend: business hours, overnight rules, and timezone handling.",
        h1="Time-of-Day Spend Policy",
        lead="A time-of-day policy decides what happens when agents spend outside business hours — the window where runaways happen.",
        sections=[
            ("The policy",
             ["Allowed window: [09:00–18:00, TZ].",
              "Outside window: [BLOCK / FLAG].",
              "Approved overnight exceptions: [AGENT / REASON].",
              "Review cadence for overnight flags: [NEXT MORNING]."]),
            ("Enforcement",
             ["The rule evaluates the transaction timestamp against the window."]),
        ],
        code=dict(
            title="Policy → rule",
            lang="json",
            body='{\n  "time_of_day": {\n    "window": ["09:00", "18:00"],\n    "tz": "Europe/Athens",\n    "outside": "flag"\n  }\n}',
            caption="Overnight spend waits for a human.",
        ),
        faqs=[
            ("What if my team is global?",
             "Set per-agent windows for each region."),
            ("Block or flag?",
             "FLAG is the balanced default — overnight work proceeds after morning review."),
        ],
        related=[("Time-of-day rule", "/glossary/time-of-day-rule"), ("Overnight runaway scenario", "/scenarios/overnight-runaway-scenario"), ("Off-hours red flag", "/redflags/off-hours-billing-activity")],
    ),
    dict(
        slug="approval-threshold-policy",
        title="Approval Threshold Policy — Template",
        desc="A copy-paste policy for human approval of agent spend: thresholds, queue owners, and escalation.",
        h1="Approval Threshold Policy",
        lead="An approval policy defines what waits for a human — the control that keeps agents fast without unreviewed spend.",
        sections=[
            ("The policy",
             ["Auto-approve under: [$].",
              "Require approval over: [$].",
              "Queue owner: [NAME].",
              "Response target: [15 MIN].",
              "Escalation after: [1 HOUR → NAME]."]),
            ("Enforcement",
             ["Transactions over the threshold return FLAGGED and route to the queue."]),
        ],
        code=dict(
            title="Policy → rule",
            lang="json",
            body='{\n  "approval_threshold": {"over": 500, "currency": "USD", "action": "flag"}\n}',
            caption="Material spend waits for a human.",
        ),
        faqs=[
            ("What's a good starting threshold?",
             "Your largest 'no review needed' purchase — typically $100–$500."),
            ("Who should own the queue?",
             "The budget owner: finance ops, platform lead, or team lead."),
        ],
        related=[("Approval queue", "/glossary/approval-queue"), ("Approval workflow template", "/templates/approval-workflow"), ("Spend approval", "/glossary/spend-approval")],
    ),
]

LIMITS = [
    dict(
        slug="per-agent-spend-limits",
        title="Per-Agent Spend Limits — How They Work",
        desc="Per-agent spend limits give every agent its own budget. How to set them, what they stop, and what they don't.",
        h1="Per-Agent Spend Limits",
        lead="A per-agent limit is the agent's own budget — a ceiling it can't exceed regardless of what it's doing.",
        sections=[
            ("What it covers",
             ["Every transaction the agent attempts, across all merchants.",
              "Daily and monthly ceilings scoped to one agent key."]),
            ("What it stops",
             ["One runaway agent bleeding the shared bill.",
              "Fleet-wide compounding — each agent is bounded individually."]),
            ("What it doesn't",
             ["Cross-agent coordination: 50 agents each under their own limit can still sum large. Pair with a shared fleet cap for that."]),
        ],
        table=dict(
            headers=["Limit", "Scope", "Catches"],
            rows=[
                ["Per-agent daily", "One agent", "Runaway single agent"],
                ["Per-agent monthly", "One agent", "Month-long drift"],
                ["Fleet shared", "All agents", "Compounding"],
            ],
        ),
        faqs=[
            ("How do I set them?",
             "Rules are per-agent or per-key — assign a ceiling at key creation."),
            ("What happens when hit?",
             "Further transactions return BLOCKED until the window resets or you raise the limit."),
        ],
        related=[("Set up per-agent limits", "/tutorials/set-up-per-agent-limits"), ("Agent budget", "/glossary/agent-budget"), ("Recommended limits", "/limits/recommended-limits-by-use-case")],
    ),
    dict(
        slug="daily-spend-limits",
        title="Daily Spend Limits — How They Work",
        desc="Daily spend limits cap what an agent (or fleet) can spend per day. How they work and how to set the right number.",
        h1="Daily Spend Limits",
        lead="A daily spend limit is a rolling 24-hour ceiling — the budget that resets every morning, enforced all day.",
        sections=[
            ("How it works",
             ["All transactions sum against the daily ceiling.",
              "When the sum crosses the ceiling, further transactions are BLOCKED (or FLAGGED)."]),
            ("Setting the number",
             ["Estimate legitimate daily spend × 1.5 — tight enough to catch runaways, loose enough to work.",
              "Start conservative; loosen with data from the audit log."]),
            ("Why daily beats monthly",
             ["A monthly cap only catches the problem at month-end. A daily cap catches it that day."]),
        ],
        faqs=[
            ("When does the window reset?",
             "Typically at midnight in your configured timezone."),
            ("Can different agents have different daily limits?",
             "Yes — per-agent rules."),
        ],
        related=[("Daily spend ceiling", "/glossary/daily-spend-ceiling"), ("Daily ceiling policy", "/policies/daily-ceiling-policy"), ("Budget sizing calculator", "/calculators/budget-sizing-calculator")],
    ),
    dict(
        slug="monthly-spend-limits",
        title="Monthly Spend Limits — How They Work",
        desc="Monthly spend limits give a per-month budget envelope. How they work with daily caps for layered control.",
        h1="Monthly Spend Limits",
        lead="A monthly limit is the budget envelope for the month — best used as the outer layer above daily caps.",
        sections=[
            ("How it works",
             ["Transactions accumulate against the monthly ceiling.",
              "The monthly number is the accounting envelope; the daily caps are the enforcement."]),
            ("Why you need both",
             ["A monthly limit alone lets a runaway blow the month in a day.",
              "Daily caps stop the runaway; the monthly limit keeps the month honest."]),
        ],
        table=dict(
            headers=["Layer", "Job"],
            rows=[
                ["Daily caps", "Stop runaways day by day"],
                ["Monthly limit", "Keep the month's envelope"],
                ["Per-agent limits", "Attribute and bound each agent"],
            ],
        ),
        faqs=[
            ("Should I use monthly or daily?",
             "Both — monthly for the envelope, daily for enforcement."),
            ("What happens at the monthly cap?",
             "Further transactions are BLOCKED until the month resets or you raise it."),
        ],
        related=[("Agent budget template", "/templates/agent-budget-template"), ("Daily spend limits", "/limits/daily-spend-limits"), ("How to set AI spend limit", "/faq/how-to-set-ai-spend-limit")],
    ),
]

LEARN = [
    dict(
        slug="the-agent-economy-explained",
        title="The Agent Economy Explained",
        desc="The agent economy: how autonomous agents buy compute, data, and services — and why the control layer is the missing piece.",
        h1="The Agent Economy Explained",
        lead="Agents are becoming customers: buying compute, data, and services on machine rails. The agent economy is real — and it needs a control layer.",
        sections=[
            ("What the agent economy is",
             ["Agents purchasing services autonomously — compute, data, APIs — via machine payment rails.",
              "x402, AP2, and AgentKit are the rails; agent-to-agent commerce is the pattern."]),
            ("Why it's growing",
             ["Every agent framework now ships tool access; every tool can be a purchase.",
              "The cost of a purchase decision is dropping to milliseconds."]),
            ("The missing piece",
             ["Rails move money; nothing screens it before settlement.",
              "The control layer — a pre-spend firewall — is what makes the economy safe to scale."]),
        ],
        faqs=[
            ("Is the agent economy speculative?",
             "The rails are live and products ship on them. What's immature is control — which is the gap."),
            ("What does this mean for a developer?",
             "If your agents can spend, they need a policy gate before the rail."),
        ],
        related=[("Agentic payment", "/glossary/agentic-payment"), ("Agentic commerce", "/use-cases/agentic-commerce"), ("x402", "/glossary/x402")],
    ),
    dict(
        slug="how-autonomous-agents-spend-money",
        title="How Autonomous Agents Spend Money",
        desc="The mechanics of agent spend: tool calls, payment rails, and provider APIs. Where the money goes and how to control it.",
        h1="How Autonomous Agents Spend Money",
        lead="Agents spend through three channels: provider APIs, third-party tools, and payment rails. Each needs a different control.",
        sections=[
            ("Channel 1 — Provider APIs",
             ["LLM and cloud APIs billed per token or per request.",
              "Control: caps, model selection, caching."]),
            ("Channel 2 — Third-party tools",
             ["Data, compute, and SaaS tools called from agent loops.",
              "Control: merchant allowlists, per-transaction caps."]),
            ("Channel 3 — Payment rails",
             ["x402, AP2, AgentKit settling payments autonomously.",
              "Control: pre-settlement decisions, approval thresholds."]),
        ],
        table=dict(
            headers=["Channel", "Example", "Primary control"],
            rows=[
                ["Provider APIs", "OpenAI, Bedrock", "Caps + model choice"],
                ["Third-party tools", "Data vendors", "Allowlist + caps"],
                ["Payment rails", "x402, AP2", "Pre-settlement decision"],
            ],
        ),
        faqs=[
            ("Which channel is riskiest?",
             "Payment rails — settlement is fast and irreversible. But any channel can run away."),
            ("How does one firewall cover all three?",
             "It evaluates every transaction the same way: amount, merchant, category → decision."),
        ],
        related=[("Spend firewall", "/glossary/spend-firewall"), ("How spend control works", "/faq/how-ai-spend-control-works"), ("Agentic payments", "/glossary/agentic-payment")],
    ),
    dict(
        slug="what-are-agentic-payments",
        title="What Are Agentic Payments?",
        desc="Agentic payments: payments initiated by agents on machine rails. The protocols, the risks, and the control layer.",
        h1="What Are Agentic Payments?",
        lead="Agentic payments are payments an agent initiates — not a human. The protocols exist; the safety layer is what's missing.",
        sections=[
            ("The protocols",
             ["x402 — HTTP-based agent payments using the 402 status.",
              "AP2 — Google's agent payments protocol.",
              "AgentKit — onchain agent payments."]),
            ("The difference from human payments",
             ["No human reviews each payment — speed is the point.",
              "Fast settlement means fast damage if something goes wrong."]),
            ("The control layer",
             ["A pre-spend firewall sits between the agent and the rail: APPROVED, BLOCKED, or FLAGGED before settlement."]),
        ],
        faqs=[
            ("Are agentic payments mainstream?",
             "Emerging — the rails are live, adoption is growing. Controls are the constraint."),
            ("Who needs to care now?",
             "Anyone deploying agents with payment capability — which is any agent with a tool that spends."),
        ],
        related=[("Agentic payment", "/glossary/agentic-payment"), ("AP2", "/glossary/ap2"), ("Agent payment firewall", "/guides/agent-payment-firewall")],
    ),
]

GUIDES = [
    dict(
        slug="guide-to-mcp-spend-security",
        title="Guide to MCP Spend Security",
        desc="How to secure spend when your agents use MCP: vetting servers, gating paid tools, and the deterministic guard.",
        h1="MCP Spend Security Guide",
        lead="MCP gives agents tools — and tools can spend. This guide covers the security model for agent spend over MCP.",
        sections=[
            ("The risk model",
             ["Every MCP server is third-party code with tool access.",
              "A paid tool in a loop, or a malicious server, spends without review."]),
            ("Vetting servers",
             ["Review source, check authors, pin versions, and scope permissions — treat MCP servers like dependencies."]),
            ("The deterministic guard",
             ["The sipi.bot MCP tool evaluates every proposed purchase before it happens — rules, not prompts."]),
        ],
        table=dict(
            headers=["Layer", "Control"],
            rows=[
                ["Server vetting", "Source review + least privilege"],
                ["Paid tools", "Merchant allowlist + caps"],
                ["Decision", "Pre-spend guard tool"],
                ["Audit", "Queryable log"],
            ],
        ),
        faqs=[
            ("Can an MCP server spend money?",
             "If it exposes a paid tool or holds a credential, yes. Gate it."),
            ("Is the guard model-free?",
             "Yes — deterministic rules, nothing to inject."),
        ],
        related=[("MCP integration", "/integrations/mcp"), ("Red flags in MCP servers", "/redflags/red-flags-in-mcp-servers"), ("Best MCP spend tools", "/best/best-mcp-tools-for-ai-spend-control")],
    ),
    dict(
        slug="guide-to-agent-budgeting-by-use-case",
        title="Guide to Agent Budgeting by Use Case",
        desc="How to budget agents by what they do: coding, research, support, trading. Starting numbers and rules per use case.",
        h1="Agent Budgeting by Use Case",
        lead="The right budget depends on the job. Coding agents, research agents, and trading bots have very different spend shapes — and starting numbers.",
        sections=[
            ("Coding agents",
             ["Spend: tool calls, compute, occasional data. Budget: per-session or daily caps, velocity limits on loops."]),
            ("Research agents",
             ["Spend: search APIs, data vendors, inference. Budget: per-project ceilings, merchant allowlists."]),
            ("Support agents",
             ["Spend: inference at request volume. Budget: daily ceilings tied to ticket volume."]),
            ("Trading agents",
             ["Spend: data feeds, exchange APIs. Budget: hard caps + velocity limits, time-of-day rules."]),
        ],
        table=dict(
            headers=["Use case", "Spend shape", "First rule"],
            rows=[
                ["Coding", "Tool calls + compute", "Velocity limit"],
                ["Research", "Data + search", "Merchant allowlist"],
                ["Support", "Inference volume", "Daily ceiling"],
                ["Trading", "Feeds + APIs", "Hard cap + velocity"],
            ],
        ),
        faqs=[
            ("What's a starting number?",
             "Estimate legitimate daily spend × 1.5, then tune with audit-log data."),
            ("Can one policy cover all use cases?",
             "Yes — per-agent rules let each use case run its own policy."),
        ],
        related=[("Recommended limits", "/limits/recommended-limits-by-use-case"), ("Agent budget template", "/templates/agent-budget-template"), ("Budget sizing calculator", "/calculators/budget-sizing-calculator")],
    ),
]

SECTORS = [
    dict(
        slug="real-estate",
        title="AI Spend Control for Real Estate | sipi.bot",
        desc="Real-estate AI agents: lead-gen, listing, and valuation bots that spend on data and ads. Cap it per office or campaign.",
        h1="Spend Control for Real Estate AI Agents",
        lead="Real-estate agents run on lead-gen, listing, and valuation bots — each pulling paid data and ad spend. Per-campaign budgets keep the commissions intact.",
        sections=[
            ("Where real-estate agents spend",
             ["Lead-gen bots buying leads and contact data per campaign.",
              "Listing agents generating photos, descriptions, and translations.",
              "Valuation bots pulling comps from data providers.",
              "Support bots answering inquiries at volume."]),
            ("The failure modes",
             ["An ad/lead campaign loop multiplies spend overnight.",
              "Unknown data vendors bypass procurement — allowlist them.",
              "Seasonal volume spikes hit overage tiers."]),
            ("Which rules to start with",
             ["Per-campaign daily ceiling.",
              "Merchant allowlist for approved data vendors.",
              "Category rule: leads vs listings vs valuation."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in real estate"],
            rows=[
                ["Per-campaign ceiling", "Each campaign has its own budget"],
                ["Merchant allowlist", "Unvetted data vendors blocked"],
                ["Category rule", "Leads vs listings vs valuation"],
            ],
        ),
        faqs=[
            ("Can I budget per office?",
             "Yes — per-agent rules let each office run its own ceiling."),
            ("Does it slow lead-gen?",
             "No — ~5 ms per check."),
        ],
        related=[("Marketing sector", "/sectors/marketing"), ("Email agents", "/use-cases/email-agents"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="manufacturing",
        title="AI Spend Control for Manufacturing | sipi.bot",
        desc="Manufacturing AI agents: predictive maintenance, quality control, and supply-chain bots. Cap data and compute spend across the plant.",
        h1="Spend Control for Manufacturing AI Agents",
        lead="Manufacturing runs agents for maintenance prediction, quality control, and supply chain — each pulling telemetry and inference at plant scale.",
        sections=[
            ("Where manufacturing agents spend",
             ["Predictive-maintenance agents pulling telemetry and running inference.",
              "Quality-control vision agents per inspection line.",
              "Supply-chain agents querying carrier and inventory APIs.",
              "Documentation and compliance bots at volume."]),
            ("The failure modes",
             ["A maintenance loop re-scoring the fleet multiplies compute spend.",
              "Unknown sensor-data vendors bypass procurement.",
              "Overnight plant runs without review."]),
            ("Which rules to start with",
             ["Per-line or per-plant daily ceiling.",
              "Velocity limit on scoring loops.",
              "Time-of-day rule for overnight runs."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in manufacturing"],
            rows=[
                ["Per-plant ceiling", "Fleet-wide budget in one number"],
                ["Velocity limit", "Scoring loops die fast"],
                ["Time-of-day rule", "Overnight runs need review"],
            ],
        ),
        faqs=[
            ("Can I budget per production line?",
             "Yes — per-agent rules per line."),
            ("Does the firewall add latency to QC?",
             "No — ~5 ms, and only spend actions trigger it."),
        ],
        related=[("Data pipelines", "/for/data-pipelines"), ("DevOps automation", "/for/devops-automation"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
]

USE_CASES = [
    dict(
        slug="customer-onboarding-agents",
        title="Customer Onboarding Agent Spend Control | sipi.bot",
        desc="Onboarding agents verify, provision, and welcome customers — each step hits paid APIs. Cap the per-onboarding spend.",
        h1="Spend Control for Customer Onboarding Agents",
        lead="Onboarding agents run verification, provisioning, and welcome flows — each with paid API calls. At signup volume, per-onboarding costs compound.",
        sections=[
            ("Where onboarding agents spend",
             ["Identity verification APIs per new customer.",
              "Provisioning tool calls per account.",
              "LLM inference for welcome and triage flows.",
              "Email and notification APIs per touch."]),
            ("The failure modes",
             ["A verification retry loop multiplies per-check charges.",
              "A provisioning bug loops against paid tools.",
              "Signup spikes (launch, campaign) hit overage tiers."]),
            ("Which rules to start with",
             ["Per-onboarding cost cap.",
              "Velocity limit on verification retries.",
              "Merchant allowlist for approved verification vendors."]),
        ],
        table=dict(
            headers=["Onboarding spend", "Control"],
            rows=[
                ["Verification APIs", "Per-check cap + velocity"],
                ["Provisioning", "Per-agent ceiling"],
                ["Inference", "Category budget"],
                ["Email APIs", "Daily ceiling"],
            ],
        ),
        faqs=[
            ("Can I cap cost per new customer?",
             "Yes — per-agent rules tied to the onboarding flow."),
            ("Does it slow signups?",
             "No — ~5 ms per check."),
        ],
        related=[("Customer support bots", "/use-cases/customer-support-bots"), ("Email agents", "/use-cases/email-agents"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="hr-automation-agents",
        title="HR Automation Agent Spend Control | sipi.bot",
        desc="HR agents handle onboarding, benefits, and employee support — each pulling paid tools. Cap the per-employee spend.",
        h1="Spend Control for HR Automation Agents",
        lead="HR bots answer benefits questions, route tickets, and process records — against paid tools at headcount scale.",
        sections=[
            ("Where HR agents spend",
             ["Benefits and policy lookup tools per query.",
              "Document processing (offer letters, records) per employee.",
              "LLM inference for employee support at volume.",
              "Background-check and verification APIs."]),
            ("The failure modes",
             ["A support bot in a loop multiplies inference spend.",
              "A records-processing job re-running overnight.",
              "Unknown verification vendors bypass procurement."]),
            ("Which rules to start with",
             ["Per-employee or per-flow cost cap.",
              "Daily ceiling on support inference.",
              "Merchant allowlist for verification vendors."]),
        ],
        table=dict(
            headers=["HR spend", "Control"],
            rows=[
                ["Support inference", "Daily ceiling"],
                ["Document processing", "Per-flow cap"],
                ["Verification APIs", "Merchant allowlist"],
                ["Lookup tools", "Category budget"],
            ],
        ),
        faqs=[
            ("Can I budget per department?",
             "Yes — per-agent rules per department."),
            ("What about seasonal hiring spikes?",
             "Set ceilings for peak season and route the rest through FLAGGED approval."),
        ],
        related=[("Backoffice automation", "/use-cases/backoffice-automation"), ("Customer support bots", "/use-cases/customer-support-bots"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
]

GLOSSARY = [
    dict(
        slug="ai-agent-economy",
        term="AI agent economy",
        title="What is the AI Agent Economy? | sipi.bot Glossary",
        desc="The AI agent economy: autonomous agents buying compute, data, and services on machine rails. Definition with the control implications.",
        h1="What is the AI Agent Economy?",
        lead="The AI agent economy is the emerging marketplace where autonomous agents — not humans — purchase compute, data, and services on machine payment rails.",
        sections=[
            ("How it works",
             ["Agents discover and pay for services via protocols like x402 and AP2.",
              "Purchases are small, frequent, and autonomous."]),
            ("Why it matters",
             ["It's the fastest-growing payment surface in software — and the least controlled.",
              "Rails settle fast; nothing screens transactions before settlement."]),
            ("The control layer",
             ["A pre-spend firewall decides APPROVED, BLOCKED, or FLAGGED before the rail settles."]),
        ],
        faqs=[
            ("Is the agent economy real?",
             "The rails are live and products ship on them. The control layer is the immature part."),
            ("What does it mean for budgets?",
             "Agent spend becomes a line item — and needs the same controls as any other spend."),
        ],
        related=[("Agentic payment", "/glossary/agentic-payment"), ("The agent economy explained", "/learn/the-agent-economy-explained"), ("x402", "/glossary/x402")],
    ),
    dict(
        slug="agentic-ai",
        term="Agentic AI",
        title="What is Agentic AI? | sipi.bot Glossary",
        desc="Agentic AI: systems that act autonomously toward goals — including spending money. Definition with the governance implications.",
        h1="What is Agentic AI?",
        lead="Agentic AI refers to systems that pursue goals autonomously — planning, using tools, and taking actions without step-by-step human direction.",
        sections=[
            ("What makes AI agentic",
             ["Goal-directed behavior instead of single-turn responses.",
              "Tool use, planning, and multi-step execution.",
              "Autonomy — the system decides how to proceed."]),
            ("Why autonomy changes the risk model",
             ["Autonomous action includes autonomous spending.",
              "A goal-directed agent in a loop keeps acting — and billing."]),
            ("The governance implication",
             ["Agentic systems need external constraints: deterministic rules on the money path, not just prompts."]),
        ],
        faqs=[
            ("Is all agentic AI a spend risk?",
             "Only agents with spend capability — but tool access makes that most of them."),
            ("How do you govern agentic systems?",
             "Same as any system with side effects: external gates, budgets, and audit."),
        ],
        related=[("Spend firewall", "/glossary/spend-firewall"), ("Subagent", "/glossary/subagent"), ("How autonomous agents spend", "/learn/how-autonomous-agents-spend-money")],
    ),
]

SCENARIOS = [
    dict(
        slug="silent-tier-escalation-scenario",
        title="Scenario: An Agent Silently Escalates to a Pricier Tier",
        desc="Eval Gym scenario: a model default changes and inference spend doubles without a code change. What per-agent caps do.",
        h1="Scenario: Silent Tier Escalation",
        lead="A provider changes its default model, or your agent starts selecting a pricier tier. No code changed; the bill doubles. Nobody notices until the invoice.",
        sections=[
            ("What happens without a firewall",
             ["The per-token rate rises silently. Volume stays the same; cost doubles.",
              "The bill shows the damage; the code shows nothing."]),
            ("What happens with sipi.bot",
             ["The per-agent daily ceiling caps total spend regardless of tier.",
              "When spend approaches the ceiling, further calls are BLOCKED or FLAGGED — the escalation becomes visible, not silent."]),
            ("The rule set",
             ["Per-agent daily ceiling + category rule for inference."]),
        ],
        code=dict(
            title="The decision",
            lang="json",
            body='{\n  "decision": "FLAGGED",\n  "reason": "Daily inference ceiling at 90%",\n  "rule_id": "rul_daily_04",\n  "transaction_id": "txn_31c9d8"\n}',
            caption="Tier drift surfaces instead of compounding.",
        ),
        faqs=[
            ("Can the firewall detect tier changes?",
             "It doesn't need to — the dollar ceiling catches the effect regardless of cause."),
            ("What should I do on a flag?",
             "Review the model selection, pin the tier, and re-baseline the ceiling."),
        ],
        related=[("Overage tier", "/glossary/overage-tier"), ("Cost per 1M tokens", "/benchmarks/cost-per-1m-tokens-2026"), ("Model drift", "/benchmarks/llm-api-pricing-comparison-2026")],
    ),
    dict(
        slug="cross-agent-budget-race-scenario",
        title="Scenario: Two Agents Race for the Same Budget",
        desc="Eval Gym scenario: agents competing for a shared budget cause thrash. How shared ceilings and priorities prevent the race.",
        h1="Scenario: Cross-Agent Budget Race",
        lead="Two agents share a daily budget. One spends early and fast; the other starves — or both loop retrying. The shared ceiling needs a design, not just a number.",
        sections=[
            ("What happens",
             ["Agent A consumes the shared ceiling by lunch; Agent B's legitimate work gets BLOCKED all afternoon.",
              "Teams respond by raising the ceiling — which defeats the budget."]),
            ("What happens with sipi.bot",
             ["Per-agent ceilings on top of the shared ceiling: each agent gets its own slice AND the fleet has a cap.",
              "Priority handling: critical agents get higher ceilings; the shared cap stays intact."]),
            ("The rule set",
             ["Shared fleet ceiling + per-agent ceilings + approval threshold for over-budget requests."]),
        ],
        code=dict(
            title="The design",
            lang="text",
            body="Fleet ceiling: $1,000/day\n  Agent A: $600/day (critical path)\n  Agent B: $400/day (batch)\nOver-budget requests: FLAGGED for approval",
            caption="Slices + a cap beats a race.",
        ),
        faqs=[
            ("Is a shared ceiling bad?",
             "No — it's necessary. The fix is per-agent slices inside it."),
            ("What if a critical agent needs more mid-day?",
             "The approval queue handles it: FLAG over-budget requests, approve the ones that matter."),
        ],
        related=[("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Multi-agent compounding", "/scenarios/multi-agent-compounding-scenario"), ("Daily spend ceiling", "/glossary/daily-spend-ceiling")],
    ),
]

# --- hub metadata (all target sections have hubs; patched by generator) ----
