"""Round 21 pSEO data — sipi.bot (2026-08-08).

Content rules (from CLAUDE.md + product truth):
- Honest copy: sipi.bot does NOT win every dimension. Comparison pages have
  "where <tool> wins" sections.
- No fabricated stats, testimonials, urgency, or tiers. Verifiable facts only:
  $99/mo Team / $499/mo Business, unlimited evals, MIT core, ~5 ms decisions,
  3 decisions (APPROVED/BLOCKED/FLAGGED), 6 rule types, HTTP+MCP+CLI,
  x402/AP2/AgentKit compatible, queryable audit log, no custody, 53/53 evals.
- ERROR PAGES describe the REAL API contract (verified in spendfirewall/api.py,
  2026-08-08): error codes, HTTP statuses, and response shapes are accurate.

Error codes verified in api.py:
  HTTP-level: invalid_api_key(401), api_key_required(401), forbidden(403),
  not_found(404), method_not_allowed(405), body_too_large(413),
  invalid_content_length(400), rate_limited(429, retry_after 60/3600),
  internal 500s.
  Transaction validation: amount_required, invalid_amount, invalid_<field>.
  Rule validation: invalid_rule_type, invalid_rule_action, invalid_rule_params,
  invalid_rule_priority, invalid_rule_label.
Decision shape: {"decision","reason","rule_id","transaction_id","amount","merchant"}.
"""

ERRORS = [
    dict(
        slug="invalid-api-key",
        code_name="invalid_api_key",
        status="401 Unauthorized",
        title="sipi.bot API Error: invalid_api_key (401)",
        desc="What invalid_api_key means on the sipi.bot API, why it happens, and how to fix it. Real error reference for the spend firewall API.",
        h1="Error: invalid_api_key",
        lead="The Authorization header was supplied but couldn't be resolved to a valid API key. sipi.bot never silently downgrades an invalid paid key to anonymous behavior — it rejects the request.",
        sections=[
            ("What it means",
             ["The request carried an Authorization header, but the token is not a valid API key: wrong format, revoked, or unresolved.",
              "This is a hard 401 — no evaluation happens, no decision is returned, nothing is logged as spend."]),
            ("Common causes",
             ["Missing \"Bearer \" prefix, or an empty token after it.",
              "A typo'd or truncated key.",
              "A revoked or expired key (hosted plans).",
              "Using a dashboard key where a transaction key is expected."]),
            ("How to fix",
             ["Check the key is complete and copied exactly.",
              "Issue a fresh key from the dashboard (or via the agents API on self-host).",
              "If you self-host, confirm the key store (SQLite) is mounted and writable."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "401"],
                ["Error code", "invalid_api_key"],
                ["Response shape", '{"error": "invalid_api_key"}'],
                ["Evaluation", "Not attempted"],
            ],
        ),
        code=dict(
            title="Example request & response",
            lang="bash",
            body='curl -X POST https://sipi.bot/v1/transactions/evaluate \\\n  -H "Content-Type: application/json" \\\n  -H "Authorization: Bearer bad-key" \\\n  -d \'{"amount": 100, "merchant": "demo"}\'\n\nHTTP/1.1 401\n{"error": "invalid_api_key"}',
            caption="Fix the key and retry. A valid key returns APPROVED, BLOCKED, or FLAGGED.",
        ),
        faqs=[
            ("Is auth required to evaluate transactions?",
             "No — the evaluate endpoint works anonymously in free/self-host mode. If you send an Authorization header, it must resolve to a valid key; invalid keys are rejected, never downgraded."),
            ("What status does a missing key return?",
             "On protected routes (rules, approvals, dashboard), a missing key returns api_key_required. The evaluate endpoint treats a missing header as anonymous."),
            ("Where do I get a valid key?",
             "Hosted plans issue keys via the checkout flow (sk_live_ keys are minted server-side). Self-hosted deployments create keys through the agents API with the admin token."),
        ],
        related=[("API key required", "/errors/api-key-required"), ("Rate limited", "/errors/rate-limited"), ("Self-host guide", "/self-hosted/")],
    ),
    dict(
        slug="api-key-required",
        code_name="api_key_required",
        status="401 Unauthorized",
        title="sipi.bot API Error: api_key_required (401)",
        desc="What api_key_required means on the sipi.bot API, which routes need keys, and how to fix it.",
        h1="Error: api_key_required",
        lead="The request hit a route that requires authentication, and no valid Authorization header was sent.",
        sections=[
            ("What it means",
             ["Control-plane routes (rules, agents, approvals, dashboard data) require a valid key or admin token.",
              "Unlike the evaluate endpoint, these routes never run anonymously."]),
            ("Common causes",
             ["Calling /api/rules or /api/approvals without an Authorization header.",
              "A client that only learned the evaluate endpoint pattern and reused it unchanged.",
              "An admin-only route called with a regular agent key."]),
            ("How to fix",
             ["Attach a valid key: Authorization: Bearer <key>.",
              "Use the admin token (self-host, from the .admin_token file or env) for operator routes."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "401"],
                ["Error code", "api_key_required"],
                ["Response shape", '{"error": "api_key_required"}'],
                ["Affected routes", "/api/rules, /api/agents, /api/approvals, dashboard"],
            ],
        ),
        code=dict(
            title="Example",
            lang="bash",
            body='curl -X GET https://sipi.bot/api/rules\n\nHTTP/1.1 401\n{"error": "api_key_required"}\n\n# Fix:\ncurl -X GET https://sipi.bot/api/rules -H "Authorization: Bearer <valid-key>"',
            caption="Add the header; the route returns your rules.",
        ),
        faqs=[
            ("Which routes require a key?",
             "Control-plane routes: rules management, agent keys, approval resolution, and dashboard endpoints. Evaluate stays anonymous-capable."),
            ("What's the difference from invalid_api_key?",
             "api_key_required means no key was sent to a protected route. invalid_api_key means a key was sent but is not valid."),
            ("Can I self-host without keys?",
             "You still need the admin token for operator routes; the evaluate endpoint can run anonymously."),
        ],
        related=[("Invalid API key", "/errors/invalid-api-key"), ("Forbidden", "/errors/forbidden"), ("Rules API", "/errors/rule-error")],
    ),
    dict(
        slug="forbidden",
        code_name="forbidden",
        status="403 Forbidden",
        title="sipi.bot API Error: forbidden (403)",
        desc="What forbidden means on the sipi.bot API, when it fires, and how to fix it.",
        h1="Error: forbidden",
        lead="The request was authenticated but the caller lacks permission for the operation.",
        sections=[
            ("What it means",
             ["403 fires when a valid credential exists but isn't allowed to do what was asked — e.g. a non-admin key hitting an admin-only route, or a cross-tenant access attempt."]),
            ("Common causes",
             ["Agent-scoped keys calling admin endpoints.",
              "Resolving or deleting rules that belong to another agent.",
              "Badge or dashboard routes hit from an untrusted origin."]),
            ("How to fix",
             ["Use a key with the right scope (admin token for admin routes).",
              "Confirm the rule or approval belongs to the calling agent."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "403"],
                ["Error code", "forbidden"],
                ["Response shape", '{"error": "forbidden"}'],
                ["Auth state", "Valid credential, wrong scope"],
            ],
        ),
        code=dict(
            title="Example",
            lang="bash",
            body='curl -X DELETE https://sipi.bot/api/rules/rul_abc -H "Authorization: Bearer <agent-key-of-another-agent>"\n\nHTTP/1.1 403\n{"error": "forbidden"}',
            caption="Scope the key correctly or use the admin token.",
        ),
        faqs=[
            ("Is forbidden the same as invalid_api_key?",
             "No. invalid_api_key means the credential is bad. forbidden means the credential is valid but lacks permission."),
            ("Can I get 403 on evaluate?",
             "Evaluate is anonymous-capable and doesn't return 403 under normal use. 403s are for control-plane permission problems."),
        ],
        related=[("API key required", "/errors/api-key-required"), ("Invalid API key", "/errors/invalid-api-key"), ("Not found", "/errors/not-found")],
    ),
    dict(
        slug="not-found",
        code_name="not_found",
        status="404 Not Found",
        title="sipi.bot API Error: not_found (404)",
        desc="What not_found means on the sipi.bot API, when it fires, and how to fix it.",
        h1="Error: not_found",
        lead="The requested route or resource doesn't exist.",
        sections=[
            ("What it means",
             ["404 fires for unknown paths (e.g. /v1/transactions/evluate) or unknown resource IDs."]),
            ("Common causes",
             ["A typo in the endpoint path.",
              "Referencing a rule, agent, or approval ID that was deleted or never existed.",
              "Calling a hosted-only route on a self-host build (or vice versa)."]),
            ("How to fix",
             ["Check the path against the API reference.",
              "Verify the ID exists (list rules first, then act on a real ID)."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "404"],
                ["Error code", "not_found"],
                ["Response shape", '{"error": "not_found"}'],
            ],
        ),
        code=dict(
            title="Example",
            lang="bash",
            body='curl -X POST https://sipi.bot/v1/transactions/evluate \\\n  -H "Content-Type: application/json" -d \'{}\'\n\nHTTP/1.1 404\n{"error": "not_found"}',
            caption="Correct path: /v1/transactions/evaluate.",
        ),
        faqs=[
            ("Does a typo in the path return 404?",
             "Yes — unknown paths return not_found. The evaluate path is exactly /v1/transactions/evaluate."),
            ("What if a rule ID is missing?",
             "Acting on a deleted rule ID returns not_found. List rules first to get current IDs."),
        ],
        related=[("Method not allowed", "/errors/method-not-allowed"), ("Transaction error", "/errors/transaction-error"), ("Rule error", "/errors/rule-error")],
    ),
    dict(
        slug="method-not-allowed",
        code_name="method_not_allowed",
        status="405 Method Not Allowed",
        title="sipi.bot API Error: method_not_allowed (405)",
        desc="What method_not_allowed means on the sipi.bot API and how to fix it.",
        h1="Error: method_not_allowed",
        lead="The route exists but doesn't accept the HTTP method you used.",
        sections=[
            ("What it means",
             ["Each route accepts specific methods (POST for evaluate and rules, GET for listing, DELETE for removal). Using the wrong one returns 405."]),
            ("Common causes",
             ["GET on a POST-only route.",
              "PUT where the API only supports POST or PATCH."]),
            ("How to fix",
             ["Use the documented method for the route.",
              "Evaluate: POST. Rules: POST (create), GET (list), DELETE (remove)."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "405"],
                ["Error code", "method_not_allowed"],
                ["Response shape", '{"ok": false, "error": "method_not_allowed"}'],
            ],
        ),
        faqs=[
            ("Can I update a rule with PUT?",
             "No — use DELETE + POST (remove and recreate) or the documented endpoints. PUT isn't supported on the rules routes."),
        ],
        related=[("Not found", "/errors/not-found"), ("Rule error", "/errors/rule-error")],
    ),
    dict(
        slug="body-too-large",
        code_name="body_too_large",
        status="413 Payload Too Large",
        title="sipi.bot API Error: body_too_large (413)",
        desc="What body_too_large means on the sipi.bot API and how to fix it.",
        h1="Error: body_too_large",
        lead="The request body exceeded the server's size limit.",
        sections=[
            ("What it means",
             ["The API enforces a maximum request body size. Bodies over the limit are rejected before parsing with 413."]),
            ("Common causes",
             ["Accidentally sending a huge payload (e.g. a full document instead of a transaction).",
              "A client retrying a corrupted buffer."]),
            ("How to fix",
             ["Send only the transaction fields the API expects: amount, currency, merchant, category, timestamp.",
              "Check for streaming/client-side buffering bugs that inflate the body."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "413"],
                ["Error code", "body_too_large"],
                ["Response shape", '{"error": "body_too_large"}'],
            ],
        ),
        faqs=[
            ("What's the size limit?",
             "The server enforces a fixed cap on request bodies; keep payloads small and structured."),
            ("Can body_too_large happen on evaluate?",
             "Only if the client sends an oversized body — a transaction object is tiny, so this usually indicates a client bug."),
        ],
        related=[("Transaction error", "/errors/transaction-error"), ("Invalid API key", "/errors/invalid-api-key")],
    ),
    dict(
        slug="rate-limited",
        code_name="rate_limited",
        status="429 Too Many Requests",
        title="sipi.bot API Error: rate_limited (429)",
        desc="What rate_limited means on the sipi.bot API, when retry_after matters, and how to fix it.",
        h1="Error: rate_limited",
        lead="Too many requests in the rate-limit window. The response includes retry_after — honor it.",
        sections=[
            ("What it means",
             ["Rate limits protect the service. When exceeded, the API returns 429 with an error and a retry_after value in seconds."]),
            ("Common causes",
             ["An agent in a tight retry loop hammering evaluate — exactly the pattern a velocity rule would stop.",
              "A misconfigured client that re-sends immediately without backoff."]),
            ("How to fix",
             ["Read retry_after and wait that long before retrying.",
              "Add exponential backoff to your client.",
              "Ironically, the fix for agent-side loops is a sipi.bot velocity rule — but the API's own rate limit applies too."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "429"],
                ["Error code", "rate_limited"],
                ["Response shape", '{"error": "rate_limited", "retry_after": 60}'],
                ["retry_after", "Seconds to wait (varies by route)"],
            ],
        ),
        code=dict(
            title="Example",
            lang="bash",
            body='curl -X POST https://sipi.bot/v1/transactions/evaluate \\\n  -H "Content-Type: application/json" -d \'{"amount": 10, "merchant": "demo"}\'  # ...burst...\n\nHTTP/1.1 429\n{"error": "rate_limited", "retry_after": 60}',
            caption="Wait retry_after seconds, or add backoff.",
        ),
        faqs=[
            ("What is retry_after?",
             "The number of seconds to wait before retrying. Different routes use different windows (e.g. 60s and 3600s)."),
            ("Does 429 count as spend?",
             "No — a rate-limited request is rejected before evaluation. Nothing is charged."),
            ("How do I avoid tripping it?",
             "Backoff + batching. If your agent retries aggressively, that's also what a sipi.bot velocity rule is for."),
        ],
        related=[("Velocity limit", "/glossary/velocity-limit"), ("Runaway loops", "/blog/runaway-loops-anatomy"), ("Internal error", "/errors/internal-error")],
    ),
    dict(
        slug="transaction-error",
        code_name="transaction_error",
        status="400 Bad Request",
        title="sipi.bot API Error: transaction_error (400)",
        desc="Transaction validation errors on the sipi.bot API: amount_required, invalid_amount, invalid_<field>. How to fix each.",
        h1="Error: transaction_error",
        lead="The transaction payload failed validation. The API returns a specific error name — amount_required, invalid_amount, or invalid_<field> — telling you exactly which field is wrong.",
        sections=[
            ("What it means",
             ["Before any rule evaluation, the transaction is validated. Validation failures return 400 with the precise reason."]),
            ("The validation error names",
             ["amount_required — the amount field is missing.",
              "invalid_amount — amount isn't a valid positive finite number within limits.",
              "invalid_<field> — another field is invalid (currency, merchant, category, timestamp, ...)."]),
            ("How to fix",
             ["Always send amount as a number in major units (e.g. 12400 for $12,400).",
              "Keep currency as a 3-letter code, merchant as a string, category from your configured set.",
              "Validate client-side before calling to avoid 400s in production."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "400"],
                ["Error code", "transaction_error (amount_required / invalid_amount / invalid_<field>)"],
                ["Response shape", '{"error": "amount_required"}'],
                ["Evaluation", "Not attempted"],
            ],
        ),
        code=dict(
            title="Minimal valid payload",
            lang="json",
            body='{\n  "amount": 6200,\n  "currency": "USD",\n  "merchant": "unknown-gpu.ru",\n  "category": "compute"\n}\n\n# Invalid:\n{"merchant": "no-amount"}        -> {"error": "amount_required"}\n{"amount": -5, "merchant": "x"}   -> {"error": "invalid_amount"}',
            caption="Send amount as a positive finite number.",
        ),
        faqs=[
            ("What exactly is invalid_amount?",
             "Amount must be a finite number within the server's accepted range — negative, NaN, or absurdly large values return invalid_amount."),
            ("Can I send string amounts?",
             "No — send numbers. Strings like \"100\" fail validation."),
            ("What fields are optional?",
             "amount is required; others (currency, merchant, category, timestamp) follow the documented schema — invalid values get invalid_<field>."),
        ],
        related=[("Rule error", "/errors/rule-error"), ("Bad request docs", "/"), ("Playground", "/playground/")],
    ),
    dict(
        slug="rule-error",
        code_name="rule_error",
        status="400 Bad Request",
        title="sipi.bot API Error: rule_error (400)",
        desc="Rule validation errors on the sipi.bot API: invalid_rule_type, invalid_rule_action, invalid_rule_params, invalid_rule_priority, invalid_rule_label.",
        h1="Error: rule_error",
        lead="The rule payload failed validation. The API names the exact problem: invalid_rule_type, invalid_rule_action, invalid_rule_params, invalid_rule_priority, or invalid_rule_label.",
        sections=[
            ("What it means",
             ["Rules are validated when created (and when updated). A malformed rule is rejected before it can affect any transaction."]),
            ("The validation error names",
             ["invalid_rule_type — unknown rule type (e.g. not per_transaction_cap, daily_ceiling, velocity_limit, merchant_allowlist, category_rule, time_of_day).",
              "invalid_rule_action — action must be one of the supported decisions (approve / block / flag).",
              "invalid_rule_params — parameters for the rule type are missing or out of range.",
              "invalid_rule_priority — priority isn't a valid finite number in the accepted range.",
              "invalid_rule_label — label is malformed or too long."]),
            ("How to fix",
             ["Use one of the documented rule types and actions.",
              "Check params against the type: a cap needs max; an allowlist needs the merchant list; a velocity rule needs count and window.",
              "Keep labels short and plain."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "400"],
                ["Error code", "rule_error (invalid_rule_type / invalid_rule_action / invalid_rule_params / invalid_rule_priority / invalid_rule_label)"],
                ["Response shape", '{"error": "invalid_rule_params"}'],
                ["Rule stored", "No"],
            ],
        ),
        code=dict(
            title="Valid rule example",
            lang="json",
            body='{\n  "type": "per_transaction_cap",\n  "action": "block",\n  "params": {"max": 500, "currency": "USD"},\n  "priority": 1,\n  "label": "Block any single transaction over $500"\n}',
            caption="Match type, action, and params or you get a named rule_error.",
        ),
        faqs=[
            ("Where can I see the supported rule types?",
             "The six enforced rule types are per-transaction cap, daily/period total, velocity limit, merchant allowlist, category rule, and time-of-day rule."),
            ("What does invalid_rule_params cover?",
             "Missing or out-of-range parameters for the rule type — e.g. a cap without max, or a velocity rule with a negative window."),
            ("Does a bad rule affect existing rules?",
             "No. Rejected rules are never stored; your existing rules keep enforcing."),
        ],
        related=[("Transaction error", "/errors/transaction-error"), ("Rules engine", "/"), ("Agent spend policy", "/templates/agent-spend-policy-template")],
    ),
    dict(
        slug="internal-error",
        code_name="internal_error",
        status="500 Internal Server Error",
        title="sipi.bot API Error: internal_error (500)",
        desc="What internal 500 errors mean on the sipi.bot API and what to do when they happen.",
        h1="Error: internal_error",
        lead="Something failed inside the service. 500s are rare; when they happen, they're the API saying 'try again, or check the status page'.",
        sections=[
            ("What it means",
             ["A 500 means the request was valid but the service hit an unexpected error handling it."]),
            ("Common causes",
             ["A transient backend issue (database, volume, network).",
              "A self-host deployment misconfiguration (missing volume, read-only store)."]),
            ("How to fix",
             ["Retry with backoff — many 500s are transient.",
              "Check the status page and changelog.",
              "Self-host: check logs, volume mount, and that the SQLite store is writable."]),
        ],
        table=dict(
            headers=["Field", "Value"],
            rows=[
                ["HTTP status", "500"],
                ["Error code", "internal_error (body carries the message)"],
                ["Response shape", '{"error": "<message>"}'],
            ],
        ),
        faqs=[
            ("Is my transaction evaluated on a 500?",
             "The response is an error; treat the decision as unknown and retry. No money moved on our side — the firewall never settles funds."),
            ("Where do I check service health?",
             "The /health endpoint and the public status page."),
        ],
        related=[("Status page", "/status/"), ("Rate limited", "/errors/rate-limited"), ("Changelog", "/changelog/")],
    ),
]

INTEGRATIONS = [
    dict(
        slug="semantic-kernel",
        title="Semantic Kernel Agent Budgets — sipi.bot Integration",
        desc="Add deterministic spend control to Microsoft Semantic Kernel agents. One tool call before any purchase: APPROVED, BLOCKED, or FLAGGED.",
        h1="Spend Control for Semantic Kernel",
        lead="Semantic Kernel is Microsoft's agent framework for .NET, Python, and Java — powering enterprise automations with plugins and planners. Enterprise agents spend on paid plugins, and nobody budgets the plugins.",
        sections=[
            ("Why Semantic Kernel agents overspend",
             ["Plugins can call paid endpoints; a planner chaining plugins multiplies calls.",
              "Enterprise deployments run many agents on shared credentials — one runaway loop hits the shared bill.",
              "There's no built-in budget concept in the kernel's plugin pipeline."]),
            ("How it works",
             ["Add sipi.bot as a plugin (or call the HTTP API from a custom plugin). Before any spend, the kernel asks sipi.bot: APPROVED, BLOCKED, or FLAGGED — deterministic, ~5 ms."]),
            ("Rules that fit enterprise workloads",
             ["Shared daily ceiling across the agent fleet.",
              "Merchant allowlist for approved paid plugins and vendors.",
              "Approval threshold so large purchases route to a human."]),
        ],
        code=dict(
            title="Plugin call",
            lang="csharp",
            body='// Semantic Kernel plugin (C#)\nvar result = await client.PostAsJsonAsync(\n    "https://sipi.bot/v1/transactions/evaluate",\n    new { amount = 800, merchant = "paid-plugin.com", category = "api" });\nvar decision = (await result.Content.ReadFromJsonAsync<Decision>()).decision;\n// APPROVED | BLOCKED | FLAGGED',
            caption="Gate any plugin that spends.",
        ),
        faqs=[
            ("Does sipi.bot support .NET?",
             "Yes — sipi.bot is a plain HTTP API and MCP tool, so .NET, Python, and Java Semantic Kernel apps all call it directly."),
            ("Can it cap a whole enterprise fleet?",
             "Yes — per-agent rules plus a shared daily ceiling govern the fleet; the audit log attributes every decision."),
            ("Does it add latency to planners?",
             "About 5 ms per check, no model in the path."),
        ],
        related=[("Pydantic AI", "/integrations/pydantic-ai"), ("Enterprise", "/use-cases/enterprise"), ("Multi-agent budgets", "/use-cases/multi-agent-budgets")],
    ),
    dict(
        slug="google-adk",
        title="Google ADK Agent Budgets — sipi.bot Integration",
        desc="Add spend control to Google Agent Development Kit (ADK) agents. A guard tool that returns APPROVED, BLOCKED, or FLAGGED before money moves.",
        h1="Spend Control for Google ADK",
        lead="Google's Agent Development Kit builds multi-agent systems on Gemini. Multi-agent means multi-spend — subagents fan out, tools get called, and the bill follows.",
        sections=[
            ("Why ADK agents overspend",
             ["Subagent fan-out multiplies inference and tool calls.",
              "Tools can trigger paid services (Vertex APIs, data, payments) without a budget check.",
              "Retry and reflection loops compound spend."]),
            ("How it works",
             ["Attach sipi.bot as a tool in your ADK agent. Before spending, the agent calls the guard and gets a deterministic decision."]),
            ("Rules that fit ADK workloads",
             ["Per-agent daily ceiling for the whole fleet.",
              "Category rule: inference vs data vs payments.",
              "Velocity limit to stop retry loops."]),
        ],
        code=dict(
            title="Guard tool",
            lang="python",
            body='from sipi_guard import sipi_guard\nfrom google.adk.agents import Agent\n\nagent = Agent(name="spending_agent", tools=[sipi_guard])\n# decision = sipi_guard(amount=300, merchant="vertex-api", category="inference")',
            caption="One tool, deterministic policy.",
        ),
        faqs=[
            ("Does this work with Gemini pricing controls?",
             "Gemini/Vertex controls cap that provider's inference. sipi.bot governs the agent's purchases across every merchant — run both."),
            ("Is there a Python SDK?",
             "Yes — HTTP API, CLI, and MCP tool, plus thin client wrappers for common frameworks."),
            ("What about subagents?",
             "Shared ceilings and velocity limits apply fleet-wide, so a fan-out can't compound one mistake."),
        ],
        related=[("Google Gemini", "/integrations/google-gemini"), ("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Vertex cost", "/cost-of/aws-bedrock-api-cost")],
    ),
    dict(
        slug="aws-bedrock-agents",
        title="AWS Bedrock Agents Cost Control — sipi.bot Integration",
        desc="Control what Bedrock Agents buy. sipi.bot gates the agent's purchases across merchants — compute, data, and APIs — before they settle.",
        h1="Spend Control for AWS Bedrock Agents",
        lead="Bedrock Agents build on AWS's LLM platform — and AWS bills you for the inference. But the agent's purchases beyond AWS (data vendors, external APIs, compute) are spend Bedrock never sees.",
        sections=[
            ("Why Bedrock Agents overspend",
             ["Inference volume: agent loops and tool calls multiply token spend on your AWS bill.",
              "Agents can call external paid tools (data, compute, APIs) outside Bedrock's pricing entirely.",
              "Cost explorer shows the bill after the fact — nothing gates a transaction in real time."]),
            ("How it works",
             ["Call sipi.bot from your agent's action group before any spend. The decision — APPROVED, BLOCKED, or FLAGGED — is deterministic and logged."]),
            ("Rules that fit Bedrock workloads",
             ["Per-agent daily ceiling for inference.",
              "Merchant allowlist for approved external vendors.",
              "Category rule: inference, data, compute budgets stay separate."]),
        ],
        code=dict(
            title="Action group call",
            lang="python",
            body='import requests\n\ndef guard(amount, merchant, category):\n    r = requests.post(\n        "https://sipi.bot/v1/transactions/evaluate",\n        json={"amount": amount, "merchant": merchant, "category": category},\n        headers={"Authorization": "Bearer KEY"},\n    )\n    return r.json()["decision"]  # APPROVED | BLOCKED | FLAGGED',
            caption="Wire it into the action group that spends.",
        ),
        faqs=[
            ("Does this replace AWS Budgets?",
             "No. AWS Budgets alerts on your AWS bill; sipi.bot decides before each agent transaction — including spend outside AWS. They compose."),
            ("Can it cap Bedrock inference specifically?",
             "Yes — category rules give inference its own ceiling; the agent can't exceed it regardless of what it's doing."),
            ("Is the decision instant?",
             "About 5 ms, no model call."),
        ],
        related=[("AWS Bedrock cost", "/cost-of/aws-bedrock-api-cost"), ("sipi.bot vs AWS Budgets", "/vs/aws-budgets"), ("DevOps automation", "/for/devops-automation")],
    ),
    dict(
        slug="dify",
        title="Dify Agent Budgets — sipi.bot Integration",
        desc="Cap spending in Dify workflows and agents. sipi.bot adds a pre-spend guard so automation can't burn API credits or trigger payments unattended.",
        h1="Spend Control for Dify",
        lead="Dify builds LLM apps and agent workflows quickly — which means workflows go to production fast, and production workflows spend. A guard node keeps the bill honest.",
        sections=[
            ("Why Dify workflows overspend",
             ["Workflow nodes call paid APIs on every run; an hourly workflow is 720 paid calls a day.",
              "Agent nodes can trigger external tools and payments.",
              "Retries re-run paid nodes automatically."]),
            ("How it works",
             ["Add an HTTP request node to sipi.bot before any spend step, and branch on the decision: APPROVED continues, BLOCKED stops, FLAGGED routes to a human."]),
            ("Rules that fit Dify workloads",
             ["Per-transaction cap on API purchases.",
              "Daily ceiling across workflows.",
              "Approval threshold for large spends."]),
        ],
        code=dict(
            title="Workflow branch",
            lang="text",
            body="HTTP Request node -> https://sipi.bot/v1/transactions/evaluate\nBranch:\n  APPROVED -> continue to paid step\n  BLOCKED  -> stop, log\n  FLAGGED  -> notify, pause for approval",
            caption="Three branches, one deterministic decision.",
        ),
        faqs=[
            ("Does sipi.bot run inside Dify?",
             "sipi.bot is external — Dify calls it over HTTP like any other API. Self-host is available."),
            ("Can it stop a workflow retry loop?",
             "Yes — velocity limits cap transactions per window, so a retry loop stops at the limit."),
            ("What about the open-source Dify self-host?",
             "Same integration — it's just HTTP. The MIT core self-hosts forever."),
        ],
        related=[("n8n", "/integrations/n8n"), ("Flowise", "/integrations/flowise"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
    dict(
        slug="flowise",
        title="Flowise Agent Budgets — sipi.bot Integration",
        desc="Add spend control to Flowise agents and workflows. A guard node returns APPROVED, BLOCKED, or FLAGGED before any purchase.",
        h1="Spend Control for Flowise",
        lead="Flowise builds agents with a drag-and-drop canvas — fast to prototype, fast to production, and fast to spend. A pre-spend guard keeps the canvas honest.",
        sections=[
            ("Why Flowise agents overspend",
             ["Tool nodes can call paid endpoints on every agent turn.",
              "Workflows with retry logic re-run paid nodes.",
              "No built-in dollar-level budget across nodes."]),
            ("How it works",
             ["Add a sipi.bot HTTP tool node before any spend step. Branch on APPROVED / BLOCKED / FLAGGED."]),
            ("Rules that fit Flowise workloads",
             ["Per-transaction cap for tool purchases.",
              "Merchant allowlist for approved paid tools.",
              "Approval threshold for large spends."]),
        ],
        code=dict(
            title="Decision branch",
            lang="text",
            body="sipi.bot tool node -> evaluate(amount, merchant, category)\nAPPROVED -> continue\nBLOCKED  -> stop + log\nFLAGGED  -> human approval queue",
            caption="Gate the nodes that spend.",
        ),
        faqs=[
            ("Does sipi.bot work with Flowise tool nodes?",
             "Yes — any HTTP-capable node can call the evaluate endpoint or MCP tool."),
            ("Can I cap a whole Flowise app?",
             "Yes — per-agent ceilings and shared daily caps apply to everything the app spends."),
            ("Is it self-hostable?",
             "The core is MIT-licensed — self-host alongside your Flowise deployment."),
        ],
        related=[("Dify", "/integrations/dify"), ("n8n", "/integrations/n8n"), ("Templates", "/templates/agent-spend-policy-template")],
    ),
    dict(
        slug="agentops",
        title="AgentOps + sipi.bot — Observe Agents, Gate Their Spend",
        desc="Run AgentOps for agent observability and sipi.bot for pre-spend enforcement. The two-layer stack for production agents.",
        h1="AgentOps + sipi.bot",
        lead="AgentOps tracks what your agents do — sessions, tokens, cost per run. sipi.bot decides whether a transaction may happen. Observability plus enforcement: the production stack.",
        sections=[
            ("What AgentOps does well",
             ["Session-level observability: traces, token counts, and cost per agent run.",
              "Team dashboards for agent behavior and drift.",
              "Strong for understanding what agents actually do."]),
            ("Where a monitoring tool can't help",
             ["It reports cost after the fact — a chart of the $12,400 night doesn't stop it.",
              "No pre-spend decision on a transaction in progress.",
              "No merchant allowlist, approval queue, or rule enforcement."]),
            ("How they compose",
             ["AgentOps for the picture; sipi.bot for the gate. Feed sipi.bot's audit log into AgentOps to correlate decisions with runs."]),
        ],
        code=dict(
            title="The stack",
            lang="text",
            body="Agent  ->  sipi.bot (APPROVED/BLOCKED/FLAGGED, ~5ms)  ->  Payment rail\n            |\n            +-- audit log (rule, amount, reason)  ->  AgentOps dashboard",
            caption="Observe with AgentOps, gate with sipi.bot.",
        ),
        faqs=[
            ("Do I need both?",
             "Yes, ideally — observability tells you what happened; the firewall decides what may happen. They're different layers of the same stack."),
            ("Is sipi.bot a competitor to AgentOps?",
             "No. sipi.bot doesn't trace sessions; AgentOps doesn't gate transactions. Complementary."),
            ("How do decisions reach AgentOps?",
             "sipi.bot's audit log is queryable via API, so you can stream decisions into AgentOps for correlation."),
        ],
        related=[("Best agent observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs AgentOps", "/vs/agentops"), ("Multi-agent governance", "/guides/multi-agent-spend-governance")],
    ),
]

FOR = [
    dict(
        slug="finance-teams",
        title="Spend Controls for Finance Teams | sipi.bot",
        desc="Finance teams controlling AI agent spend: budgets, approvals, and audit trails for autonomous spending across the org.",
        h1="Agent Spend Controls for Finance Teams",
        lead="You own the budget — and suddenly agents are spending it at 2 AM. Finance needs the same controls for agent spend that exist for procurement: budgets, approvals, and audit trails.",
        sections=[
            ("The finance problem",
             ["Agent spend is invisible until the bill: no PO, no approval, no ledger line.",
              "Providers cap their own APIs; nothing caps the whole agent fleet.",
              "Recovering spend after the fact is a post-mortem, not a control."]),
            ("What finance teams get",
             ["Per-agent and fleet-wide budgets enforced before money moves.",
              "An approval queue for spend above thresholds — the agent equivalent of a purchase order.",
              "A queryable audit log: what was bought, from whom, why, under which rule."]),
            ("How to deploy",
             ["Set a daily ceiling per team, an approval threshold per project, and an allowlist of approved vendors. Decisions are deterministic and logged."]),
        ],
        table=dict(
            headers=["Finance control", "sipi.bot equivalent"],
            rows=[
                ["Budget", "Daily / period ceiling per agent"],
                ["Purchase approval", "FLAGGED → human approval queue"],
                ["Vendor management", "Merchant allowlist"],
                ["Expense audit", "Queryable rule-level audit log"],
            ],
        ),
        faqs=[
            ("Can finance set budgets without touching code?",
             "Rules are managed via the dashboard and API — finance ops can own the policy while engineers own the integration."),
            ("What does the audit log contain?",
             "Every decision: amount, merchant, category, decision, and the rule that fired."),
            ("Is this about preventing fraud?",
             "It's about preventing runaway and unauthorized spend — the same governance finance applies everywhere else, applied to agents."),
        ],
        related=[("Agent cost center", "/glossary/agent-cost-center"), ("Cost allocation template", "/templates/cost-allocation-template"), ("Spend policy best practices", "/guides/agent-spend-policy-best-practices")],
    ),
    dict(
        slug="platform-engineers",
        title="Agent Spend Guardrails for Platform Engineers | sipi.bot",
        desc="Platform engineers building AI infrastructure: give every agent a spending policy with sipi.bot — one API call, deterministic, self-hostable.",
        h1="Agent Spend Guardrails for Platform Engineers",
        lead="You run the platform agents run on. If they spend, that's your pipeline to control — and prompts aren't controls.",
        sections=[
            ("The platform problem",
             ["Every team ships agents; every agent can spend. You need a shared layer, not per-team hope.",
              "The guardrail has to be deterministic — no model call that can be prompt-injected or argued with.",
              "It must fit your stack: HTTP, MCP, or CLI."]),
            ("What platform teams get",
             ["One API call (or MCP tool) that returns APPROVED, BLOCKED, or FLAGGED in ~5 ms.",
              "Rules as code: caps, allowlists, velocity limits, time-of-day rules.",
              "MIT-licensed core — self-host inside your VPC if you need to."]),
            ("How to deploy",
             ["Put sipi.bot in front of your payment path. Agent → sipi.bot → rail. Wire the audit log into your observability stack."]),
        ],
        table=dict(
            headers=["Platform concern", "sipi.bot answer"],
            rows=[
                ["Latency", "~5 ms decision, no model call"],
                ["Lock-in", "MIT core, self-host anywhere"],
                ["Fit", "HTTP API, MCP tool, CLI"],
                ["Audit", "Queryable rule-level log"],
            ],
        ),
        faqs=[
            ("Is it deployable in a private network?",
             "Yes — the core is MIT-licensed and self-hosts; the decision engine runs fully offline with your rules."),
            ("Does it work with our gateway?",
             "Yes — sipi.bot composes with LiteLLM, Cloudflare AI Gateway, and similar proxies: firewall first, then route."),
            ("What's the operational footprint?",
             "Small — a single service with a SQLite store; unlimited evaluations on hosted plans."),
        ],
        related=[("DevOps teams", "/for/devops-teams"), ("Self-host guide", "/self-hosted/"), ("sipi.bot vs LiteLLM", "/vs/litellm")],
    ),
    dict(
        slug="ml-engineers",
        title="ML Engineer Agent Cost Control | sipi.bot",
        desc="ML engineers running agent fleets and evals: cap inference spend, stop retry loops, and keep model experiments on budget.",
        h1="Agent Cost Control for ML Engineers",
        lead="Your experiments, evals, and agent fleets spend on inference — and the bill scales with every parallel run. Cap it before it caps your GPU budget.",
        sections=[
            ("The ML problem",
             ["Eval fleets spawn hundreds of parallel agent runs — cheap per call, expensive in aggregate.",
              "Retry loops on failing evals re-run inference continuously.",
              "Model drift to pricier tiers changes the bill without a code change."]),
            ("What ML teams get",
             ["Per-run and per-fleet ceilings enforced deterministically.",
              "Velocity limits that kill retry loops mid-run.",
              "Category rules: inference, data, and compute budgets stay separate."]),
            ("How to deploy",
             ["Call sipi.bot from the harness before each spend, or add the guard tool to your agent framework (LangChain, LangGraph, Pydantic AI, ...)."]),
        ],
        table=dict(
            headers=["ML concern", "sipi.bot answer"],
            rows=[
                ["Eval fleet cost", "Shared daily ceiling"],
                ["Retry loops", "Velocity limit"],
                ["Model drift", "Per-agent cap regardless of tier"],
                ["Experiments", "Category-scoped budgets"],
            ],
        ),
        faqs=[
            ("Does it add overhead to eval runs?",
             "About 5 ms per check — negligible next to inference latency."),
            ("Can I budget by experiment?",
             "Yes — per-agent rules let each experiment have its own ceiling."),
            ("Does it work with my framework?",
             "LangChain, LangGraph, Pydantic AI, SmolAgents, LlamaIndex, and plain HTTP all supported."),
        ],
        related=[("Pydantic AI", "/integrations/pydantic-ai"), ("LLM API pricing comparison", "/benchmarks/llm-api-pricing-comparison-2026"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="security-engineers",
        title="Agent Spend Security for Security Engineers | sipi.bot",
        desc="Security engineers: give autonomous agents a spending policy they can't be prompt-injected into breaking. Deterministic, auditable, self-hostable.",
        h1="Agent Spend Security for Security Engineers",
        lead="Prompt injection can make an agent do things its prompt never allowed — including spending. A deterministic firewall is the control a prompt can't be talked out of.",
        sections=[
            ("The security problem",
             ["An injected instruction in tool output can drive an agent to purchase or exfiltrate via payment rails.",
              "Model-based 'safety' can be bypassed; a rules engine can't.",
              "You need an audit trail for every money-touching decision."]),
            ("What security teams get",
             ["A deterministic decision path — no LLM in the approval loop to inject.",
              "Merchant allowlists that block unknown vendors regardless of what the agent claims.",
              "A queryable audit log of every transaction decision."]),
            ("How to deploy",
             ["Self-host the MIT core in your VPC; route all agent spend through it; wire the audit log to your SIEM."]),
        ],
        table=dict(
            headers=["Security concern", "sipi.bot answer"],
            rows=[
                ["Prompt injection spend", "Deterministic rules — no model in the path"],
                ["Unknown merchants", "Merchant allowlist"],
                ["Audit", "Rule-level queryable log"],
                ["Supply chain", "MIT core, self-host in VPC"],
            ],
        ),
        faqs=[
            ("Can a prompt injection bypass the firewall?",
             "No. The decision path is a deterministic rules engine — there's no model to inject. Rules can't be argued with."),
            ("Does sipi.bot hold keys or money?",
             "No — it's a decision API. It never holds money or private keys; your rail settles."),
            ("Where can I see the threat model?",
             "The security page documents how sipi.bot handles security."),
        ],
        related=[("Security page", "/security"), ("Prompt injection incidents", "/incidents/chatgpt-prompt-injection-exfil-2024-06"), ("Cybersecurity sector", "/sectors/cybersecurity")],
    ),
    dict(
        slug="ctos",
        title="AI Spend Governance for CTOs | sipi.bot",
        desc="CTOs shipping AI products: control what autonomous agents spend without slowing your roadmap. One API call, deterministic policy, full audit.",
        h1="AI Spend Governance for CTOs",
        lead="You're shipping agents to production. The question isn't whether they'll spend — it's whether you'll find out from the dashboard or from Stripe.",
        sections=[
            ("The CTO problem",
             ["Speed vs control: heavy governance slows agent velocity; no governance produces a $12,400 night.",
              "Vendor sprawl: every team picks providers; nobody sees the whole.",
              "You need a control that's technical, not procedural — enforced in the request path."]),
            ("What CTOs get",
             ["One integration point for every agent, on any stack: HTTP, MCP, or CLI.",
              "Policy you can set centrally and delegate per team.",
              "A board-ready audit log: what agents bought, from whom, under which rule."]),
            ("How to deploy",
             ["Integrate once behind your payment path, set org-wide defaults, let teams tune their own rules. $99/mo flat, unlimited evaluations — or self-host the MIT core."]),
        ],
        table=dict(
            headers=["CTO concern", "sipi.bot answer"],
            rows=[
                ["Speed", "~5 ms decision, no model call"],
                ["Control", "Central rules, per-team delegation"],
                ["Visibility", "Queryable audit log"],
                ["Cost", "Flat $99/$499, unlimited evals"],
            ],
        ),
        faqs=[
            ("What does integration cost in engineering time?",
             "One HTTP call or MCP registration per agent stack. Client wrappers for the common frameworks take a few lines."),
            ("Is it a subscription with per-call fees?",
             "No — Team and Business are flat-rate with unlimited transaction evaluations."),
            ("Can we self-host?",
             "Yes — MIT core, free forever. Hosted plans add the dashboard, approval queue, and stored audit log."),
        ],
        related=[("Pricing", "/pricing"), ("Startup founders", "/for/startup-founders"), ("AI startups", "/use-cases/ai-startups")],
    ),
]

USE_CASES = [
    dict(
        slug="agentic-commerce",
        title="Agentic Commerce — Let Agents Buy, Not Run Wild",
        desc="Agentic commerce: agents buying compute, data, and services autonomously. sipi.bot puts a spending policy in front of every agent purchase.",
        h1="Agentic Commerce: Controlling Agent Purchases",
        lead="Agents are becoming customers — buying compute, data, APIs, even negotiating with other agents. The commerce rails exist (x402, AP2, AgentKit). The control layer is what's missing.",
        sections=[
            ("What agentic commerce means",
             ["Agents purchase services on machine rails: x402 (HTTP-based), Google AP2, Coinbase AgentKit.",
              "Purchases are small, frequent, and autonomous — no human in the loop.",
              "The rails settle fast; the control has to decide faster."]),
            ("The control problem",
             ["Rails move money; they don't screen it.",
              "A runaway agent on a fast rail is damage at settlement speed.",
              "You need a decision before settlement: approve, block, or flag."]),
            ("How sipi.bot fits",
             ["sipi.bot sits in front of the rail as the approval layer: amount, merchant, category → APPROVED, BLOCKED, or FLAGGED in ~5 ms, fully logged."]),
        ],
        table=dict(
            headers=["Rail", "What it does", "sipi.bot role"],
            rows=[
                ["x402", "HTTP payment flow", "Pre-settlement decision"],
                ["AP2", "Google agent payments", "Pre-settlement decision"],
                ["AgentKit", "Onchain agent payments", "Pre-settlement decision"],
                ["Direct APIs", "Vendor purchases", "Allowlist + caps"],
            ],
        ),
        faqs=[
            ("Is agentic commerce real or speculative?",
             "Real — the rails are live and products are shipping. What's immature is the control layer; that's the gap sipi.bot fills."),
            ("Does sipi.bot hold funds?",
             "No — it decides. The rail settles. No custody, no float."),
            ("What stops an agent buying from an unknown vendor?",
             "The merchant allowlist — unknown vendors are BLOCKED unless you've approved them."),
        ],
        related=[("x402 approach", "/alternatives/x402/"), ("Agent payment firewall", "/guides/agent-payment-firewall"), ("sipi.bot vs AgentKit", "/vs/openai-agentkit")],
    ),
    dict(
        slug="sales-development-agents",
        title="Sales Development Agent Spend Control | sipi.bot",
        desc="SDR and outbound agents spend on enrichment, sequencing, and data APIs. Cap the spend, keep the velocity.",
        h1="Spend Control for Sales Development Agents",
        lead="SDR agents research, enrich, and sequence — each step hits a paid API. At outbound scale, per-credit costs compound fast.",
        sections=[
            ("Where SDR agents spend",
             ["Contact enrichment APIs per lead.",
              "Sequencing and deliverability tools per campaign.",
              "LLM inference for research and personalization at scale."]),
            ("The failure modes",
             ["A campaign loop re-enriching the same list multiplies credits.",
              "An unknown data vendor charges per lookup with no approval.",
              "Overnight runs burn the monthly enrichment budget before review."]),
            ("Which rules to start with",
             ["Daily ceiling on enrichment spend.",
              "Merchant allowlist for approved data vendors.",
              "Approval threshold for new vendor spend."]),
        ],
        table=dict(
            headers=["SDR spend", "Control"],
            rows=[
                ["Enrichment APIs", "Daily ceiling + allowlist"],
                ["Sequencing tools", "Category budget"],
                ["Inference", "Per-agent cap"],
                ["New vendors", "Approval threshold"],
            ],
        ),
        faqs=[
            ("Will this slow outbound velocity?",
             "No — decisions take ~5 ms; the agent keeps its speed, the budget stays enforced."),
            ("Can marketing ops own the rules?",
             "Yes — rules are managed via dashboard/API, so ops can adjust budgets without engineering."),
        ],
        related=[("Marketing sector", "/sectors/marketing"), ("AI agency operations", "/use-cases/ai-agency-operations"), ("Merchant allowlists", "/guides/merchant-allowlists")],
    ),
    dict(
        slug="automated-qa-testing",
        title="QA Agent Fleet Cost Control | sipi.bot",
        desc="Automated QA agents run test fleets that spend on compute and APIs. Cap fleet spend and stop retry loops.",
        h1="Cost Control for Automated QA Agents",
        lead="QA agents run thousands of test scenarios per build — each spending on compute and third-party APIs. Fleet-scale automation needs fleet-scale budgets.",
        sections=[
            ("Where QA agents spend",
             ["Compute for test execution and parallel runners.",
              "LLM inference for assertion generation and failure analysis.",
              "Third-party test and mock APIs per scenario."]),
            ("The failure modes",
             ["A failing suite retries all scenarios — spend multiplies with each retry.",
              "Parallel fleets compound spend during a single build.",
              "Nightly runs burn budget before anyone reviews."]),
            ("Which rules to start with",
             ["Shared daily ceiling across the fleet.",
              "Velocity limit on retries.",
              "Category rule: compute vs inference budgets."]),
        ],
        table=dict(
            headers=["QA spend", "Control"],
            rows=[
                ["Parallel runners", "Fleet daily ceiling"],
                ["Retries", "Velocity limit"],
                ["Inference", "Per-agent cap"],
                ["Test APIs", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Does sipi.bot slow test execution?",
             "No — ~5 ms per check, and only on spend actions, not on every assertion."),
            ("Can different suites have different budgets?",
             "Yes — per-agent rules let you budget by suite or environment."),
        ],
        related=[("DevOps teams", "/for/devops-teams"), ("DevOps automation", "/for/devops-automation"), ("AI agent cost per task", "/benchmarks/ai-agent-cost-per-task")],
    ),
    dict(
        slug="backoffice-automation",
        title="Backoffice Automation Spend Control | sipi.bot",
        desc="Backoffice automation agents (finance ops, HR, procurement) spend on APIs and tools. Cap the spend with per-agent budgets.",
        h1="Spend Control for Backoffice Automation",
        lead="Backoffice bots reconcile, route, and process — quietly, all day, against paid APIs. Quiet spend is the hardest spend to catch.",
        sections=[
            ("Where backoffice agents spend",
             ["Accounting and reconciliation APIs per batch.",
              "HR and payroll tool calls per employee record.",
              "Document processing (OCR, parsing) at volume."]),
            ("The failure modes",
             ["A reconciliation job re-running overnight multiplies per-batch charges.",
              "A new tool vendor bypasses procurement — allowlist it.",
              "Volume spikes (month-end, payroll) hit overage tiers."]),
            ("Which rules to start with",
             ["Per-agent daily ceiling.",
              "Merchant allowlist for approved tools.",
              "Time-of-day rule for overnight batches."]),
        ],
        table=dict(
            headers=["Backoffice spend", "Control"],
            rows=[
                ["Reconciliation APIs", "Per-agent ceiling"],
                ["HR tool calls", "Category budget"],
                ["Document processing", "Daily ceiling"],
                ["New vendors", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Is this only for finance bots?",
             "No — any backoffice automation that calls paid APIs: HR, ops, procurement, document processing."),
            ("What about month-end spikes?",
             "Set the ceiling where it should be and let FLAGGED route the rest to approval instead of overage."),
        ],
        related=[("Finance teams", "/for/finance-teams"), ("Cost allocation template", "/templates/cost-allocation-template"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
]

VS = [
    dict(
        slug="agentops",
        name="AgentOps",
        title="sipi.bot vs AgentOps — Observability vs Enforcement",
        desc="AgentOps traces agent sessions; sipi.bot gates transactions before they settle. See where each wins and why they compose.",
        h1="sipi.bot vs AgentOps",
        lead="AgentOps is an agent observability platform; sipi.bot is a pre-spend firewall. One tells you what agents did, the other decides what they may spend.",
        sections=[
            ("What AgentOps does well",
             ["Session traces, token counts, and cost-per-run dashboards.",
              "Team-level views of agent behavior and drift.",
              "Great for understanding and debugging agent runs."]),
            ("Where it falls short",
             ["Reports cost after the fact — no decision before a transaction.",
              "No merchant allowlist, approval queue, or rule enforcement.",
              "A chart of a $12,400 night doesn't stop it."]),
            ("Where sipi.bot wins",
             ["Pre-spend APPROVED / BLOCKED / FLAGGED decisions.",
              "Caps, allowlists, velocity limits, time-of-day rules.",
              "Human-in-the-loop approval for flagged spend.",
              "Deterministic, ~5 ms, no model call."]),
            ("When to use which",
             ["AgentOps for observability; sipi.bot for enforcement. Stream the audit log into AgentOps for a single pane."]),
        ],
        table=dict(
            headers=["Dimension", "AgentOps", "sipi.bot"],
            rows=[
                ["Role", "Observe agent runs", "Gate agent spend"],
                ["When it acts", "After the run", "Before the transaction"],
                ["Controls", "Dashboards, alerts", "Caps, allowlists, approvals"],
                ["Audit", "Session traces", "Rule-level decisions"],
                ["Pricing", "Per-seat/platform", "Flat $99/$499, unlimited evals"],
            ],
        ),
        faqs=[
            ("Are they competitors?",
             "No — different layers. Observability and enforcement both belong in a production agent stack."),
            ("Can I feed sipi.bot decisions into AgentOps?",
             "Yes — the audit log is queryable via API."),
            ("Which one prevents runaway spend?",
             "Only sipi.bot — it acts before money moves. AgentOps will show you the damage beautifully."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("AgentOps integration", "/integrations/agentops"), ("AI spend monitoring", "/best/ai-spend-monitoring")],
    ),
    dict(
        slug="arize-phoenix",
        name="Arize Phoenix",
        title="sipi.bot vs Arize Phoenix — LLM Observability vs Spend Firewall",
        desc="Phoenix traces and evaluates LLM apps. sipi.bot blocks runaway agent spend. Compare scope and how they work together.",
        h1="sipi.bot vs Arize Phoenix",
        lead="Arize Phoenix is an open-source LLM observability and evaluation platform. sipi.bot is a pre-spend firewall. Tracing shows you the what; the firewall controls the may.",
        sections=[
            ("What Phoenix does well",
             ["Open-source tracing and evals for LLM apps.",
              "Deep insight into prompts, spans, and evaluation scores.",
              "Strong community and self-host option."]),
            ("Where it falls short",
             ["No pre-spend decision on transactions.",
              "No merchant allowlist or approval queue.",
              "Observation after the fact, not enforcement before it."]),
            ("Where sipi.bot wins",
             ["Deterministic pre-spend decisions.",
              "Dollar-level controls: caps, velocity, categories.",
              "Approval workflow for edge cases.",
              "~5 ms, no model in the path."]),
            ("When to use which",
             ["Phoenix for tracing and evals; sipi.bot for spend enforcement. Complementary layers."]),
        ],
        table=dict(
            headers=["Dimension", "Arize Phoenix", "sipi.bot"],
            rows=[
                ["Role", "Trace & evaluate LLM apps", "Gate agent spend"],
                ["When it acts", "During/after runs", "Before transactions"],
                ["Open source", "Yes", "MIT core"],
                ["Controls", "Evals, spans", "Caps, allowlists, approvals"],
                ["Pricing", "OSS + platform", "Flat $99/$499, unlimited evals"],
            ],
        ),
        faqs=[
            ("Do they overlap?",
             "Minimally — Phoenix is observability/eval; sipi.bot is enforcement. Run both."),
            ("Is sipi.bot open source?",
             "The core is MIT-licensed and self-hostable; hosted plans add the dashboard and approval queue."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs Langfuse", "/vs/langfuse"), ("Agent observability", "/best/best-ai-agent-observability-tools")],
    ),
    dict(
        slug="stripe-billing",
        name="Stripe Billing",
        title="sipi.bot vs Stripe Billing — Subscriptions vs Spend Firewall",
        desc="Stripe Billing handles subscriptions and invoicing. sipi.bot blocks runaway agent spend before it settles. Different jobs — here's when you might confuse them.",
        h1="sipi.bot vs Stripe Billing",
        lead="Stripe Billing is the world's subscription and invoicing infrastructure. sipi.bot is a pre-spend firewall for agents. They don't compete — but teams shopping for 'spend control' sometimes land on the wrong one.",
        sections=[
            ("What Stripe Billing does well",
             ["Subscriptions, invoices, and payment links at global scale.",
              "Dunning, proration, and revenue reporting.",
              "The right tool for billing your customers."]),
            ("Where it falls short for agent spend",
             ["It bills humans; it doesn't screen agent-initiated transactions.",
              "Stripe Radar flags fraud (stolen cards, chargebacks) — not 'your agent bought from an unknown vendor 40 times'.",
              "No per-agent budgets, velocity limits, or approval queue."]),
            ("Where sipi.bot wins",
             ["Decides before agent transactions settle: APPROVED, BLOCKED, FLAGGED.",
              "Merchant allowlists, category rules, velocity limits.",
              "Human-in-the-loop approval queue.",
              "Queryable rule-level audit log."]),
            ("When to use which",
             ["Use Stripe Billing to bill customers. Use sipi.bot to control what your agents spend — including through Stripe."]),
        ],
        table=dict(
            headers=["Dimension", "Stripe Billing", "sipi.bot"],
            rows=[
                ["Job", "Bill customers", "Gate agent spend"],
                ["Fraud model", "Stolen cards, chargebacks", "Runaway agents, unknown vendors"],
                ["When it acts", "Settlement/recurring", "Before the transaction"],
                ["Controls", "Invoices, dunning", "Caps, allowlists, approvals"],
                ["Cost", "Per-transaction %", "Flat $99/$499, unlimited evals"],
            ],
        ),
        faqs=[
            ("Can sipi.bot replace Stripe?",
             "No — sipi.bot never moves money. Your rail (including Stripe) still settles; sipi.bot decides whether it may."),
            ("Is this the same as Stripe Radar?",
             "No — Radar detects card fraud. sipi.bot detects agent spend policy violations. See the full comparison."),
            ("Do they work together?",
             "Yes — agents that pay through Stripe call sipi.bot first; approved transactions settle normally."),
        ],
        related=[("sipi.bot vs Stripe Radar", "/vs/stripe-radar"), ("Stripe integration", "/integrations/stripe"), ("Agent payment firewall", "/guides/agent-payment-firewall")],
    ),
    dict(
        slug="laminar-ai",
        name="Laminar AI",
        title="sipi.bot vs Laminar — LLM Monitoring vs Spend Firewall",
        desc="Laminar traces LLM apps and costs. sipi.bot blocks runaway agent spend. See where each wins.",
        h1="sipi.bot vs Laminar",
        lead="Laminar is an LLM monitoring and tracing platform. sipi.bot is a pre-spend firewall. One gives you the picture; the other holds the gate.",
        sections=[
            ("What Laminar does well",
             ["Tracing, evals, and cost tracking for LLM applications.",
              "Clean dashboards for prompt and span analysis.",
              "Solid for understanding model behavior and cost drivers."]),
            ("Where it falls short",
             ["Post-hoc reporting — no pre-spend decision.",
              "No merchant allowlist, approval queue, or rule enforcement.",
              "Cost tracking shows the bill; it can't stop the next transaction."]),
            ("Where sipi.bot wins",
             ["Decides before money moves.",
              "Dollar-level controls across every merchant.",
              "Approval workflow for edge cases.",
              "Deterministic, ~5 ms."]),
            ("When to use which",
             ["Laminar for monitoring; sipi.bot for enforcement. Feed the audit log into Laminar for context."]),
        ],
        table=dict(
            headers=["Dimension", "Laminar", "sipi.bot"],
            rows=[
                ["Role", "Monitor LLM apps", "Gate agent spend"],
                ["When it acts", "After requests", "Before transactions"],
                ["Controls", "Traces, evals", "Caps, allowlists, approvals"],
                ["Decision", "Cost reports", "APPROVED / BLOCKED / FLAGGED"],
                ["Pricing", "Platform", "Flat $99/$499, unlimited evals"],
            ],
        ),
        faqs=[
            ("Do Laminar and sipi.bot overlap?",
             "Hardly. Monitoring answers what happened; the firewall decides what may happen."),
            ("Can I correlate decisions with traces?",
             "Yes — sipi.bot's audit log is API-queryable, so decisions can join traces in Laminar."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs Langfuse", "/vs/langfuse"), ("AI cost management tools", "/best/ai-cost-management-tools")],
    ),
]

GLOSSARY = [
    dict(
        slug="agentic-payment",
        term="Agentic payment",
        title="What is an Agentic Payment? | sipi.bot Glossary",
        desc="Agentic payment: a payment initiated and authorized by an AI agent, not a human. Rails, risks, and controls explained.",
        h1="What is an Agentic Payment?",
        lead="An agentic payment is a payment initiated by an autonomous AI agent on behalf of a user or organization — with the agent deciding when, how much, and to whom to pay.",
        sections=[
            ("How it works",
             ["Agents trigger payments through machine rails — x402 (HTTP-based), Google AP2, Coinbase AgentKit — or directly through vendor APIs.",
              "The agent makes the spending decision; the rail settles it."]),
            ("Why it's risky",
             ["The agent is following a prompt, not judgment. A retry loop, hallucination, or prompt injection can turn one intended purchase into many.",
              "Rails move money fast; there's no human to say 'stop' mid-loop."]),
            ("The control layer",
             ["A spend firewall sits between the agent and the rail: every proposed payment gets APPROVED, BLOCKED, or FLAGGED before settlement."]),
        ],
        faqs=[
            ("Is an agentic payment the same as an API payment?",
             "No. An API payment is a fixed integration; an agentic payment is a decision the agent makes at runtime — which is exactly why it needs runtime controls."),
            ("Do agentic payments require human authorization?",
             "Not by default — that's the point. Controls (approval thresholds) can require it for flagged amounts."),
        ],
        related=[("x402", "/glossary/x402"), ("AP2", "/glossary/ap2"), ("Agent wallet", "/glossary/agent-wallet")],
    ),
    dict(
        slug="x402",
        term="x402",
        title="What is x402? Agentic Payment Protocol | sipi.bot Glossary",
        desc="x402 is an HTTP-based payment protocol for AI agents using the 402 Payment Required status. How it works and why agents need a firewall on top.",
        h1="What is x402?",
        lead="x402 is an open protocol that lets AI agents pay for services over plain HTTP, using the 402 Payment Required status code as the payment trigger.",
        sections=[
            ("How it works",
             ["An agent requests a resource; the server responds 402 Payment Required with payment details.",
              "The agent settles via the specified payment method and retries the request with proof of payment.",
              "It's stateless, standard HTTP — no custom transport."]),
            ("Why it matters",
             ["It turns any API into a payable resource — agents can buy compute, data, and services the same way they call tools."]),
            ("The risk",
             ["Speed and autonomy: an agent in a loop can settle many payments in minutes. A firewall decides before settlement."]),
        ],
        faqs=[
            ("Is x402 the same as AP2?",
             "No. x402 is an HTTP-status-based protocol; AP2 is Google's agent payments protocol. sipi.bot sits in front of both."),
            ("Does sipi.bot support x402?",
             "Yes — sipi.bot is the approval layer in front of x402 flows."),
        ],
        related=[("x402 approach", "/alternatives/x402/"), ("Agentic payment", "/glossary/agentic-payment"), ("Agent payment firewall", "/guides/agent-payment-firewall")],
    ),
    dict(
        slug="ap2",
        term="AP2",
        title="What is AP2? Google Agent Payments Protocol | sipi.bot Glossary",
        desc="AP2 is Google's agent payments protocol. How it works, how it differs from x402, and why agents need pre-spend controls.",
        h1="What is AP2?",
        lead="AP2 (Agent Payments Protocol) is Google's protocol for enabling AI agents to make payments. It's one of the machine-payment rails sipi.bot gates.",
        sections=[
            ("How it works",
             ["AP2 defines how agents initiate, authorize, and settle payments across services.",
              "It's designed for agent-to-service commerce at scale."]),
            ("Why it matters",
             ["It's a signal that agentic payments are becoming infrastructure — and infrastructure needs guardrails."]),
            ("The risk",
             ["Faster settlement means faster damage from a runaway agent. Pre-settlement decisions are the control."]),
        ],
        faqs=[
            ("Is AP2 available now?",
             "Check Google's current documentation for availability and scope. The protocol family (x402, AP2, AgentKit) is the pattern to design for."),
            ("Does sipi.bot support AP2?",
             "Yes — sipi.bot sits in front of AP2 flows as the approval layer."),
        ],
        related=[("Agentic payment", "/glossary/agentic-payment"), ("x402", "/glossary/x402"), ("sipi.bot vs AgentKit", "/vs/openai-agentkit")],
    ),
    dict(
        slug="agent-wallet",
        term="Agent wallet",
        title="What is an Agent Wallet? | sipi.bot Glossary",
        desc="An agent wallet lets an AI agent hold and spend funds autonomously. The risks and the controls that make it safe.",
        h1="What is an Agent Wallet?",
        lead="An agent wallet is a payment credential or wallet controlled by an AI agent rather than a human — enabling autonomous purchases on machine rails.",
        sections=[
            ("How it works",
             ["The agent holds a credential (card, account, onchain wallet) it can authorize against.",
              "Rails like x402 and AgentKit are designed for wallet-controlled agents."]),
            ("Why it's risky",
             ["A credential in an agent's hands is spendable 24/7. Prompt injection or a retry loop can drain it without human intent.",
              "The wallet doesn't judge; it pays."]),
            ("The control layer",
             ["sipi.bot sits in front of the wallet: every proposed spend gets a deterministic APPROVED, BLOCKED, or FLAGGED before the wallet authorizes."]),
        ],
        faqs=[
            ("Is an agent wallet a custodial wallet?",
             "It depends on the rail. sipi.bot itself never holds funds — it's a decision layer in front of whatever wallet you use."),
            ("Can a firewall stop a drained wallet?",
             "A firewall can't reverse settlement, but it stops the drain before it starts — per-transaction caps and velocity limits bite first."),
        ],
        related=[("Agentic payment", "/glossary/agentic-payment"), ("Spend approval", "/glossary/spend-approval"), ("x402", "/glossary/x402")],
    ),
    dict(
        slug="spend-approval",
        term="Spend approval",
        title="What is Spend Approval? | sipi.bot Glossary",
        desc="Spend approval routes an agent transaction to a human before money moves. How FLAGGED transactions and approval queues work.",
        h1="What is Spend Approval?",
        lead="Spend approval is the human-in-the-loop control that routes an agent's proposed transaction to a person for review before any money moves.",
        sections=[
            ("How it works",
             ["When a transaction crosses an approval threshold (or matches a flag rule), the firewall returns FLAGGED instead of APPROVED.",
              "The transaction is held in an approval queue; a human reviews it in the dashboard and approves or denies.",
              "Only after approval does the agent proceed to settlement."]),
            ("Why it matters",
             ["Hard blocks stop bad spend but also stop legitimate edge cases. Approval keeps agents fast while keeping big or unusual purchases human-checked."]),
        ],
        faqs=[
            ("What's the difference between BLOCKED and FLAGGED?",
             "BLOCKED is final — the transaction violates a hard rule and no money moves. FLAGGED is conditional — it's held for human review, then allowed or denied."),
            ("Where do approvals happen?",
             "In the hosted dashboard's approval queue. Self-hosted deployments wire their own queue to the API."),
        ],
        related=[("Approval workflow template", "/templates/approval-workflow"), ("Human-in-the-loop approval", "/glossary/human-in-the-loop-approval"), ("Approval threshold", "/glossary/approval-threshold")],
    ),
    dict(
        slug="overage-tier",
        term="Overage tier",
        title="What is an Overage Tier? | sipi.bot Glossary",
        desc="Overage tiers bill extra when an API or provider usage crosses included limits. How agents hit them and how to prevent it.",
        h1="What is an Overage Tier?",
        lead="An overage tier is a pricing band that charges a higher rate once your usage exceeds the included allotment — the classic surprise on an AI bill.",
        sections=[
            ("How overage works",
             ["Most AI providers bill included usage + per-unit overage beyond it.",
              "The overage rate is often higher than the included unit rate.",
              "An agent in a loop can cross the included allotment in minutes."]),
            ("Why agents hit it",
             ["Autonomous volume: retries, fan-out, and long contexts consume allotment fast.",
              "The crossing happens silently — you find out on the invoice."]),
            ("The control",
             ["A pre-spend firewall caps the dollars before the tier is crossed: per-agent ceilings, velocity limits, and category rules."]),
        ],
        faqs=[
            ("Is overage always more expensive?",
             "Typically yes — overage units are billed at a higher effective rate than included units. Check your provider's pricing."),
            ("Can sipi.bot prevent overage?",
             "Yes — set a daily ceiling below the included allotment and the agent physically can't cross into the overage band."),
        ],
        related=[("Token burn rate", "/glossary/token-burn-rate"), ("Daily spend ceiling", "/glossary/daily-spend-ceiling"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs")],
    ),
]

# --- hub metadata -----------------------------------------------------------
ERRORS_HUB = dict(
    title="sipi.bot API Error Codes — Reference | sipi.bot",
    desc="Complete reference for sipi.bot API error codes: invalid_api_key, rate_limited, rule_error, transaction_error, and more — with fixes.",
    h1="sipi.bot API Error Codes",
    lead="Every error the sipi.bot API returns, what it means, and how to fix it. Error names and HTTP statuses match the live API exactly.",
)
