"""Round 24 pSEO data — sipi.bot (2026-08-08).

Fifth round. "Tightening" round: a real technical fix (public/ canonical
mismatch — see /tmp/fix_public_canonicals.py + rebuild_sitemap.py changes)
plus 24 targeted pages in the genuinely thin spots:
  sectors/ +3 (education, government, media-publishing)
  cost-of/ +4 (consumer AI subscription pricing — huge volume)
  glossary/ +4 (time-of-day-rule, category-rule, approval-queue, merchant-blocklist)
  for/ +2 (finops-teams, heads-of-ai)
  use-cases/ +2 (email-agents, web-research-agents)
  faq/ +2 (llm-gateway difference, stripe)
  best/ +2 (spend-policy tools, cost dashboards)
  templates/ +2 (agent-budget, vendor-risk-assessment)
  checklists/ +3 (public/ — RFP, vendor due diligence, governance)

Content rules unchanged: honest, no fabricated stats; consumer subscription
prices labeled "verify current"; $99/$499 flat, MIT core, ~5 ms, 3 decisions,
6 rule types, HTTP+MCP+CLI, rail-agnostic, queryable audit log.
"""

SECTORS = [
    dict(
        slug="education",
        title="AI Spend Control for Education | sipi.bot",
        desc="Spend control for education AI agents — tutoring bots, grading automation, and admin agents. Cap inference spend across the institution.",
        h1="Spend Control for Education AI Agents",
        lead="Schools and edtech platforms run agents for tutoring, grading, and admissions — at student scale. Volume is the budget killer: thousands of sessions × inference per session.",
        sections=[
            ("Where education agents spend",
             ["Tutoring and homework-help bots hitting LLM inference per session.",
              "Grading and feedback automation processing every submission.",
              "Admissions and admin agents pulling data and documents.",
              "Language-learning apps with per-lesson generation."]),
            ("The failure modes",
             ["A tutoring loop re-generating responses multiplies inference spend.",
              "End-of-term volume spikes (finals, admissions) hit overage tiers.",
              "A research agent buying from an unknown vendor bypasses procurement."]),
            ("Which rules to start with",
             ["Daily ceiling across the tutoring fleet.",
              "Velocity limit on retry loops.",
              "Category rule: instruction vs admin vs research budgets.",
              "Merchant allowlist for approved content and data vendors."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in education"],
            rows=[
                ["Daily spend ceiling", "Fleet-wide budget in one number"],
                ["Velocity limit", "Tutoring loops die fast"],
                ["Category rule", "Instruction vs admin budgets"],
                ["Merchant allowlist", "Unvetted vendors never billed"],
            ],
        ),
        faqs=[
            ("Can I budget per course or program?",
             "Yes — per-agent rules let each program run its own ceiling."),
            ("Does the firewall slow tutoring?",
             "No — ~5 ms per check, only on spend actions."),
        ],
        related=[("Customer support bots", "/use-cases/customer-support-bots"), ("How to set spend limits", "/how-to/how-to-set-spend-limits"), ("Agent budget", "/glossary/agent-budget")],
    ),
    dict(
        slug="government",
        title="AI Spend Control for Government | sipi.bot",
        desc="Public-sector AI agents: permits, citizen support, and document processing. Transparent, auditable spend control with procurement constraints.",
        h1="Spend Control for Government AI Agents",
        lead="Public-sector agents handle permits, citizen queries, and documents — with procurement rules, audit requirements, and public accountability. Spend control has to be transparent.",
        sections=[
            ("Where government agents spend",
             ["Citizen-support bots answering at volume.",
              "Document and permit processing (OCR, classification).",
              "Research and analysis agents pulling data sources."]),
            ("The failure modes",
             ["Unattended overnight runs without review.",
              "Unknown vendors bypassing procurement — an allowlist problem.",
              "No audit trail for a purchase someone will ask about later."]),
            ("Which rules to start with",
             ["Merchant allowlist for approved vendors only.",
              "Approval threshold for anything above procurement limits.",
              "Queryable audit log — every decision attributable."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in government"],
            rows=[
                ["Merchant allowlist", "Procurement control on agent spend"],
                ["Approval threshold", "Material spend waits for review"],
                ["Audit log", "Every decision attributable"],
                ["Time-of-day rule", "Overnight runs need approval"],
            ],
        ),
        faqs=[
            ("Does the audit log satisfy transparency needs?",
             "It records every decision — amount, merchant, rule — which is the evidence base a review needs. It's a control, not a compliance certification."),
            ("Can procurement control vendors?",
             "Yes — the allowlist IS the approved-vendor list for agents."),
        ],
        related=[("Compliance officers", "/for/compliance-officers"), ("Audit trail", "/glossary/agent-audit-trail"), ("Procurement teams", "/for/procurement-teams")],
    ),
    dict(
        slug="media-publishing",
        title="AI Spend Control for Media & Publishing | sipi.bot",
        desc="Media and publishing agents: content drafts, translation, distribution. Cap inference volume across the newsroom without slowing output.",
        h1="Spend Control for Media & Publishing Agents",
        lead="Newsrooms run agents for drafting, translation, SEO, and distribution — high volume, tight margins. Inference cost is now a line item editors have to care about.",
        sections=[
            ("Where media agents spend",
             ["Drafting and summarization agents per article.",
              "Translation engines across languages.",
              "SEO and distribution agents hitting APIs per post.",
              "Content moderation at comment volume."]),
            ("The failure modes",
             ["A draft agent re-generating variations multiplies inference.",
              "Syndication loops re-calling distribution APIs.",
              "Translation volume spikes during breaking news."]),
            ("Which rules to start with",
             ["Per-agent daily ceiling.",
              "Velocity limit on generation loops.",
              "Category rule: drafting vs translation vs distribution."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in media"],
            rows=[
                ["Per-agent ceiling", "Each workflow has its own budget"],
                ["Velocity limit", "Generation loops die fast"],
                ["Category rule", "Draft vs translate vs distribute"],
            ],
        ),
        faqs=[
            ("Does this slow the newsroom?",
             "No — ~5 ms per check, and only spend actions trigger it."),
            ("Can I cap translation spend specifically?",
             "Yes — category rules give translation its own ceiling."),
        ],
        related=[("Content bots", "/for/content-bots"), ("Backoffice automation", "/use-cases/backoffice-automation"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs")],
    ),
]

COST_OF = [
    dict(
        slug="chatgpt-plus-cost",
        title="How Much Does ChatGPT Cost? — Plans Explained",
        desc="ChatGPT pricing: the free tier, Plus, Pro, and Team plans, what's included, and what agents add on top. Honest breakdown from sipi.bot.",
        h1="How Much Does ChatGPT Cost?",
        lead="ChatGPT has a free tier and several paid plans. The subscription is simple — the surprise is everything your AI usage adds beyond it.",
        sections=[
            ("The plan structure",
             ["A free tier exists for light use; paid plans add higher limits, newer models, and extra features.",
              "Consumer plans are per-month; Team/Enterprise are per-seat with org controls.",
              "List prices change — verify current pricing on OpenAI's site."]),
            ("What people actually spend",
             ["Most individuals pay for one subscription tier.",
              "Teams pay per seat, and seats multiply fast.",
              "Agents that call the OpenAI API are billed separately from any ChatGPT plan — that's where the real spend lives."]),
            ("The agent angle",
             ["ChatGPT usage and API usage are different bills. Agents hit the API — and API spend is where a firewall earns its keep."]),
        ],
        table=dict(
            headers=["Tier", "Type", "Watch"],
            rows=[
                ["Free", "Consumer", "Limits"],
                ["Plus", "Consumer monthly", "Seat × team"],
                ["Pro", "Power user", "Overage behavior"],
                ["Team/Enterprise", "Per seat", "Seat sprawl"],
            ],
        ),
        faqs=[
            ("Is ChatGPT free?",
             "There's a free tier with limits. Paid plans raise them. Verify current pricing."),
            ("Is ChatGPT the same as the OpenAI API?",
             "No — separate products, separate bills. Agents typically use the API, not ChatGPT."),
            ("How do I control API spend from agents?",
             "Per-agent caps and velocity limits — the firewall governs the API bill the subscription never sees."),
        ],
        related=[("OpenAI API cost", "/cost-of/openai-api-cost"), ("OpenAI spending limits", "/vs/openai-spending-limits"), ("How to control AI API costs", "/answers/how-to-control-ai-api-costs/")],
    ),
    dict(
        slug="claude-pro-cost",
        title="How Much Does Claude Pro Cost? — Plans Explained",
        desc="Claude pricing: Pro, Max, and Team plans, what Claude Code adds, and what agents spend beyond the subscription. Honest breakdown.",
        h1="How Much Does Claude Pro Cost?",
        lead="Claude's consumer plans are per-month with usage allotments — and Claude Code rides on top, which changes the bill math for developers.",
        sections=[
            ("The plan structure",
             ["Pro is the standard consumer tier; Max tiers add larger usage allotments for heavy users.",
              "Claude Code is included with Claude plans but consumes the usage allotment fast in agentic sessions.",
              "Verify current pricing and allotments on Anthropic's site."]),
            ("What people actually spend",
             ["Light users: one Pro subscription.",
              "Agentic coders: subscription + API overage when sessions exceed the allotment.",
              "Teams: per-seat plans with shared or individual allotments."]),
            ("The agent angle",
             ["Claude Code in agentic mode burns tokens quickly. The subscription is the entry cost; the agent's tool purchases and API overage are the real spend."]),
        ],
        table=dict(
            headers=["Tier", "Type", "Watch"],
            rows=[
                ["Pro", "Consumer monthly", "Usage allotment"],
                ["Max", "Heavy use", "Agentic sessions"],
                ["Team", "Per seat", "Seat sprawl"],
            ],
        ),
        faqs=[
            ("Is Claude Code free?",
             "It requires a Claude subscription or API billing — the subscription tier sets your allotment."),
            ("Why does my Claude bill spike with agents?",
             "Agentic sessions consume tokens fast; overage and third-party tool spend are the usual culprits."),
            ("How do I control Claude Code spend?",
             "Provider limits for Claude's own usage, plus a firewall for the agent's purchases across other merchants."),
        ],
        related=[("Claude Code pricing", "/cost-of/claude-code-pricing"), ("Claude Code integration", "/integrations/claude-code"), ("Anthropic API cost", "/cost-of/anthropic-api-cost")],
    ),
    dict(
        slug="gemini-advanced-cost",
        title="How Much Does Google Gemini Cost? — Plans Explained",
        desc="Google AI plans: free tier, AI Pro, AI Ultra/Advanced, and Workspace. What's included and what agents spend beyond the plan. Honest breakdown.",
        h1="How Much Does Google Gemini Cost?",
        lead="Google's consumer AI plans are per-month with a free tier — and Google Workspace bundles change the math for businesses.",
        sections=[
            ("The plan structure",
             ["A free tier exists for light use; paid tiers add model access and higher limits.",
              "Workspace plans bundle AI features per seat.",
              "Verify current pricing — Google reshuffles these tiers."]),
            ("What people actually spend",
             ["Consumers: one plan, or free.",
              "Businesses: per-seat Workspace bundles.",
              "Developers: Gemini API billed per token, separate from any plan."]),
            ("The agent angle",
             ["Agents hit the Gemini API, not the consumer plan. Per-token API spend is the uncontrolled part."]),
        ],
        table=dict(
            headers=["Tier", "Type", "Watch"],
            rows=[
                ["Free", "Consumer", "Limits"],
                ["AI Pro", "Consumer monthly", "Model access"],
                ["AI Ultra/Advanced", "Power user", "Rate changes"],
                ["Workspace", "Per seat", "Bundle drift"],
            ],
        ),
        faqs=[
            ("Is Gemini free?",
             "There's a free tier. Paid tiers add access and limits. Verify current pricing."),
            ("How is Gemini API priced?",
             "Per token, by model generation — see the Gemini API cost page."),
            ("Can I control Gemini API spend from agents?",
             "Yes — category rules and per-agent caps apply to any API merchant."),
        ],
        related=[("Google Gemini API cost", "/cost-of/google-gemini-api-cost"), ("Google ADK integration", "/integrations/google-adk"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="perplexity-pro-cost",
        title="How Much Does Perplexity Cost? — Plans Explained",
        desc="Perplexity pricing: free, Pro, and Enterprise. What's included, what the API costs, and what agents add. Honest breakdown.",
        h1="How Much Does Perplexity Cost?",
        lead="Perplexity's consumer plans are per-month with a free tier — and its API is a separate, per-request bill that research agents drive hard.",
        sections=[
            ("The plan structure",
             ["A free tier with limited queries; Pro adds unlimited-ish usage and model choice.",
              "Enterprise adds org controls.",
              "Verify current pricing on Perplexity's site."]),
            ("What people actually spend",
             ["Consumers: one plan or free.",
              "Research teams: Pro seats + API usage.",
              "Agents: Perplexity API billed per request — the uncontrolled part."]),
            ("The agent angle",
             ["Research agents generate requests automatically. Per-request API spend is exactly what a firewall should cap."]),
        ],
        table=dict(
            headers=["Tier", "Type", "Watch"],
            rows=[
                ["Free", "Consumer", "Query limits"],
                ["Pro", "Consumer monthly", "Seat × team"],
                ["Enterprise", "Org", "Deploy scale"],
            ],
        ),
        faqs=[
            ("Is Perplexity free?",
             "There's a free tier with limits. Verify current pricing."),
            ("How is the Perplexity API priced?",
             "Per request, model-dependent — see the Perplexity API cost page."),
            ("Can I cap a research agent's Perplexity spend?",
             "Yes — per-agent ceilings and category rules."),
        ],
        related=[("Perplexity API cost", "/cost-of/perplexity-api-cost"), ("Research agents", "/use-cases/research-agents"), ("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs")],
    ),
]

GLOSSARY = [
    dict(
        slug="time-of-day-rule",
        term="Time-of-day rule",
        title="What is a Time-of-Day Rule? | sipi.bot Glossary",
        desc="A time-of-day rule restricts or flags agent spend outside business hours — the control that stops the 2 AM runaway.",
        h1="What is a Time-of-Day Rule?",
        lead="A time-of-day rule restricts or flags agent transactions outside configured hours — so unattended overnight activity has to pass a human first.",
        sections=[
            ("How it works",
             ["You define allowed hours (e.g. 9–18 local).",
              "Transactions outside the window are BLOCKED or FLAGGED for review.",
              "It's one of the six rule types a spend firewall enforces."]),
            ("Why it matters",
             ["The classic runaway happens at 2 AM, when no one is watching.",
              "Time-of-day rules turn 'unattended overnight' into 'requires approval.'"]),
        ],
        faqs=[
            ("Can legitimate overnight work pass?",
             "Yes — set the rule to FLAG instead of BLOCK: overnight purchases wait for a human, then proceed."),
            ("Which hours should I set?",
             "Your team's business hours. Adjust per agent — a global fleet may need multiple windows."),
        ],
        related=[("Six rule types", "/"), ("Overnight runaway scenario", "/scenarios/overnight-runaway-scenario"), ("Off-hours red flag", "/redflags/off-hours-billing-activity")],
    ),
    dict(
        slug="category-rule",
        term="Category rule",
        title="What is a Category Rule? | sipi.bot Glossary",
        desc="A category rule allows, caps, or flags spend by type — compute, data, SaaS, ads. How category budgets keep agents in their lane.",
        h1="What is a Category Rule?",
        lead="A category rule applies spend policy by type — compute, data, SaaS, ads, payments — so an agent can buy API credits but never wire money.",
        sections=[
            ("How it works",
             ["Each transaction carries a category.",
              "Rules set per-category ceilings, blocks, or flags.",
              "It's one of the six rule types a spend firewall enforces."]),
            ("Why it matters",
             ["Agents drift: a research agent starts buying compute.",
              "Category rules make the budget explicit per spend type."]),
        ],
        faqs=[
            ("What categories can I define?",
             "Whatever maps to your ledger: compute, data, SaaS, ads, payments, inference."),
            ("What happens when a category is capped?",
             "Transactions in that category over the cap are BLOCKED or FLAGGED — the agent stays in its lane."),
        ],
        related=[("Category drift scenario", "/scenarios/merchant-category-drift-scenario"), ("Category-based spending", "/glossary/category-based-spending"), ("Cost allocation template", "/templates/cost-allocation-template")],
    ),
    dict(
        slug="approval-queue",
        term="Approval queue",
        title="What is an Approval Queue? | sipi.bot Glossary",
        desc="An approval queue holds FLAGGED agent transactions for human review before money moves. How the human-in-the-loop control works.",
        h1="What is an Approval Queue?",
        lead="An approval queue is where FLAGGED transactions wait for a human — the control that keeps agents fast while material spend gets reviewed.",
        sections=[
            ("How it works",
             ["When a transaction crosses an approval threshold, it returns FLAGGED.",
              "It lands in the queue with amount, merchant, category, and the rule that fired.",
              "A human approves or denies; only then does the agent proceed."]),
            ("Why it matters",
             ["Hard blocks stop bad spend but also legitimate edge cases.",
              "The queue makes the middle path — review, not deny — fast and auditable."]),
        ],
        faqs=[
            ("Who reviews the queue?",
             "Whoever owns the budget — finance ops, platform lead, or team lead."),
            ("How long does approval take?",
             "As long as your team takes; the design target is minutes, not days."),
        ],
        related=[("Spend approval", "/glossary/spend-approval"), ("Approval workflow template", "/templates/approval-workflow"), ("False-positive scenario", "/scenarios/legit-workflow-false-positive-scenario")],
    ),
    dict(
        slug="merchant-blocklist",
        term="Merchant blocklist",
        title="What is a Merchant Blocklist? | sipi.bot Glossary",
        desc="A merchant blocklist hard-blocks specific vendors. How it complements the allowlist in a spend firewall.",
        h1="What is a Merchant Blocklist?",
        lead="A merchant blocklist is a deny-list of vendors an agent may never pay — the explicit complement to the allowlist's default-deny.",
        sections=[
            ("How it works",
             ["You list banned merchants (known-scam vendors, banned categories of vendors).",
              "Any transaction to a blocked merchant returns BLOCKED immediately.",
              "It's the counterpart to the merchant allowlist's default-deny."]),
            ("Allowlist vs blocklist",
             ["Allowlist: only approved vendors pass — everything else is blocked.",
              "Blocklist: everything passes unless explicitly banned.",
              "Most teams run the allowlist as primary and add blocklist entries for clarity."]),
        ],
        faqs=[
            ("Do I need both?",
             "The allowlist is the stronger default. The blocklist is useful when you want to permit most vendors but hard-ban a few."),
            ("Can I update it live?",
             "Yes — rules are managed via the dashboard and API."),
        ],
        related=[("Merchant blocklist template", "/templates/merchant-blocklist"), ("Merchant allowlist", "/glossary/merchant-allowlist"), ("Merchant allowlist template", "/templates/merchant-allowlist-template")],
    ),
]

FOR = [
    dict(
        slug="finops-teams",
        title="Agent Spend Control for FinOps Teams | sipi.bot",
        desc="FinOps teams: apply cost discipline to agent spend — allocation, unit economics, budgets, and enforcement.",
        h1="Agent Spend Control for FinOps Teams",
        lead="FinOps brought discipline to cloud cost. Agent spend is the next frontier — and it needs the same tools: allocation, budgets, and enforcement.",
        sections=[
            ("The FinOps problem",
             ["Agent spend doesn't fit the cloud cost model — it's transactions, not infrastructure.",
              "No allocation: one key, many teams, one blob bill.",
              "Cost tools report after; nothing gates before."]),
            ("What FinOps teams get",
             ["Per-agent allocation via the audit log — who spent what.",
              "Budgets enforced before the transaction, not reported after.",
              "Unit economics: cost per completed task from real data."]),
            ("How to deploy",
             ["Map agents to cost centers in sipi.bot rules; export the audit log to your FinOps stack."]),
        ],
        table=dict(
            headers=["FinOps practice", "sipi.bot equivalent"],
            rows=[
                ["Allocation", "Per-agent audit log"],
                ["Budgeting", "Per-agent ceilings"],
                ["Enforcement", "Pre-spend decisions"],
                ["Unit economics", "Cost per task data"],
            ],
        ),
        faqs=[
            ("Does this replace CloudZero/Vantage?",
             "No — they report infrastructure cost. sipi.bot enforces agent transaction spend. They compose."),
            ("Can I export decisions to my cost platform?",
             "Yes — the audit log is API-queryable."),
        ],
        related=[("sipi.bot vs CloudZero", "/vs/cloudzero"), ("sipi.bot vs Vantage", "/vs/vantage"), ("Cost allocation template", "/templates/cost-allocation-template")],
    ),
    dict(
        slug="heads-of-ai",
        title="AI Governance for Heads of AI | sipi.bot",
        desc="Heads of AI: org-wide agent spend governance — one policy, every agent, full audit. The control layer your AI strategy needs.",
        h1="Agent Spend Governance for Heads of AI",
        lead="You own the AI strategy — which means you own the risk. Agent spend is the risk that shows up on the invoice, not in the roadmap.",
        sections=[
            ("The head-of-AI problem",
             ["Teams ship agents fast; spend control lags behind.",
              "No org-wide view of what agents buy.",
              "An incident becomes a board conversation, not a tech issue."]),
            ("What heads of AI get",
             ["One governance layer across every agent and stack.",
              "Org-wide defaults with per-team delegation.",
              "A queryable audit trail for any question about agent spend."]),
            ("How to deploy",
             ["Set org defaults (caps, allowlists, approval thresholds), let teams tune their own, and review the audit log monthly."]),
        ],
        table=dict(
            headers=["Concern", "sipi.bot answer"],
            rows=[
                ["Org-wide policy", "Central rules + delegation"],
                ["Visibility", "Queryable audit log"],
                ["Risk", "Pre-spend enforcement"],
                ["Cost", "Flat $99/$499, unlimited evals"],
            ],
        ),
        faqs=[
            ("How fast can we roll out?",
             "Integration is one call or MCP registration per stack; defaults apply immediately."),
            ("Can teams keep autonomy?",
             "Yes — org defaults with per-team rule overrides."),
        ],
        related=[("CTOs", "/for/ctos"), ("Enterprise agent deployments", "/use-cases/enterprise-agent-deployments"), ("Agent spend governance guide", "/guides/agent-spend-governance")],
    ),
]

USE_CASES = [
    dict(
        slug="email-agents",
        title="Email Agent Spend Control | sipi.bot",
        desc="Email agents send on SendGrid, Resend, and outreach APIs — and loops multiply sends. Cap the spend, keep the campaigns.",
        h1="Spend Control for Email Agents",
        lead="Email agents draft, send, and follow up — each send hits a paid API. A retry loop on a broken campaign is a bill in the making.",
        sections=[
            ("Where email agents spend",
             ["Sending APIs (SendGrid, Resend, SES) per message.",
              "Enrichment and sequencing tools per contact.",
              "LLM inference for drafting at scale."]),
            ("The failure modes",
             ["A campaign loop re-sending the same batch multiplies per-message charges.",
              "Unknown vendors (new sending tools) bypass procurement.",
              "Overnight sequencing runs burn budget before review."]),
            ("Which rules to start with",
             ["Daily ceiling on sending API spend.",
              "Velocity limit on sends per window.",
              "Merchant allowlist for approved sending vendors."]),
        ],
        table=dict(
            headers=["Email spend", "Control"],
            rows=[
                ["Sending APIs", "Daily ceiling"],
                ["Loops", "Velocity limit"],
                ["Drafting inference", "Per-agent cap"],
                ["New tools", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Does this slow outbound velocity?",
             "No — ~5 ms per check; the agent keeps its pace, the budget stays enforced."),
            ("Can I cap per campaign?",
             "Yes — per-agent rules let each campaign run its own ceiling."),
        ],
        related=[("Sales development agents", "/use-cases/sales-development-agents"), ("Marketing sector", "/sectors/marketing"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="web-research-agents",
        title="Web Research Agent Spend Control | sipi.bot",
        desc="Research agents browse, scrape, and buy data — and the tool spend adds up. Cap it with per-agent budgets and allowlists.",
        h1="Spend Control for Web Research Agents",
        lead="Research agents hit search APIs, scraping tools, and paywalled data — dozens of paid calls per query. Volume is the cost driver.",
        sections=[
            ("Where research agents spend",
             ["Search and SERP APIs per query.",
              "Scraping and browser tools per page.",
              "Paywalled data and enrichment APIs.",
              "LLM inference for synthesis."]),
            ("The failure modes",
             ["A research loop re-running queries multiplies per-call charges.",
              "Agents buying from unknown data vendors — allowlist it.",
              "Parallel research agents compound spend during a single task."]),
            ("Which rules to start with",
             ["Per-agent daily ceiling.",
              "Velocity limit on query loops.",
              "Merchant allowlist for approved data vendors."]),
        ],
        table=dict(
            headers=["Research spend", "Control"],
            rows=[
                ["Search APIs", "Daily ceiling"],
                ["Scraping tools", "Per-agent cap"],
                ["Data purchases", "Merchant allowlist"],
                ["Inference", "Category budget"],
            ],
        ),
        faqs=[
            ("Can I budget per research project?",
             "Yes — per-agent rules let each project run its own ceiling."),
            ("What about paywalled data?",
             "Allowlist approved vendors; new ones go through FLAGGED review."),
        ],
        related=[("Research agents", "/use-cases/research-agents"), ("Perplexity API cost", "/cost-of/perplexity-api-cost"), ("AI research labs", "/use-cases/ai-research-labs")],
    ),
]

FAQ = [
    dict(
        slug="how-is-sipi-bot-different-from-an-llm-gateway",
        title="How Is sipi.bot Different From an LLM Gateway?",
        desc="LLM gateways route requests; sipi.bot decides whether spend may happen. The difference between traffic control and dollar control.",
        h1="How Is sipi.bot Different From an LLM Gateway?",
        lead="Gateways (LiteLLM, Portkey, Cloudflare AI Gateway) manage request flow — routing, caching, rate limits. sipi.bot manages money. Different layers, different jobs.",
        sections=[
            ("What gateways do",
             ["Route requests to models, cache responses, enforce rate limits.",
              "Optimize traffic and provider costs."]),
            ("Where gateways stop",
             ["Rate limits cap requests, not dollars — a loop under the limit can still cost $12,400.",
              "No merchant allowlist, category budgets, or approval queue."]),
            ("What sipi.bot does",
             ["Decides APPROVED, BLOCKED, or FLAGGED before the transaction settles.",
              "Caps, allowlists, velocity limits, time-of-day rules, approvals."]),
        ],
        faqs=[
            ("Do I need both?",
             "Yes — the standard stack is firewall → gateway → provider. sipi.bot decides, the gateway routes."),
            ("Is sipi.bot a gateway?",
             "No — it's a decision API and MCP tool. It doesn't proxy traffic."),
        ],
        related=[("sipi.bot vs LiteLLM", "/vs/litellm"), ("Best LLM API gateways", "/best/best-llm-api-gateways"), ("How spend control works", "/faq/how-ai-spend-control-works")],
    ),
    dict(
        slug="does-sipi-bot-work-with-stripe",
        title="Does sipi.bot Work With Stripe?",
        desc="Yes — sipi.bot sits in front of Stripe for agent payments: evaluate first, settle on Stripe. How the integration works.",
        h1="Does sipi.bot Work With Stripe?",
        lead="Yes. Agents that pay through Stripe call sipi.bot first; approved transactions settle normally on your existing Stripe account.",
        sections=[
            ("How it works",
             ["The agent proposes a payment → sipi.bot evaluates it against your rules → APPROVED, BLOCKED, or FLAGGED.",
              "Approved transactions proceed through Stripe as usual.",
              "sipi.bot never holds funds — Stripe remains your processor."]),
            ("What it adds",
             ["Per-agent budgets, merchant allowlists, velocity limits, and an approval queue — none of which Stripe provides for agent spend."]),
        ],
        faqs=[
            ("Does sipi.bot replace Stripe?",
             "No — it's a decision layer in front of it. Your rail still moves the money."),
            ("Is this the same as Stripe Radar?",
             "No — Radar detects card fraud. sipi.bot enforces your agent spend policy. See the comparison."),
        ],
        related=[("sipi.bot vs Stripe Billing", "/vs/stripe-billing"), ("sipi.bot vs Stripe Radar", "/vs/stripe-radar"), ("Stripe integration", "/integrations/stripe")],
    ),
]

BEST = [
    dict(
        slug="best-ai-spend-policy-tools",
        title="Best AI Spend Policy Tools 2026 — Honest List",
        desc="The best tools for writing and enforcing AI spend policies: templates, policy engines, and firewalls. Criteria-based and honest.",
        h1="Best AI Spend Policy Tools 2026",
        lead="A spend policy is only as good as its enforcement. Here are the tools that help write one — and the one that makes it real.",
        sections=[
            ("Write the policy",
             ["Templates and playbooks (like sipi.bot's own) that structure budgets, vendors, and approvals.",
              "Internal wiki/governance docs for org-wide policy."]),
            ("Enforce it",
             ["sipi.bot — turns the policy into deterministic rules: caps, allowlists, velocity limits, approval queue.",
              "Provider limits and gateway budgets cover single-vendor slices."]),
            ("The honest gap",
             ["Most 'policy tools' produce documents, not enforcement. The firewall is where the policy becomes a decision."]),
        ],
        table=dict(
            headers=["Tool", "Writes policy", "Enforces"],
            rows=[
                ["Templates", "Yes", "No"],
                ["Wiki/docs", "Yes", "No"],
                ["Provider limits", "Partial", "Per-provider"],
                ["sipi.bot", "Yes", "Yes — every transaction"],
            ],
        ),
        faqs=[
            ("What's the minimum viable policy?",
             "A cap, an allowlist, and an owner per agent. Three rules."),
            ("How do I start?",
             "Use the spend policy template, then turn it into rules in the firewall."),
        ],
        related=[("Agent spend policy template", "/templates/agent-spend-policy-template"), ("How to create a spend policy", "/how-to/how-to-create-a-spend-policy"), ("Spend policy glossary", "/glossary/spend-policy")],
    ),
    dict(
        slug="best-agent-cost-dashboards",
        title="Best Agent Cost Dashboards 2026 — Honest List",
        desc="The best dashboards for agent cost: provider consoles, observability platforms, and the audit-log dashboard. Honest comparison.",
        h1="Best Agent Cost Dashboards 2026",
        lead="You need to SEE agent spend before you can control it. These dashboards show different slices — from per-provider consoles to transaction-level audit logs.",
        sections=[
            ("Provider consoles",
             ["OpenAI, Anthropic, and cloud usage dashboards — precise per-provider numbers."]),
            ("Observability platforms",
             ["Langfuse, Helicone, LangSmith — cost per request, traced to runs."]),
            ("The audit-log layer",
             ["sipi.bot's dashboard + queryable audit log — every decision, rule, and amount, including BLOCKED attempts."]),
        ],
        table=dict(
            headers=["Dashboard", "Shows", "Missing"],
            rows=[
                ["Provider consoles", "Per-provider usage", "Cross-provider view"],
                ["Observability", "Per-request cost", "Pre-spend decisions"],
                ["sipi.bot", "Every decision", "Full traces"],
            ],
        ),
        faqs=[
            ("Which dashboard should I start with?",
             "Provider consoles for the bill, plus the audit log for what agents actually did."),
            ("Can I export the audit log?",
             "Yes — API-queryable, timestamped."),
        ],
        related=[("AI spend monitoring", "/best/ai-spend-monitoring"), ("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs"), ("Agent audit trail", "/glossary/agent-audit-trail")],
    ),
]

TEMPLATES = [
    dict(
        slug="agent-budget-template",
        title="Agent Budget Template",
        desc="A copy-paste agent budget template: ceiling, vendors, categories, approvals, owner. Turn it into firewall rules in minutes.",
        h1="Agent Budget Template",
        lead="Every agent gets a budget before it gets a key. This template structures the number — and maps to rules.",
        sections=[
            ("The template",
             ["Agent: [NAME] — purpose: [WHAT IT DOES].",
              "Daily ceiling: [$] | Monthly ceiling: [$].",
              "Approved vendors: [LIST].",
              "Categories: [allowed] / [blocked].",
              "Approval threshold: [$].",
              "Owner & approver: [NAME]."]),
            ("Turning it into rules",
             ["Ceiling → daily cap. Vendors → allowlist. Categories → category rules. Threshold → approval flag."]),
        ],
        code=dict(
            title="One agent, four rules",
            lang="json",
            body='{\n  "daily_ceiling": 500,\n  "merchant_allowlist": ["openai.com", "data-vendor.com"],\n  "category_rule": {"data": "allow", "compute": "block"},\n  "approval_threshold": {"over": 200, "action": "flag"}\n}',
            caption="The budget becomes enforceable decisions.",
        ),
        faqs=[
            ("What's a good starting ceiling?",
             "Whatever the task legitimately costs × 1.5 — tight enough to catch runaways, loose enough to work."),
            ("Who sets it?",
             "The engineer shipping the agent, reviewed by the budget owner."),
        ],
        related=[("Agent onboarding spend brief", "/templates/agent-onboarding-spend-brief"), ("Budget sizing calculator", "/calculators/budget-sizing-calculator"), ("How to set AI agent budget", "/faq/how-to-set-ai-agent-budget")],
    ),
    dict(
        slug="vendor-risk-assessment-template",
        title="AI Vendor Risk Assessment Template",
        desc="A template for assessing vendors before agents can pay them: reputation, pricing model, data handling, and spend risk.",
        h1="AI Vendor Risk Assessment Template",
        lead="Before a vendor joins the allowlist, it gets a risk pass. This template structures the review.",
        sections=[
            ("The assessment",
             ["Vendor: [NAME] | Category: [TYPE].",
              "Reputation: [history, reviews, source].",
              "Pricing model: [per-call, per-token, subscription] — and overage behavior.",
              "Data handling: [what they receive, retention].",
              "Spend risk: [worst-case monthly if agent loops].",
              "Decision: [APPROVE / CONDITIONAL / REJECT]."]),
            ("Turning it into rules",
             ["APPROVE → allowlist with limits. CONDITIONAL → allowlist with lower caps. REJECT → absent from the allowlist (blocked by default)."]),
        ],
        code=dict(
            title="Risk → rule mapping",
            lang="text",
            body="APPROVE      -> allowlist + standard limits\nCONDITIONAL  -> allowlist + reduced caps + FLAG threshold\nREJECT       -> not on allowlist (BLOCKED by default)",
            caption="The assessment becomes enforcement.",
        ),
        faqs=[
            ("Who does the assessment?",
             "Procurement or the budget owner — whoever owns vendor relationships."),
            ("How often to reassess?",
             "Annually, or when pricing/behavior changes."),
        ],
        related=[("Vendor onboarding policy", "/templates/vendor-onboarding-policy"), ("Procurement teams", "/for/procurement-teams"), ("Merchant allowlist template", "/templates/merchant-allowlist-template")],
    ),
]

# Checklists live in public/ (slash-canonical — matching _serve_static 301s).
CHECKLISTS = [
    dict(
        slug="spend-firewall-rfp-checklist",
        title="Spend Firewall RFP Checklist",
        desc="A checklist for evaluating spend-firewall vendors: decision latency, rule types, audit, pricing, and deployment.",
        h1="Spend Firewall RFP Checklist",
        lead="Buying a spend firewall? Ask these questions — the answers separate a decision engine from a dashboard.",
        sections=[
            ("The checklist",
             ["1. Decision path: deterministic rules or model-based? (Deterministic can't be injected.)",
              "2. Latency: what's the p95 decision time? (~5 ms target.)",
              "3. Rule types: caps, velocity, allowlists, categories, time-of-day, approvals?",
              "4. Audit: is every decision logged with the rule that fired?",
              "5. Pricing: per-call metering or flat? Any overage tier?",
              "6. Deployment: hosted, self-host, or both? License?",
              "7. Integration: HTTP, MCP, CLI — and wrappers for your stack?",
              "8. Rail support: does it sit in front of x402, AP2, AgentKit?"]),
            ("How to score",
             ["Weight by your priorities — for most teams: deterministic path, flat pricing, audit log."]),
        ],
        faqs=[
            ("Why does deterministic matter?",
             "A model-based decision path can be argued with or injected; rules can't."),
            ("What's the most underrated item?",
             "The audit log — it's what answers questions six months later."),
        ],
        related=[("Agent spend firewall deployment", "/checklists/agent-spend-firewall-deployment"), ("Pricing", "/pricing"), ("Eval report", "/eval-report/")],
    ),
    dict(
        slug="agent-vendor-due-diligence-checklist",
        title="Agent Vendor Due Diligence Checklist",
        desc="A checklist for vetting vendors before agents can pay them: reputation, pricing, data, failure modes, and worst-case spend.",
        h1="Agent Vendor Due Diligence Checklist",
        lead="An agent can't be careful about vendors — you have to be, in advance. This checklist makes it systematic.",
        sections=[
            ("The checklist",
             ["1. Reputation: who runs it, what's the track record?",
              "2. Pricing model: per-call, per-token, subscription — and overage behavior.",
              "3. Failure modes: what happens when their API errors? Does your agent retry?",
              "4. Data handling: what do they receive, how long is it kept?",
              "5. Worst-case spend: if your agent loops, what's the monthly damage?",
              "6. Contract: cancellation terms, SLAs, support.",
              "7. Offboarding: how fast can you stop paying?"]),
            ("Turning it into rules",
             ["Approved → allowlist with limits. Risky → conditional allowlist with caps. Unknown → not allowlisted."]),
        ],
        faqs=[
            ("How deep should diligence go?",
             "Proportional to spend — a $10/mo API gets a light pass; a major data vendor gets the full review."),
            ("Who maintains the list?",
             "Procurement or the budget owner, with the allowlist as the enforcement point."),
        ],
        related=[("Vendor risk assessment template", "/templates/vendor-risk-assessment-template"), ("Vendor onboarding policy", "/templates/vendor-onboarding-policy"), ("Merchant allowlist", "/glossary/merchant-allowlist")],
    ),
    dict(
        slug="ai-spend-governance-checklist",
        title="AI Spend Governance Checklist",
        desc="An org-level checklist for AI spend governance: policy, defaults, approvals, audit, and review cadence.",
        h1="AI Spend Governance Checklist",
        lead="Governance is the org layer on top of the firewall. This checklist covers the whole program.",
        sections=[
            ("The checklist",
             ["1. Policy: written spend policy with owners?",
              "2. Defaults: do new agents inherit caps and allowlists?",
              "3. Approvals: who reviews FLAGGED transactions, how fast?",
              "4. Vendors: is there an allowlist process with due diligence?",
              "5. Audit: is every decision logged and reviewable?",
              "6. Review: is there a monthly spend review with rule tuning?",
              "7. Incidents: does every runaway produce a report and a rule?",
              "8. Education: do teams know the policy?"]),
        ],
        faqs=[
            ("What's the first item to implement?",
             "Defaults — they cover the ungoverned gap between deploy and policy."),
            ("How often should the program be reviewed?",
             "Monthly for spend and rules; quarterly for the policy itself."),
        ],
        related=[("Weekly spend review template", "/templates/weekly-spend-review-template"), ("Agent incident report", "/templates/agent-incident-report"), ("Heads of AI", "/for/heads-of-ai")],
    ),
]

# --- hub metadata (repo-root hubs patched via patch_hub; checklists hub in
# public/ is patched separately by the generator) ---------------------------
