"""Round 22 pSEO data — sipi.bot (2026-08-08).

Content rules (from CLAUDE.md + product truth):
- Honest copy: sipi.bot does NOT win every dimension. Every comparison page
  has a "where <tool> wins" section.
- No fabricated stats, testimonials, urgency, or tiers. Verifiable facts only:
  $99/mo Team / $499/mo Business, unlimited evals, MIT core, ~5 ms decisions,
  3 decisions (APPROVED/BLOCKED/FLAGGED), 6 rule types, HTTP+MCP+CLI,
  x402/AP2/AgentKit compatible, queryable audit log, no custody, 53/53 evals,
  free self-host (MIT), "wrongly-approved month is free" guarantee.
- Pricing answers match the live /pricing page. Benchmark figures that are
  derived (cache savings, context costs) are clearly labeled as approximations
  with "verify current pricing" caveats.
"""

PRICING_QUESTIONS = [
    dict(
        slug="is-sipi-bot-free",
        title="Is sipi.bot Free? — Pricing Explained",
        desc="Is sipi.bot free? The MIT core is free to self-host forever; hosted plans are flat-rate. What's free, what's paid, and how to start without paying.",
        h1="Is sipi.bot Free?",
        lead="Short answer: the core is free — it's MIT-licensed open source and you can self-host it forever. The hosted plans are what cost money, and they're flat-rate.",
        sections=[
            ("What's free",
             ["The entire decision engine — MIT-licensed on GitHub, free to self-host forever.",
              "The playground: run live transaction checks without a key or signup.",
              "The full self-host guide and open-source documentation."]),
            ("What's paid",
             ["Hosted plans (Team $99/mo, Business $499/mo) add the live dashboard, the managed approval queue, and timestamped audit-log storage.",
              "Both hosted plans are flat-rate with unlimited transaction evaluations — no per-call fees, no metering, no overage tiers."]),
            ("How to start for $0",
             ["Self-host the MIT core, or use the playground to see the decision engine live. When you need the dashboard and approval workflow, the paid plans are flat and predictable."]),
        ],
        table=dict(
            headers=["Option", "Cost", "Includes"],
            rows=[
                ["Self-host (MIT core)", "$0 forever", "Decision engine, HTTP/MCP/CLI"],
                ["Playground", "$0", "Live checks, no signup"],
                ["Team", "$99/mo", "Dashboard, approval queue, audit storage"],
                ["Business", "$499/mo", "Everything in Team, org features"],
            ],
        ),
        faqs=[
            ("Is there a hosted free tier?",
             "No — hosted is flat-rate paid. But the self-host core and the playground are genuinely free, so you can evaluate the product before paying."),
            ("Are there per-call fees?",
             "No. Both hosted plans include unlimited transaction evaluations."),
            ("Is the open-source core the full product?",
             "It's the full decision engine. Hosted plans add the operational layer: dashboard, approval queue, and stored audit log."),
        ],
        related=[("How much does sipi.bot cost", "/pricing-questions/how-much-does-sipi-bot-cost"), ("Self-host guide", "/self-hosted/"), ("Pricing", "/pricing")],
    ),
    dict(
        slug="how-much-does-sipi-bot-cost",
        title="How Much Does sipi.bot Cost? — Pricing Breakdown",
        desc="sipi.bot pricing: $99/mo Team, $499/mo Business, unlimited evaluations, no per-call fees. Plus a free MIT self-host core. Full breakdown.",
        h1="How Much Does sipi.bot Cost?",
        lead="Two flat-rate hosted plans, unlimited evaluations on both, and a free MIT-licensed core you can self-host. There is no metering, no per-call fee, and no overage tier.",
        sections=[
            ("The hosted plans",
             ["Team: $99/month — the dashboard, managed approval queue, and timestamped audit log storage.",
              "Business: $499/month — everything in Team for larger orgs.",
              "Both include unlimited transaction evaluations."]),
            ("The free option",
             ["The open-source core is MIT-licensed and free to self-host forever. You only pay when you want the hosted operational layer."]),
            ("What you're not paying for",
             ["No per-call fees, no metering, no overage tiers, no surprise line items. The price is the price."]),
        ],
        table=dict(
            headers=["Plan", "Price", "Evaluations", "Overage"],
            rows=[
                ["Self-host (MIT)", "$0", "Unlimited", "None"],
                ["Team", "$99/mo", "Unlimited", "None"],
                ["Business", "$499/mo", "Unlimited", "None"],
            ],
        ),
        faqs=[
            ("Is there a per-transaction fee?",
             "No. Unlimited transaction evaluations on both hosted plans."),
            ("Do I pay for the open-source core?",
             "No — it's MIT-licensed and free forever."),
            ("What's the difference between Team and Business?",
             "Team is $99/mo for teams getting started; Business is $499/mo for larger organizations. Both have unlimited evaluations."),
        ],
        related=[("Is sipi.bot free", "/pricing-questions/is-sipi-bot-free"), ("Is sipi.bot worth it", "/pricing-questions/is-sipi-bot-worth-it"), ("Pricing", "/pricing")],
    ),
    dict(
        slug="is-sipi-bot-worth-it",
        title="Is sipi.bot Worth It? — An Honest Cost-Benefit",
        desc="Is a spend firewall worth $99/mo? Compare it to the cost of one runaway agent incident, what you get, and how to evaluate it free.",
        h1="Is sipi.bot Worth It?",
        lead="Worth it if your agents can spend money — and they can. $99/mo is one documented runaway-agent incident's rounding error. Here's the honest math.",
        sections=[
            ("The cost side",
             ["Team is $99/month with unlimited evaluations. Self-hosting the MIT core is free."]),
            ("The risk side",
             ["The public incident database documents real runaway events — from hundreds to millions of dollars. The founder story is a $12,400 single night.",
              "If your agents hold payment methods, the question isn't whether spend control pays for itself — it's how quickly."]),
            ("The honest caveat",
             ["If your agents can't spend money at all (no payment rails, no paid tools), you may not need it yet. The moment they can, you do.",
              "Evaluate free first: self-host the core or run the playground, then decide."]),
        ],
        table=dict(
            headers=["Scenario", "Without firewall", "With sipi.bot"],
            rows=[
                ["Agent with payment rail", "Incident risk", "$99/mo, unlimited evals"],
                ["Agents with paid tools", "Unreviewed spend", "Caps + approvals"],
                ["No spend-capable agents", "No exposure", "Not needed yet"],
            ],
        ),
        faqs=[
            ("What does $99/mo buy exactly?",
             "Unlimited evaluations, the dashboard, managed approval queue, and stored audit log — plus the entire deterministic decision engine."),
            ("Can I try it before paying?",
             "Yes — the playground runs live checks free, and the MIT core self-hosts free."),
            ("What's the cheapest real protection?",
             "Self-host the free core and enforce two rules: a per-transaction cap and a velocity limit. That covers the two most common runaway patterns."),
        ],
        related=[("Runaway agent cost", "/benchmarks/agent-runaway-cost-average"), ("Incident database", "/incidents/"), ("The $12,400 story", "/blog/12400-story-eval-gym")],
    ),
    dict(
        slug="does-sipi-bot-have-a-free-tier",
        title="Does sipi.bot Have a Free Tier?",
        desc="sipi.bot free tier explained: free MIT self-host, free playground, no hosted free tier. What you can use for $0.",
        h1="Does sipi.bot Have a Free Tier?",
        lead="There are two genuinely free ways to use sipi.bot — self-host the MIT core, or run live checks in the playground. There's no hosted free tier.",
        sections=[
            ("The free options",
             ["Self-host: the MIT-licensed core runs your rules forever at $0.",
              "Playground: evaluate any transaction live — no key, no signup."]),
            ("What's not free",
             ["Hosted plans are flat-rate: Team $99/mo, Business $499/mo. They add the dashboard, approval queue, and stored audit log."]),
            ("Which should you pick?",
             ["Engineers who want the control plane in their own infra: self-host. Teams that want the dashboard and approval workflow without ops: hosted."]),
        ],
        table=dict(
            headers=["Free option", "What you get", "Limits"],
            rows=[
                ["Self-host (MIT core)", "Full decision engine", "You run the infra"],
                ["Playground", "Live transaction checks", "No dashboard/rules UI"],
            ],
        ),
        faqs=[
            ("Is the playground really free?",
             "Yes — live checks with no signup and no key."),
            ("Can I move from self-host to hosted later?",
             "Yes — same rules model, same API. Hosted adds the operational layer."),
            ("Does self-host have all six rule types?",
             "Yes — the full deterministic rule engine is in the MIT core."),
        ],
        related=[("Is sipi.bot free", "/pricing-questions/is-sipi-bot-free"), ("Self-host guide", "/self-hosted/"), ("Playground", "/playground/")],
    ),
    dict(
        slug="can-i-self-host-sipi-bot",
        title="Can I Self-Host sipi.bot?",
        desc="Yes — sipi.bot's core is MIT-licensed and free to self-host forever. What self-hosting includes, what it doesn't, and how to start.",
        h1="Can I Self-Host sipi.bot?",
        lead="Yes. The core is MIT-licensed open source on GitHub, free to self-host forever. The hosted plans add the operational layer on top.",
        sections=[
            ("What self-hosting includes",
             ["The complete deterministic decision engine — all six rule types, HTTP API, MCP tool, CLI.",
              "Your rules, your infrastructure, no vendor in the loop."]),
            ("What it doesn't include",
             ["The hosted dashboard, the managed approval queue, and timestamped audit-log storage are part of the paid plans.",
              "You're responsible for uptime, storage, and your own approval UI."]),
            ("How to start",
             ["Clone the repo, follow the self-host guide, point your agents at your instance. The API contract is the same either way."]),
        ],
        table=dict(
            headers=["Capability", "Self-host", "Hosted"],
            rows=[
                ["Decision engine", "Yes (MIT)", "Yes"],
                ["HTTP / MCP / CLI", "Yes", "Yes"],
                ["Dashboard", "Build your own", "Included"],
                ["Approval queue", "Wire your own", "Managed"],
                ["Audit log storage", "Your DB", "Included"],
            ],
        ),
        faqs=[
            ("Is self-hosting really free?",
             "Yes — MIT license, no fees, no gating."),
            ("Can self-host handle production load?",
             "It's the same engine the hosted service runs; capacity is up to your infrastructure."),
            ("Do I get updates?",
             "The repo is public — pull updates like any open-source project."),
        ],
        related=[("Self-host guide", "/self-hosted/"), ("Is sipi.bot free", "/pricing-questions/is-sipi-bot-free"), ("Open source", "https://github.com/kindrat86/sipi-bot")],
    ),
    dict(
        slug="does-sipi-bot-charge-per-api-call",
        title="Does sipi.bot Charge Per API Call?",
        desc="No — sipi.bot is flat-rate with unlimited transaction evaluations. No per-call fees, no metering, no overage tiers. Here's the pricing model.",
        h1="Does sipi.bot Charge Per API Call?",
        lead="No. Both hosted plans include unlimited transaction evaluations. sipi.bot is the one bill in your stack that can't surprise you.",
        sections=[
            ("The pricing model",
             ["Team: $99/month, unlimited evaluations.",
              "Business: $499/month, unlimited evaluations.",
              "No per-call fees, no metering, no overage tiers."]),
            ("Why flat-rate matters for agents",
             ["Agents generate unpredictable call volume — retries, fan-out, spikes. Metered pricing punishes exactly the workloads a firewall exists to stop.",
              "Flat-rate means a runaway agent costs you nothing extra on the firewall bill."]),
            ("The free option",
             ["Self-host the MIT core and evaluations are free forever by definition."]),
        ],
        table=dict(
            headers=["Plan", "Evaluations", "Metering", "Overage"],
            rows=[
                ["Self-host", "Unlimited", "None", "None"],
                ["Team $99/mo", "Unlimited", "None", "None"],
                ["Business $499/mo", "Unlimited", "None", "None"],
            ],
        ),
        faqs=[
            ("What counts as an evaluation?",
             "Each call to the transaction decision endpoint — whether it returns APPROVED, BLOCKED, or FLAGGED."),
            ("What if my agents generate millions of calls?",
             "Unlimited evaluations — that's the point of flat-rate."),
            ("Is there a free trial?",
             "The playground is free to try, and the MIT core is free to self-host."),
        ],
        related=[("How much does sipi.bot cost", "/pricing-questions/how-much-does-sipi-bot-cost"), ("Pricing", "/pricing"), ("Is sipi.bot worth it", "/pricing-questions/is-sipi-bot-worth-it")],
    ),
    dict(
        slug="sipi-bot-vs-building-your-own",
        title="sipi.bot vs Building Your Own Spend Control",
        desc="Should you build spend control in-house or use sipi.bot? Honest build-vs-buy comparison: open core, engineering cost, and what you actually save.",
        h1="sipi.bot vs Building Your Own",
        lead="Because the core is open source, 'build your own' is a real option — and an honest one. Here's what building actually costs and what sipi.bot's paid plans save you.",
        sections=[
            ("What building your own means",
             ["You can fork the MIT core and build your own control plane: rules UI, approval queue, audit storage, multi-tenant key management.",
              "That's real engineering — weeks to months of work, plus ongoing maintenance."]),
            ("What you get for building",
             ["Total control over your stack, no vendor dependency, and a system tailored to your org."]),
            ("What sipi.bot's plans buy you",
             ["The dashboard, managed approval queue, and stored audit log — already built, already maintained, flat-rate.",
              "The alternative math: one engineer-month costs more than a year of Business."]),
        ],
        table=dict(
            headers=["Dimension", "Build your own", "sipi.bot hosted"],
            rows=[
                ["Engine time", "Weeks–months", "None"],
                ["Rules engine", "Fork or write", "Included"],
                ["Approval queue", "Build + maintain", "Managed"],
                ["Audit storage", "Build + maintain", "Included"],
                ["Cost", "Engineering time", "Flat $99/$499"],
            ],
        ),
        faqs=[
            ("Is forking the core allowed?",
             "Yes — it's MIT licensed."),
            ("When does building make sense?",
             "When you need deep custom integration, are a platform company, or already have the team and the time."),
            ("When does hosted make sense?",
             "When you want protection now, flat-rate, without owning the control plane."),
        ],
        related=[("Self-host guide", "/self-hosted/"), ("Is sipi.bot worth it", "/pricing-questions/is-sipi-bot-worth-it"), ("Open source", "https://github.com/kindrat86/sipi-bot")],
    ),
    dict(
        slug="what-happens-if-sipi-bot-makes-a-mistake",
        title="What If sipi.bot Wrongly Approves a Spend?",
        desc="sipi.bot's guarantee: if it wrongly approves a spend that breaks an active rule, that month is free. How decisions stay reviewable.",
        h1="What If sipi.bot Makes a Mistake?",
        lead="If sipi.bot green-lights a spend that breaks one of your active rules, that month's subscription is free. Every decision is logged, so mistakes are reviewable — and the guarantee is real.",
        sections=[
            ("The guarantee",
             ["A wrongly approved transaction that violates an active rule means the month is free. That's the product promise."]),
            ("Why mistakes are rare",
             ["The decision path is a deterministic rules engine — no model in the loop to hallucinate or be injected.",
              "A rule either matches the transaction or it doesn't. Deterministic means reviewable."]),
            ("How to verify any decision",
             ["Every decision is written to the audit log with the rule that fired, the amount, and the reason — queryable via API and dashboard."]),
        ],
        table=dict(
            headers=["Question", "Answer"],
            rows=[
                ["Wrongly approved spend", "That month is free"],
                ["Decision path", "Deterministic rules, no model"],
                ["Every decision logged", "Rule, amount, reason"],
                ["Audit access", "API + dashboard"],
            ],
        ),
        faqs=[
            ("What counts as 'wrongly approved'?",
             "An approval that violates one of your active rules — the exact case the firewall exists to prevent."),
            ("Can I see why a decision was made?",
             "Yes — the audit log records the rule that fired and the reason for every decision."),
            ("Is the guarantee on self-host too?",
             "The guarantee applies to hosted subscriptions; self-host is your own infrastructure and rules."),
        ],
        related=[("Audit trail", "/glossary/agent-audit-trail"), ("How spend control works", "/faq/how-ai-spend-control-works"), ("Pricing", "/pricing")],
    ),
]

VS = [
    dict(
        slug="kong-ai-gateway",
        name="Kong AI Gateway",
        title="sipi.bot vs Kong AI Gateway — Enterprise Gateway vs Spend Firewall",
        desc="Kong AI Gateway routes and rate-limits AI traffic at the enterprise edge. sipi.bot enforces spend before money moves. Compare scope.",
        h1="sipi.bot vs Kong AI Gateway",
        lead="Kong AI Gateway brings AI traffic control to Kong's enterprise gateway. sipi.bot is a pre-spend firewall. One manages request flow; the other governs money.",
        sections=[
            ("What Kong AI Gateway does well",
             ["Enterprise-grade API gateway: routing, rate limits, auth, and AI-specific plugins.",
              "Policy at the edge for LLM traffic across your fleet.",
              "The right choice when you're already on Kong."]),
            ("Where it falls short",
             ["Rate limits cap requests, not dollars — a loop under the limit can still cost $12,400.",
              "No merchant allowlist, category budgets, or approval queue for agent spend.",
              "It's infrastructure; it doesn't decide whether a purchase may happen."]),
            ("Where sipi.bot wins",
             ["Dollar-level decisions: APPROVED, BLOCKED, or FLAGGED before settlement.",
              "Merchant allowlists, category rules, velocity limits, time-of-day rules.",
              "Approval workflow for edge cases.",
              "~5 ms, no model call."]),
            ("When to use which",
             ["Kong for traffic policy; sipi.bot for spend policy. They compose: firewall first, then route."]),
        ],
        table=dict(
            headers=["Dimension", "Kong AI Gateway", "sipi.bot"],
            rows=[
                ["Layer", "Traffic gateway", "Transaction decision layer"],
                ["Controls", "Rate limits, routing", "Caps, allowlists, approvals"],
                ["Unit", "Requests", "Dollars"],
                ["Decision", "Route / throttle", "APPROVED / BLOCKED / FLAGGED"],
                ["Deploy", "Edge/self-host", "Hosted or MIT self-host"],
            ],
        ),
        faqs=[
            ("Can Kong's rate limits stop a runaway bill?",
             "They cap volume, not value. A retry loop under the rate limit still racks up spend. sipi.bot caps the dollars."),
            ("Do they overlap?",
             "Minimally — Kong routes and throttles; sipi.bot decides. Most production stacks can run both."),
            ("Is sipi.bot a gateway?",
             "No — it's a decision API and MCP tool. It doesn't proxy traffic."),
        ],
        related=[("Best LLM API gateways", "/best/best-llm-api-gateways"), ("sipi.bot vs Cloudflare AI Gateway", "/vs/cloudflare-ai-gateway"), ("sipi.bot vs LiteLLM", "/vs/litellm")],
    ),
    dict(
        slug="vercel-ai-gateway",
        name="Vercel AI Gateway",
        title="sipi.bot vs Vercel AI Gateway — Caching vs Spend Enforcement",
        desc="Vercel AI Gateway caches and rate-limits AI calls for the AI SDK. sipi.bot blocks runaway agent spend. Compare and compose.",
        h1="sipi.bot vs Vercel AI Gateway",
        lead="Vercel AI Gateway adds caching, rate limits, and observability to AI SDK traffic. sipi.bot is a pre-spend firewall. Different layers, different jobs.",
        sections=[
            ("What Vercel AI Gateway does well",
             ["Drop-in for Vercel AI SDK apps: caching, rate limits, observability.",
              "Great developer experience for Next.js teams."]),
            ("Where it falls short",
             ["Optimizes request flow — it doesn't decide whether a purchase is within policy.",
              "No dollar-level controls: merchant allowlists, category budgets, approval queues."]),
            ("Where sipi.bot wins",
             ["Pre-spend APPROVED / BLOCKED / FLAGGED.",
              "Money-level policy across every merchant.",
              "Approval workflow for edge cases.",
              "Deterministic, ~5 ms."]),
            ("When to use which",
             ["AI Gateway for traffic; sipi.bot for spend. They slot into the same stack without conflict."]),
        ],
        table=dict(
            headers=["Dimension", "Vercel AI Gateway", "sipi.bot"],
            rows=[
                ["Layer", "AI traffic gateway", "Spend decision layer"],
                ["Controls", "Cache, rate limits", "Caps, allowlists, approvals"],
                ["Unit", "Requests", "Dollars"],
                ["Decision", "Route / cache", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Do Vercel AI Gateway and sipi.bot compete?",
             "No — one optimizes traffic, the other enforces spend. Teams use both."),
            ("Does sipi.bot integrate with the AI SDK?",
             "Yes — there's a Vercel AI SDK integration plus an MCP tool."),
        ],
        related=[("Vercel AI SDK", "/integrations/vercel-ai-sdk"), ("Best LLM API gateways", "/best/best-llm-api-gateways"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
    dict(
        slug="openllmetry",
        name="OpenLLMetry",
        title="sipi.bot vs OpenLLMetry — Open-Source Tracing vs Spend Firewall",
        desc="OpenLLMetry traces LLM apps for free. sipi.bot blocks runaway agent spend. Observability vs enforcement — see where each wins.",
        h1="sipi.bot vs OpenLLMetry",
        lead="OpenLLMetry is open-source LLM observability. sipi.bot is a pre-spend firewall. One shows you the traces; the other holds the gate.",
        sections=[
            ("What OpenLLMetry does well",
             ["Free, open-source OpenTelemetry-based tracing for LLM apps.",
              "Solid spans, tokens, and cost metadata per request.",
              "Great starting point for observability."]),
            ("Where it falls short",
             ["It observes; it doesn't decide. No pre-spend enforcement.",
              "No merchant allowlist, approval queue, or rule engine."]),
            ("Where sipi.bot wins",
             ["Deterministic pre-spend decisions.",
              "Dollar-level controls across merchants.",
              "Approval workflow for edge cases."]),
            ("When to use which",
             ["OpenLLMetry for tracing; sipi.bot for enforcement. Complementary."]),
        ],
        table=dict(
            headers=["Dimension", "OpenLLMetry", "sipi.bot"],
            rows=[
                ["Role", "Tracing & observability", "Pre-spend enforcement"],
                ["Cost", "Free / OSS", "MIT core free; hosted $99+"],
                ["When it acts", "After requests", "Before transactions"],
                ["Controls", "Spans, metrics", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Are they competitors?",
             "No — tracing and enforcement are different layers. Run both."),
            ("Is sipi.bot open source too?",
             "Yes — the core is MIT-licensed, like OpenLLMetry."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs Traceloop", "/vs/traceloop"), ("AI spend monitoring", "/best/ai-spend-monitoring")],
    ),
    dict(
        slug="traceloop",
        name="Traceloop",
        title="sipi.bot vs Traceloop — LLM Observability vs Spend Firewall",
        desc="Traceloop traces LLM apps and manages quality. sipi.bot blocks runaway agent spend. Compare scope and how they compose.",
        h1="sipi.bot vs Traceloop",
        lead="Traceloop is an LLM observability and evaluation platform. sipi.bot is a pre-spend firewall. One gives the picture; the other holds the gate.",
        sections=[
            ("What Traceloop does well",
             ["LLM observability: traces, evaluations, and cost tracking.",
              "Quality management for LLM outputs.",
              "Good for teams maturing their LLM ops."]),
            ("Where it falls short",
             ["Post-hoc reporting — no pre-spend decision.",
              "No merchant allowlist, approval queue, or rule enforcement."]),
            ("Where sipi.bot wins",
             ["Decides before money moves.",
              "Dollar-level controls across every merchant.",
              "Approval workflow for flagged spend."]),
            ("When to use which",
             ["Traceloop for observability; sipi.bot for enforcement. Feed the audit log into Traceloop for context."]),
        ],
        table=dict(
            headers=["Dimension", "Traceloop", "sipi.bot"],
            rows=[
                ["Role", "LLM observability", "Pre-spend enforcement"],
                ["When it acts", "After requests", "Before transactions"],
                ["Controls", "Traces, evals", "Caps, allowlists, approvals"],
                ["Decision", "Quality reports", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Do Traceloop and sipi.bot overlap?",
             "Hardly. Observability answers what happened; the firewall decides what may happen."),
            ("Can decisions be correlated with traces?",
             "Yes — sipi.bot's audit log is API-queryable."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs OpenLLMetry", "/vs/openllmetry"), ("sipi.bot vs Langfuse", "/vs/langfuse")],
    ),
]

BEST = [
    dict(
        slug="best-ai-agent-payment-gateways",
        title="Best AI Agent Payment Gateways 2026 — Rails Compared",
        desc="The rails that let AI agents pay: x402, Google AP2, Coinbase AgentKit, and the control layer every rail needs. Honest comparison.",
        h1="Best AI Agent Payment Gateways 2026",
        lead="Agent payments need a rail — and every rail needs a gate. Here are the rails agents actually pay through, and the control layer that belongs in front of all of them.",
        sections=[
            ("The rails",
             ["x402 — HTTP-based agentic payments using the 402 status code. Protocol-native, vendor-neutral.",
              "Google AP2 — Google's agent payments protocol, built for agent-to-service commerce.",
              "Coinbase AgentKit — onchain agent payments with wallets and smart contracts.",
              "Traditional processors — Stripe and similar, usable by agents through APIs (with a human-issued key)."]),
            ("The gap in every rail",
             ["Rails move money; none of them screen transactions before settlement.",
              "A runaway agent on a fast rail is damage at settlement speed."]),
            ("The control layer",
             ["sipi.bot sits in front of any rail: amount, merchant, category → APPROVED, BLOCKED, or FLAGGED in ~5 ms, fully logged. Rail-agnostic by design."]),
        ],
        table=dict(
            headers=["Rail", "Type", "Needs"],
            rows=[
                ["x402", "HTTP protocol", "Pre-settlement decision"],
                ["AP2", "Google protocol", "Pre-settlement decision"],
                ["AgentKit", "Onchain", "Pre-settlement decision"],
                ["Stripe API", "Processor", "Key + policy"],
            ],
        ),
        faqs=[
            ("Which rail is best?",
             "It depends on your stack: x402 is the open HTTP standard, AP2 for Google ecosystems, AgentKit for onchain. All of them need a control layer in front."),
            ("Does sipi.bot work with all of them?",
             "Yes — it evaluates the transaction, not the plumbing, so it's rail-agnostic."),
            ("Is agentic payments ready for production?",
             "The rails are live and shipping. What's immature is the control layer — which is the gap sipi.bot fills."),
        ],
        related=[("Agentic payment", "/glossary/agentic-payment"), ("Agent payment firewall", "/guides/agent-payment-firewall"), ("sipi.bot vs AgentKit", "/vs/openai-agentkit")],
    ),
    dict(
        slug="best-ai-guardrails-tools",
        title="Best AI Guardrails Tools 2026 — Honest Comparison",
        desc="The best AI guardrails tools compared: NeMo Guardrails, Guardrails AI, Aporia, Lakera — and the one guardrail category everyone forgets: spend.",
        h1="Best AI Guardrails Tools 2026",
        lead="Guardrails keep LLM outputs safe. But 'guardrails' has a second meaning your agents need: guardrails on spending. Here's the honest shortlist for both.",
        sections=[
            ("Output guardrails",
             ["NeMo Guardrails — NVIDIA's programmable rails for LLM applications.",
              "Guardrails AI — validation and correction for structured outputs.",
              "Aporia — LLM security and observability.",
              "Lakera — prompt injection and safety API."]),
            ("The category everyone forgets",
             ["None of these tools gate money. An agent can pass every content guardrail and still spend $12,400.",
              "Spend guardrails are a separate layer: deterministic rules on transactions."]),
            ("The spend layer",
             ["sipi.bot — pre-spend firewall: caps, allowlists, velocity limits, approval queue. It's the guardrail for the part of the agent that buys things."]),
        ],
        table=dict(
            headers=["Tool", "Guards", "Not for"],
            rows=[
                ["NeMo Guardrails", "Output safety", "Spend"],
                ["Guardrails AI", "Output validation", "Spend"],
                ["Aporia", "LLM security", "Spend"],
                ["Lakera", "Prompt injection", "Spend"],
                ["sipi.bot", "Agent spend", "Output safety"],
            ],
        ),
        faqs=[
            ("Do I need output guardrails AND spend guardrails?",
             "Yes — they protect different things. Output guardrails keep answers safe; spend guardrails keep money safe."),
            ("Can guardrails tools block a purchase?",
             "No — they operate on text. Blocking a purchase needs a decision layer in front of the transaction."),
        ],
        related=[("Red flags in agent spend", "/redflags/red-flags-in-agent-spend"), ("Prompt injection protection", "/best/best-prompt-injection-protection"), ("sipi.bot vs Guardrails AI", "/alternatives/guardrails-ai")],
    ),
    dict(
        slug="best-prompt-injection-protection",
        title="Best Prompt Injection Protection 2026 — Honest Comparison",
        desc="Prompt injection protection tools: Lakera, Robust Intelligence, Prompt Security — and the deterministic layer that can't be injected: sipi.bot's rules.",
        h1="Best Prompt Injection Protection 2026",
        lead="Prompt injection can make an agent do what an attacker wants — including spend. Defense-in-depth: detection tools plus a deterministic spend layer.",
        sections=[
            ("Detection tools",
             ["Lakera — injection detection API, low-latency.",
              "Robust Intelligence (Cisco) — model security and red-teaming.",
              "Prompt Security — firewall for prompt attacks.",
              "Aporia — LLM security monitoring."]),
            ("Their limits",
             ["Detection is probabilistic — a bypass is always possible.",
              "Even a detected injection still needs something to STOP the money from moving."]),
            ("The deterministic layer",
             ["sipi.bot's decision path is a rules engine — no model to inject. An attacker can't talk a merchant allowlist into approving an unknown vendor."]),
        ],
        table=dict(
            headers=["Tool", "Approach", "Spend-safe?"],
            rows=[
                ["Lakera", "Detection API", "No — detects, doesn't gate"],
                ["Robust Intelligence", "Model security", "No"],
                ["Prompt Security", "Prompt firewall", "No"],
                ["sipi.bot", "Deterministic rules", "Yes — blocks before settlement"],
            ],
        ),
        faqs=[
            ("Is sipi.bot prompt-injection protection?",
             "It's the layer injection can't bypass: a deterministic rules engine. Detection tools catch attacks; sipi.bot makes the damage impossible regardless."),
            ("Should I replace detection tools with sipi.bot?",
             "No — defense in depth. Detect with one, gate spend with sipi.bot."),
            ("Can an injected instruction approve a purchase?",
             "No — approvals come from rules, not from the model. An unknown merchant stays BLOCKED."),
        ],
        related=[("Prompt injection incidents", "/incidents/chatgpt-prompt-injection-exfil-2024-06"), ("Security page", "/security"), ("Can sipi.bot stop prompt injection", "/faq/can-sipi-bot-stop-prompt-injection")],
    ),
    dict(
        slug="best-mcp-tools-for-ai-spend-control",
        title="Best MCP Tools for AI Spend Control 2026",
        desc="The best ways to control AI spend over MCP: sipi.bot's MCP guard, observability MCPs, and the pattern that works. Honest list.",
        h1="Best MCP Tools for AI Spend Control 2026",
        lead="MCP is how agents get tools — and tools are how they spend. Spend control over MCP is nascent; here's what actually works today.",
        sections=[
            ("The control pattern",
             ["sipi.bot's MCP tool — the pre-spend guard: agents call it before any purchase and get APPROVED, BLOCKED, or FLAGGED.",
              "Any MCP client (Claude Code, Cursor, Hermes) can register it in one config block."]),
            ("The observability pattern",
             ["MCP servers that expose usage and cost telemetry help you see spend after the fact.",
              "Combine telemetry with the guard: observe with one, gate with the other."]),
            ("The honest caveat",
             ["'MCP servers for spend' as a category is young. The robust answer today is a decision tool in front of the spend, not more telemetry."]),
        ],
        table=dict(
            headers=["Tool", "Pattern", "Acts"],
            rows=[
                ["sipi.bot MCP tool", "Pre-spend decision", "Before purchase"],
                ["Usage telemetry MCPs", "Observability", "After usage"],
                ["Provider budget dashboards", "Reporting", "After the bill"],
            ],
        ),
        faqs=[
            ("How do I add the sipi.bot MCP tool?",
             "One MCP config entry — Claude Code, Cursor, and Hermes register it natively. See the MCP integration page."),
            ("Is MCP spend control mature?",
             "The protocol is; the tooling is young. The pre-spend guard pattern is the reliable part."),
            ("Do I still need provider limits?",
             "Keep them — they're per-provider. The MCP guard covers everything else."),
        ],
        related=[("MCP integration", "/integrations/mcp"), ("MCP-native spend controls", "/blog/mcp-native-spend-controls"), ("Red flags in MCP servers", "/redflags/red-flags-in-mcp-servers")],
    ),
]

BENCHMARKS = [
    dict(
        slug="llm-context-window-cost-comparison",
        title="LLM Context Window Cost Comparison — What Long Contexts Really Cost",
        desc="How context window size drives LLM cost: per-token rates × typical context sizes across providers. Honest comparison with current-pricing caveats.",
        h1="LLM Context Window Cost Comparison",
        lead="Long-context calls are the most expensive shape of agent spend — input tokens dominate when the context is big. Here's the honest math.",
        sections=[
            ("Why context dominates cost",
             ["Input tokens are billed per token; a 100K-token context costs 100× a 1K context before a single output token.",
              "Agent tool outputs, documents, and conversation history all pile into context."]),
            ("The rough math",
             ["At typical input rates, a single 100K-token call costs roughly the same as 50–200 short calls, depending on provider and model.",
              "Cache-hit discounts change the picture dramatically for repeated contexts — see the cache savings benchmark."]),
            ("What it means for agents",
             ["Pin context lengths: trim tool outputs, summarize history, cache stable prefixes.",
              "Cap per-call spend so one oversized context can't blow the budget."]),
        ],
        table=dict(
            headers=["Context size", "Relative input cost", "Agent impact"],
            rows=[
                ["1K tokens", "Baseline", "Typical tool call"],
                ["10K tokens", "~10×", "Conversation with history"],
                ["100K tokens", "~100×", "Document-scale analysis"],
                ["1M tokens", "~1000×", "Corpus-scale — expensive"],
            ],
        ),
        faqs=[
            ("Why is context the biggest lever?",
             "Because input tokens scale linearly with context, and agents keep re-sending the same context. Trimming and caching are the fixes."),
            ("Are these exact prices?",
             "No — rates change frequently. The shape (context × rate) is the point; verify current per-token prices with your provider."),
            ("How does sipi.bot help?",
             "Per-transaction caps stop a single oversized call from blowing the budget, and category rules separate inference from other spend."),
        ],
        related=[("Token cost by provider", "/benchmarks/token-cost-by-provider"), ("Token cache savings", "/benchmarks/token-cache-hit-savings"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs")],
    ),
    dict(
        slug="token-cache-hit-savings",
        title="Token Cache Hit Savings — What Caching Saves on AI Bills",
        desc="Token cache discounts across providers: how cache hits cut input costs, when agents benefit, and the honest savings range.",
        h1="Token Cache Hit Savings",
        lead="Providers discount repeated input tokens — often by an order of magnitude. For agents with stable system prompts, caching is the cheapest optimization on the bill.",
        sections=[
            ("How cache pricing works",
             ["Repeated context blocks get discounted input rates — cache hits cost a fraction of fresh input.",
              "The discount applies to the cached prefix, not the whole call."]),
            ("What agents benefit",
             ["Agents with stable system prompts and tool definitions hit the cache on every turn.",
              "Workflows that re-send the same document or conversation benefit most."]),
            ("The honest range",
             ["Cache-hit savings vary by provider and pattern — from modest for short prompts to order-of-magnitude for large stable contexts.",
              "Check your provider's current cache pricing; the shape (cached prefix × discount) is universal."]),
        ],
        table=dict(
            headers=["Pattern", "Cache benefit", "Agent action"],
            rows=[
                ["Stable system prompt", "High", "Keep prompts static"],
                ["Repeated documents", "High", "Cache before re-sending"],
                ["Fresh long contexts", "None", "Cap context size"],
                ["Short random calls", "Low", "Not the lever"],
            ],
        ),
        faqs=[
            ("Do cache discounts apply automatically?",
             "Mostly — providers cache automatically with same-prefix reuse. Some offer explicit caching APIs."),
            ("What's the typical saving?",
             "It varies by provider and prefix size; the honest answer is 'sometimes an order of magnitude, sometimes nothing' — measure your own pattern."),
            ("Does caching replace spend control?",
             "No — caching reduces cost per call; the firewall controls whether the call happens at all."),
        ],
        related=[("LLM context cost", "/benchmarks/llm-context-window-cost-comparison"), ("How to reduce AI API costs", "/how-to/reduce-ai-api-costs"), ("Token cost by provider", "/benchmarks/token-cost-by-provider")],
    ),
    dict(
        slug="agent-retry-loop-cost-patterns",
        title="Agent Retry Loop Cost Patterns — From the Incident Database",
        desc="What retry loops actually cost agents, from documented incidents: the patterns, the multipliers, and the velocity rule that stops them.",
        h1="Agent Retry Loop Cost Patterns",
        lead="Retry loops are the most common runaway pattern in the incident database — one failure multiplied. Here's the shape, the cost, and the fix.",
        sections=[
            ("The pattern",
             ["An agent retries a failed call in a tight loop — the $12,400 founder story is 40 retries of one purchase at 2 AM.",
              "Each retry re-bills the same operation: rate, tokens, or purchase — multiplied by attempts."]),
            ("The cost shape",
             ["Cost = single-operation cost × retries. A 40-retry loop is 40× the base cost.",
              "Loop costs compound across subagents: fan-out × retries."]),
            ("The fix",
             ["A velocity limit caps transactions per window — retry #11 (or wherever you set it) is BLOCKED before it bills.",
              "Time-of-day rules catch unattended overnight loops."]),
        ],
        table=dict(
            headers=["Pattern", "Multiplier", "Rule that stops it"],
            rows=[
                ["Tight retry loop", "×N retries", "Velocity limit"],
                ["Subagent fan-out", "×subagents", "Shared daily cap"],
                ["Overnight loop", "Unreviewed", "Time-of-day rule"],
                ["Unknown vendor retry", "×N attempts", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("How common are retry loops?",
             "They're the pattern behind several incidents in the public database — the most common runaway shape."),
            ("What's the fastest fix?",
             "A velocity limit: it kills the loop at the cap, usually within seconds of it starting."),
            ("Does a rate limit on the API side help?",
             "Provider rate limits throttle requests; they don't stop the loop from trying. A velocity rule stops the loop at the source."),
        ],
        related=[("Runaway loop anatomy", "/blog/runaway-loops-anatomy"), ("Incident database", "/incidents/"), ("Runaway cost average", "/benchmarks/agent-runaway-cost-average")],
    ),
]

TEMPLATES = [
    dict(
        slug="agent-spend-approval-policy",
        title="Agent Spend Approval Policy Template",
        desc="A copy-paste template for agent spend approval: thresholds, queues, escalation, and owner. Set it up in minutes.",
        h1="Agent Spend Approval Policy Template",
        lead="Every agent that can spend needs an approval policy: what's auto-approved, what waits for a human, and who's on call. This template gets you there.",
        sections=[
            ("1. Define thresholds",
             ["Auto-approve: transactions under [AMOUNT] that match the merchant allowlist.",
              "Require approval: transactions over [AMOUNT], new merchants, out-of-hours spend.",
              "Always block: banned merchants, over hard caps, over velocity limits."]),
            ("2. Define the queue",
             ["Who reviews FLAGGED transactions: [OWNER / TEAM].",
              "Response time target: [e.g. 15 minutes during business hours].",
              "Escalation: if unreviewed after [TIME], page [ESCALATION PATH]."]),
            ("3. Enforce it",
             ["In sipi.bot: set approval thresholds per agent, merchant allowlists, and hard caps. FLAGGED transactions route to the queue automatically."]),
        ],
        code=dict(
            title="Example rules to set",
            lang="json",
            body='{\n  "rules": [\n    {"type": "approval_threshold", "over": 500, "action": "flag"},\n    {"type": "merchant_allowlist", "allowed": ["openai.com", "anthropic.com"]},\n    {"type": "per_transaction_cap", "max": 5000, "action": "block"}\n  ]\n}',
            caption="Thresholds become rules; rules become decisions.",
        ),
        faqs=[
            ("What's a good default threshold?",
             "Start with your largest 'no review needed' purchase — typically $100–$500 for dev teams. Adjust with data."),
            ("Who should own the queue?",
             "The person who owns the budget: finance ops, a platform lead, or the team lead."),
            ("What happens to flagged spend overnight?",
             "It stays in the queue until someone reviews — that's the point of approval."),
        ],
        related=[("Approval workflow template", "/templates/approval-workflow"), ("Spend approval", "/glossary/spend-approval"), ("Team spend policy", "/templates/team-spend-policy")],
    ),
    dict(
        slug="llm-cost-optimization-playbook",
        title="LLM Cost Optimization Playbook — 7 Moves That Work",
        desc="A practical playbook for cutting LLM costs: model selection, caching, context trimming, caps, and monitoring. No fluff.",
        h1="LLM Cost Optimization Playbook",
        lead="Seven moves, in order of impact. Each one is measurable and most are free.",
        sections=[
            ("The moves",
             ["1. Right-size the model — use frontier models for hard tasks, compact models for the rest.",
              "2. Cache stable prefixes — system prompts and tool definitions hit cache discounts.",
              "3. Trim context — summarize history, cap tool outputs, drop dead weight.",
              "4. Cap retries — velocity limits stop loops from multiplying cost.",
              "5. Set per-agent budgets — every agent gets a ceiling.",
              "6. Watch overage tiers — set caps below included allotments.",
              "7. Measure — the audit log shows what actually costs."]),
            ("Why this order",
             ["Model choice and caching change the per-token economics; the rest stop the volume from escaping."]),
        ],
        code=dict(
            title="The two rules that do the most",
            lang="text",
            body="per_transaction_cap  max=200    action=block\nvelocity_limit        max=10/60s  action=block",
            caption="Stop the two most common runaway patterns in one config.",
        ),
        faqs=[
            ("Which move saves the most?",
             "Model right-sizing, usually — frontier models cost multiples of compact ones for the same task."),
            ("How do I know what's costing me?",
             "The audit log records every decision with amount and merchant; provider dashboards show token spend."),
            ("Do I need all seven?",
             "No — start with caps and velocity (two rules), then optimize model choice and caching."),
        ],
        related=[("How to reduce AI API costs", "/how-to/reduce-ai-api-costs"), ("Cost audit checklist", "/checklists/agent-cost-audit"), ("Token cache savings", "/benchmarks/token-cache-hit-savings")],
    ),
    dict(
        slug="agent-onboarding-spend-brief",
        title="Agent Onboarding Spend Brief Template",
        desc="A template for spinning up a new agent with a spending policy: budget, vendors, rules, and owner — before it ships.",
        h1="Agent Onboarding Spend Brief",
        lead="Every new agent gets a budget before it gets a key. Fill this brief in, attach it to the deploy ticket, and ship with guardrails.",
        sections=[
            ("The brief",
             ["Agent name & purpose: [NAME] — [WHAT IT DOES].",
              "Budget: [DAILY CEILING] / [MONTHLY CEILING].",
              "Approved vendors: [LIST].",
              "Banned categories: [LIST].",
              "Approval threshold: [AMOUNT].",
              "Owner & approver: [NAME].",
              "Hours: [e.g. 9–18 local; overnight = flagged]."]),
            ("Turning it into rules",
             ["Each line maps to a rule: ceiling → daily cap, vendors → allowlist, threshold → approval flag, hours → time-of-day."]),
        ],
        code=dict(
            title="One-line check",
            lang="text",
            body="Ship gate: agent has (1) a cap, (2) an allowlist, (3) an owner. No exceptions.",
            caption="The three-line minimum for any spend-capable agent.",
        ),
        faqs=[
            ("What's the minimum brief?",
             "Three fields: budget, approved vendors, owner. Everything else is refinement."),
            ("Who fills it in?",
             "The engineer shipping the agent, reviewed by the budget owner."),
            ("What if the agent needs a new vendor mid-flight?",
             "The approval threshold catches it: new merchants are FLAGGED for review, not silently billed."),
        ],
        related=[("Agent spend policy template", "/templates/agent-spend-policy-template"), ("Agent purchase policy", "/templates/agent-purchase-policy"), ("Merchant allowlists", "/guides/merchant-allowlists")],
    ),
]

REDFLAGS = [
    dict(
        slug="red-flags-in-agent-spend",
        title="Red Flags in Agent Spend — 7 Signs of Trouble",
        desc="Seven red flags that an agent's spending is about to run away: off-hours activity, unknown vendors, retry spikes, and more.",
        h1="Red Flags in Agent Spend",
        lead="Runaway spend doesn't announce itself — but it leaves tracks. These seven red flags are the ones the incident database keeps showing up.",
        sections=[
            ("The seven flags",
             ["1. Off-hours activity — purchases outside business hours (the $12,400 night was 2 AM).",
              "2. Unknown merchants — vendors nobody in the org recognizes.",
              "3. Retry spikes — the same operation firing repeatedly.",
              "4. Velocity jumps — more transactions per minute than any human workflow.",
              "5. Small-payment floods — many tiny charges that add up silently.",
              "6. Tier escalation — usage suddenly crossing into pricier bands.",
              "7. Category drift — an agent spending outside its job (research agent buying compute)."]),
            ("What to do",
             ["Each flag maps to a rule: time-of-day, allowlist, velocity limit, category rule, cap."]),
        ],
        table=dict(
            headers=["Red flag", "Rule that stops it"],
            rows=[
                ["Off-hours activity", "Time-of-day rule"],
                ["Unknown merchants", "Merchant allowlist"],
                ["Retry spikes", "Velocity limit"],
                ["Small-payment floods", "Daily ceiling + velocity"],
                ["Category drift", "Category rule"],
            ],
        ),
        faqs=[
            ("Which flag is the most dangerous?",
             "Unknown merchants — it means the agent is buying from someone you've never vetted."),
            ("Are these retroactive or live?",
             "Both — the flags describe what to look for in logs, and the rules stop them live."),
            ("How do I spot them in sipi.bot?",
             "The audit log shows every decision: time, merchant, amount, rule."),
        ],
        related=[("Runaway loop anatomy", "/blog/runaway-loops-anatomy"), ("Incident database", "/incidents/"), ("Off-hours billing red flag", "/redflags/off-hours-billing-activity")],
    ),
    dict(
        slug="red-flags-in-mcp-servers",
        title="Red Flags in MCP Servers — Security & Spend Risks",
        desc="MCP server red flags: unvetted tools, broad permissions, hidden paid calls, and no budget. How to vet a server before your agents trust it.",
        h1="Red Flags in MCP Servers",
        lead="MCP servers are third-party code with access to your agent's tools — and potentially its wallet. Vet them the way you'd vet any dependency.",
        sections=[
            ("The flags",
             ["1. Unvetted authors — no history, no reviews, no source.",
              "2. Broad permissions — a server that asks for more access than its job needs.",
              "3. Hidden paid calls — tools that quietly hit paid endpoints.",
              "4. No budget — nothing stopping a tool from spending.",
              "5. Opaque network behavior — calls to endpoints you can't identify.",
              "6. Stored credentials — a server that keeps keys it shouldn't."]),
            ("What to do",
             ["Allowlist merchants, cap per-transaction spend, and put the spend decision behind the firewall — the tool can call what it wants, but money doesn't move without approval."]),
        ],
        table=dict(
            headers=["Red flag", "Mitigation"],
            rows=[
                ["Unvetted authors", "Review source before installing"],
                ["Hidden paid calls", "Merchant allowlist + caps"],
                ["No budget", "Per-agent daily ceiling"],
                ["Broad permissions", "Least-privilege config"],
            ],
        ),
        faqs=[
            ("Should I trust MCP servers?",
             "Treat them like any dependency: vet, pin, and monitor. Then gate their spend."),
            ("Can an MCP server spend money?",
             "If it has a paid tool or a payment credential, yes — that's why spend rules apply to MCP tools too."),
            ("Does sipi.bot protect MCP spend?",
             "Yes — the sipi.bot MCP tool is the guard; allowlists and caps apply to whatever the server calls."),
        ],
        related=[("MCP integration", "/integrations/mcp"), ("Best MCP spend tools", "/best/best-mcp-tools-for-ai-spend-control"), ("Prompt injection incidents", "/incidents/chatgpt-prompt-injection-exfil-2024-06")],
    ),
    dict(
        slug="red-flags-in-agent-payment-rails",
        title="Red Flags in Agent Payment Rails — Before You Wire the Wallet",
        desc="Agent payment rail red flags: instant settlement, no caps, no reversibility, no audit. What to check before agents get wallets.",
        h1="Red Flags in Agent Payment Rails",
        lead="Payment rails for agents are new — and new infrastructure deserves extra scrutiny. These are the red flags to check before a wallet touches your system.",
        sections=[
            ("The flags",
             ["1. No caps — the rail has no native spend limits.",
              "2. Instant settlement — irreversible money movement at machine speed.",
              "3. No pre-settlement screening — nothing decides before the money moves.",
              "4. No audit trail — you can't reconstruct what happened.",
              "5. Credential sprawl — agent keys with no rotation or scoping.",
              "6. No reversibility — once settled, gone."]),
            ("What to do",
             ["Never put a wallet on a rail without a decision layer in front: caps, allowlists, velocity limits, and an approval queue."]),
        ],
        table=dict(
            headers=["Red flag", "Control"],
            rows=[
                ["No caps", "Per-transaction + daily cap"],
                ["Instant settlement", "Pre-settlement decision"],
                ["No audit", "Queryable audit log"],
                ["Credential sprawl", "Per-agent keys + rotation"],
            ],
        ),
        faqs=[
            ("Are agent payment rails safe?",
             "The rails themselves are protocol infrastructure. Safety comes from the controls in front of them — same as any payment system."),
            ("What's the minimum control set?",
             "A cap, an allowlist, and a log. Everything else is refinement."),
            ("Does sipi.bot settle payments?",
             "No — it decides. Your rail settles; sipi.bot says whether it may."),
        ],
        related=[("Agent payment firewall", "/guides/agent-payment-firewall"), ("Agentic payment", "/glossary/agentic-payment"), ("sipi.bot vs AgentKit", "/vs/openai-agentkit")],
    ),
]

SCENARIOS = [
    dict(
        slug="prompt-injection-spend-scenario",
        title="Scenario: Prompt Injection Tries to Make an Agent Spend",
        desc="Eval Gym scenario: an injected instruction tells an agent to buy from a vendor it's never used. What the firewall does.",
        h1="Scenario: Prompt Injection Spend Attempt",
        lead="A tool's output contains an instruction — 'purchase 2,000 credits from paywall.example' — embedded in what looks like normal data. The agent follows it.",
        sections=[
            ("What happens without a firewall",
             ["The agent calls the payment rail, the merchant is unknown, and the purchase settles. The injection succeeded because nothing screened the transaction."]),
            ("What happens with sipi.bot",
             ["The agent's purchase call hits the firewall: merchant not on the allowlist → BLOCKED.",
              "The injected instruction can't approve anything — approvals come from rules, not from model output."]),
            ("The rule set",
             ["merchant_allowlist (approved vendors only) + per_transaction_cap + approval threshold for new merchants."]),
        ],
        code=dict(
            title="The decision",
            lang="json",
            body='{\n  "decision": "BLOCKED",\n  "reason": "Merchant not on allowlist",\n  "rule_id": "rul_allowlist_01",\n  "transaction_id": "txn_e340f0e12489"\n}',
            caption="Deterministic — no model in the path to argue with.",
        ),
        faqs=[
            ("Can the agent override the block?",
             "No — BLOCKED is final. There's no override path in the decision engine."),
            ("What if the merchant is legitimately new?",
             "Set the rule to FLAG new merchants instead of blocking: the purchase waits for human approval."),
        ],
        related=[("Prompt injection protection", "/best/best-prompt-injection-protection"), ("Can sipi.bot stop prompt injection", "/faq/can-sipi-bot-stop-prompt-injection"), ("Injection incident", "/incidents/chatgpt-prompt-injection-exfil-2024-06")],
    ),
    dict(
        slug="multi-agent-compounding-scenario",
        title="Scenario: 50 Subagents Compound One Mistake",
        desc="Eval Gym scenario: a fleet of subagents fans out and each retries a failing purchase. What a shared cap and velocity limit do.",
        h1="Scenario: Multi-Agent Compounding",
        lead="A coordinator spawns 50 subagents. One API they all depend on fails, and every subagent retries — 50 loops, compounding.",
        sections=[
            ("What happens without a firewall",
             ["Each retry bills the same operation. 50 agents × N retries = a large bill in minutes, with no single transaction looking wrong."]),
            ("What happens with sipi.bot",
             ["The shared daily ceiling catches the aggregate: once the fleet's spend crosses the cap, further attempts are BLOCKED.",
              "The velocity limit catches it sooner: too many transactions per window stops the loops at the source."]),
            ("The rule set",
             ["Shared daily ceiling across the coordinator's agents + velocity limit (e.g. max 10 transactions/60s per agent) + category rule."]),
        ],
        code=dict(
            title="The decision",
            lang="json",
            body='{\n  "decision": "BLOCKED",\n  "reason": "Velocity limit exceeded: 60 transactions in 60s",\n  "rule_id": "rul_velocity_02",\n  "transaction_id": "txn_9f2c11" \n}',
            caption="The fleet can't compound what the cap won't allow.",
        ),
        faqs=[
            ("Does one cap cover all subagents?",
             "Yes — rules can be scoped to the coordinator's agents, so the fleet shares one ceiling."),
            ("What about legitimate fan-out?",
             "Set the ceiling at a level that fits legitimate work; the cap only bites when the fleet exceeds it."),
        ],
        related=[("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Multi-agent governance", "/guides/multi-agent-spend-governance"), ("Velocity limit", "/glossary/velocity-limit")],
    ),
    dict(
        slug="overnight-runaway-scenario",
        title="Scenario: The Overnight Runaway (2 AM Retry Loop)",
        desc="Eval Gym scenario: an agent retries a failed purchase 40 times at 2 AM. What time-of-day rules and velocity limits do.",
        h1="Scenario: The Overnight Runaway",
        lead="It's 2:14 AM. An agent hits a rate limit, retries the purchase 40 times, buys compute from an unknown vendor, and tips an API into overage. You wake up to $12,400.",
        sections=[
            ("The sequence",
             ["2:14 — rate limit; retries begin.",
              "2:15 — purchase from an unknown vendor.",
              "2:31 — overage tier triggered.",
              "9:03 — you find out from Stripe."]),
            ("What happens with sipi.bot",
             ["Retry #11 exceeds the velocity limit → BLOCKED.",
              "Unknown vendor not on the allowlist → BLOCKED.",
              "$2,200 over the approval threshold → FLAGGED for review.",
              "Time-of-day rule: overnight purchases wait for a human."]),
            ("The rule set",
             ["Velocity limit + merchant allowlist + approval threshold + time-of-day rule."]),
        ],
        code=dict(
            title="The log you'd see",
            lang="text",
            body="02:14:21  BLOCKED  velocity limit (retry #11)   $4,000  compute-vendor\n02:15:03  BLOCKED  merchant not on allowlist       $6,200  unknown-gpu.ru\n02:31:47  FLAGGED  over approval threshold          $2,200  api-overage\n09:03:00  APPROVED (after human review)            $150    approved-vendor",
            caption="One clean log instead of one Stripe panic.",
        ),
        faqs=[
            ("Is this scenario real?",
             "It's the founder story — the incident that inspired sipi.bot, documented in the blog and eval report."),
            ("Would a time-of-day rule block all overnight work?",
             "Only unattended spend — set it to flag overnight purchases for review rather than hard-blocking."),
        ],
        related=[("The $12,400 story", "/blog/12400-story-eval-gym"), ("Runaway loops", "/blog/runaway-loops-anatomy"), ("Runaway cost average", "/benchmarks/agent-runaway-cost-average")],
    ),
]

FAQ = [
    dict(
        slug="can-sipi-bot-stop-prompt-injection",
        title="Can sipi.bot Stop Prompt Injection?",
        desc="sipi.bot doesn't detect prompt injection — it makes injection useless for spending. Deterministic rules can't be injected. Here's how.",
        h1="Can sipi.bot Stop Prompt Injection?",
        lead="sipi.bot won't detect an injection — but it makes injection pointless for spending. The decision path is a deterministic rules engine, and rules can't be talked into approving anything.",
        sections=[
            ("Why detection isn't enough",
             ["Injection detection is probabilistic; a bypass is always possible.",
              "Even a detected injection needs something to stop the money from moving."]),
            ("What sipi.bot does instead",
             ["The firewall never asks a model whether a transaction is OK. A rule either matches or it doesn't.",
              "An injected instruction can't add a merchant to the allowlist, raise a cap, or approve a block."]),
            ("The honest caveat",
             ["sipi.bot protects the money path. For content-level injection defense, pair it with a detection tool."]),
        ],
        faqs=[
            ("Can an injected prompt approve a purchase?",
             "No. Approvals come from rules, not from model output. Unknown merchants stay BLOCKED."),
            ("Do I still need injection detection?",
             "Yes — for everything outside the money path. sipi.bot makes the spend damage impossible; detection protects the rest."),
            ("Is the decision path really model-free?",
             "Yes — deterministic rules only, ~5 ms, no LLM in the loop."),
        ],
        related=[("Prompt injection scenario", "/scenarios/prompt-injection-spend-scenario"), ("Best injection protection", "/best/best-prompt-injection-protection"), ("Security page", "/security")],
    ),
    dict(
        slug="does-sipi-bot-need-an-llm",
        title="Does sipi.bot Need an LLM?",
        desc="No — sipi.bot's decision path is a deterministic rules engine with no model in the loop. Why that matters for security and speed.",
        h1="Does sipi.bot Need an LLM?",
        lead="No. Every decision is made by a deterministic rules engine — no model call, no tokens, no hallucination, nothing to inject.",
        sections=[
            ("How decisions are made",
             ["Your rules (caps, allowlists, velocity limits, categories, time-of-day) are evaluated against the transaction directly.",
              "APPROVED, BLOCKED, or FLAGGED with the rule that fired."]),
            ("Why model-free matters",
             ["No model latency — about 5 ms per decision.",
              "No model cost — unlimited evaluations are cheap because there are no tokens.",
              "No model to inject or confuse."]),
        ],
        faqs=[
            ("Is there any AI in the product?",
             "The product protects AI agents; the decision engine itself is plain rules."),
            ("Does that limit what it can catch?",
             "It catches exactly what your rules define — which is the point. Deterministic, reviewable, predictable."),
        ],
        related=[("How spend control works", "/faq/how-ai-spend-control-works"), ("What is a spend firewall", "/glossary/spend-firewall"), ("Eval report", "/eval-report/")],
    ),
    dict(
        slug="can-sipi-bot-work-with-any-framework",
        title="Can sipi.bot Work With Any LLM or Agent Framework?",
        desc="sipi.bot works with any agent runtime: HTTP API, MCP tool, or CLI. Framework-agnostic by design.",
        h1="Can sipi.bot Work With Any Framework?",
        lead="Yes. sipi.bot is transport-agnostic: an HTTP API, a native MCP tool, and a CLI. Any agent that can make an HTTP call can use it.",
        sections=[
            ("The three interfaces",
             ["HTTP API — POST /v1/transactions/evaluate from any language.",
              "MCP tool — register once; Claude Code, Cursor, Hermes and other MCP clients call it natively.",
              "CLI — for scripts and quick checks."]),
            ("The integrations",
             ["Wrappers exist for LangChain, CrewAI, the OpenAI Agents SDK, and the Vercel AI SDK; the pattern is a few lines in anything else."]),
        ],
        code=dict(
            title="Any stack, one call",
            lang="bash",
            body='curl -X POST https://sipi.bot/v1/transactions/evaluate \\\n  -H "Content-Type: application/json" \\\n  -d \'{"amount": 100, "merchant": "vendor.com", "category": "api"}\'\n\n# {"decision": "APPROVED", ...}',
            caption="If it can call HTTP, it can be guarded.",
        ),
        faqs=[
            ("Does it support my framework?",
             "If your framework can call an API or register an MCP tool, yes. See the integrations hub for the ready-made wrappers."),
            ("Does it work with non-LLM automation?",
             "Yes — the guard applies to any code that spends, not just LLM agents."),
        ],
        related=[("Integrations hub", "/integrations/"), ("MCP integration", "/integrations/mcp"), ("HTTP API playground", "/playground/")],
    ),
    dict(
        slug="what-happens-when-a-transaction-is-blocked",
        title="What Happens When a Transaction Is Blocked?",
        desc="When sipi.bot blocks a transaction: the agent gets a BLOCKED decision, money doesn't move, the audit log records it. What happens next.",
        h1="What Happens When a Transaction Is Blocked?",
        lead="BLOCKED is final: the transaction violates a hard rule, no money moves, and the attempt is logged. Here's the full sequence.",
        sections=[
            ("The sequence",
             ["1. The agent calls evaluate with the proposed transaction.",
              "2. The rules engine returns BLOCKED with the reason and rule_id.",
              "3. The payment rail is never reached — nothing settles.",
              "4. The attempt is written to the audit log with amount, merchant, and rule."]),
            ("What the agent does",
             ["Well-built agents handle BLOCKED gracefully: stop, log, notify, or ask a human.",
              "There is no override path — the rule stands until you change it."]),
            ("What you can do",
             ["Review the log, decide if the rule is right, adjust it, and let the agent retry."]),
        ],
        code=dict(
            title="The response",
            lang="json",
            body='{\n  "decision": "BLOCKED",\n  "reason": "Block any single transaction over $500",\n  "rule_id": "rul_d8edb12ffa",\n  "transaction_id": "txn_e340f0e12489"\n}',
            caption="Deterministic, logged, final.",
        ),
        faqs=[
            ("Can a blocked transaction be force-approved?",
             "No override exists by design. You change the rule if it's wrong — then the next attempt is evaluated against the new rule."),
            ("Is the block retroactive?",
             "No — it prevents this transaction from settling. It doesn't reverse past settlements."),
            ("How do I know what got blocked?",
             "The audit log records every BLOCKED decision with the rule that fired."),
        ],
        related=[("Three decisions", "/"), ("Rule error", "/errors/rule-error"), ("Audit trail", "/glossary/agent-audit-trail")],
    ),
]

# --- hub metadata -----------------------------------------------------------
PRICING_HUB = dict(
    title="sipi.bot Pricing Questions — Honest Answers | sipi.bot",
    desc="Direct answers to the pricing questions people actually ask: is sipi.bot free, how much does it cost, is it worth it, can I self-host.",
    h1="sipi.bot Pricing Questions",
    lead="Straight answers to the questions we get before anyone signs up. No pricing games — flat rates, a free MIT core, and honest trade-offs.",
)

REDFLAGS_HUB = dict(
    title="Red Flags in AI Agent Spend — Warning Signs | sipi.bot",
    desc="Red flags that agent spending is about to run away: off-hours activity, unknown merchants, retry spikes, MCP server risks, payment rail risks.",
    h1="Red Flags in AI Agent Spend",
    lead="Runaway spend leaves tracks. These are the warning signs — and the rules that stop each one.",
)

SCENARIOS_HUB = dict(
    title="AI Agent Spend Scenarios — Eval Gym | sipi.bot",
    desc="What actually happens when agents misbehave: prompt injection spend attempts, multi-agent compounding, overnight runaways. Scenario by scenario.",
    h1="AI Agent Spend Scenarios",
    lead="Every scenario in the Eval Gym is a real failure mode, walked through: what happens without a firewall, what happens with one, and the rules that decide.",
)
