"""Round 30 pSEO data — sipi.bot (2026-08-08).

Eleventh round. Two uncovered comparison clusters (usage-metering/billing
infra: metronome/orb/amberflo; LLM observability: weave/promptlayer) + the
AI-app-builder integration wave + fillers. 17 static pages + 2 blog.

All existing dirs — no plumbing. Content honest: category comparisons state
what each tool does without invented numbers; sipi.bot positioned as the
composing gate, not a replacement for metering or observability.
"""

VS = [
    dict(
        slug="metronome",
        name="Metronome",
        title="sipi.bot vs Metronome — Usage-Based Billing vs Spend Firewall",
        desc="Metronome bills your customers by usage; sipi.bot gates what your agents spend. Different jobs, same budget conversation.",
        h1="sipi.bot vs Metronome",
        lead="Metronome is usage-based billing infrastructure — it measures what customers used and bills them. sipi.bot is a pre-spend firewall for agents. One meters revenue; the other gates cost.",
        sections=[
            ("What Metronome does well",
             ["Purpose-built usage-based billing: metering, pricing, invoicing at scale.",
              "The modern standard for billing AI products by usage."]),
            ("Where it falls short for agent spend",
             ["It meters and bills your customers; it doesn't gate what your agents spend.",
              "No pre-spend decisions, merchant allowlists, or approval queues for internal agent spend."]),
            ("Where sipi.bot wins",
             ["Decides before the money moves: APPROVED, BLOCKED, FLAGGED.",
              "Governs every merchant your agents touch, not just your billing surface."]),
            ("When to use which",
             ["Metronome for customer billing; sipi.bot for agent spend control. They compose — meter with one, gate with the other."]),
        ],
        table=dict(
            headers=["Dimension", "Metronome", "sipi.bot"],
            rows=[
                ["Role", "Usage-based billing", "Pre-spend firewall"],
                ["Direction", "Bill customers", "Gate internal spend"],
                ["When it acts", "After usage", "Before transactions"],
                ["Controls", "Pricing, invoicing", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Are they competitors?",
             "No — Metronome monetizes your product; sipi.bot controls agent cost. Different directions."),
            ("Can they integrate?",
             "Yes — sipi.bot's audit log feeds usage data your metering stack can bill or report on."),
        ],
        related=[("sipi.bot vs OpenMeter", "/vs/openmeter"), ("sipi.bot vs Orb", "/vs/orb"), ("Best agent budgeting tools", "/best/best-agent-budgeting-tools")],
    ),
    dict(
        slug="orb",
        name="Orb",
        title="sipi.bot vs Orb — Metering vs Spend Enforcement",
        desc="Orb meters usage and bills customers; sipi.bot gates what agents spend. The compose story.",
        h1="sipi.bot vs Orb",
        lead="Orb is usage-based billing and metering infrastructure. sipi.bot is a pre-spend firewall. One bills your customers; the other controls your agents.",
        sections=[
            ("What Orb does well",
             ["Flexible metering, pricing, and invoicing for usage-based products.",
              "Strong for AI companies billing by tokens or requests."]),
            ("Where it falls short for agent spend",
             ["No pre-spend decision layer — it records usage, it doesn't gate it."]),
            ("Where sipi.bot wins",
             ["Deterministic decisions before settlement.",
              "Caps, allowlists, velocity limits, approvals across every merchant."]),
            ("When to use which",
             ["Orb for customer billing; sipi.bot for agent spend control. Complementary."]),
        ],
        table=dict(
            headers=["Dimension", "Orb", "sipi.bot"],
            rows=[
                ["Role", "Usage metering + billing", "Pre-spend firewall"],
                ["Direction", "Bill customers", "Gate internal spend"],
                ["When it acts", "After usage", "Before transactions"],
                ["Controls", "Pricing, invoicing", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Do Orb and sipi.bot overlap?",
             "No — billing vs enforcement."),
            ("What's the integration story?",
             "sipi.bot's audit log can feed Orb with internal usage data."),
        ],
        related=[("sipi.bot vs Metronome", "/vs/metronome"), ("sipi.bot vs OpenMeter", "/vs/openmeter"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
    dict(
        slug="amberflo",
        name="Amberflo",
        title="sipi.bot vs Amberflo — Usage Metering vs Spend Firewall",
        desc="Amberflo meters usage for billing; sipi.bot gates agent spend. Different layers of the same budget.",
        h1="sipi.bot vs Amberflo",
        lead="Amberflo is a real-time usage metering and pricing platform. sipi.bot is a pre-spend firewall. One measures; the other gates.",
        sections=[
            ("What Amberflo does well",
             ["Real-time metering and pricing for usage-based products.",
              "Fast time-to-value for usage billing."]),
            ("Where it falls short for agent spend",
             ["Metering records; it doesn't decide. No pre-spend enforcement."]),
            ("Where sipi.bot wins",
             ["Decides before settlement — caps, allowlists, velocity, approvals."]),
            ("When to use which",
             ["Amberflo for metering/billing; sipi.bot for agent spend enforcement."]),
        ],
        table=dict(
            headers=["Dimension", "Amberflo", "sipi.bot"],
            rows=[
                ["Role", "Usage metering", "Pre-spend firewall"],
                ["Direction", "Bill customers", "Gate internal spend"],
                ["When it acts", "After usage", "Before transactions"],
                ["Controls", "Pricing, metering", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Is Amberflo a spend firewall?",
             "No — it's metering/billing. The firewall gates before the money moves."),
            ("Can I use both?",
             "Yes — meter customer usage with Amberflo, gate agent spend with sipi.bot."),
        ],
        related=[("sipi.bot vs OpenMeter", "/vs/openmeter"), ("sipi.bot vs Metronome", "/vs/metronome"), ("Agent budget", "/glossary/agent-budget")],
    ),
    dict(
        slug="weave",
        name="W&B Weave",
        title="sipi.bot vs W&B Weave — ML Observability vs Spend Firewall",
        desc="Weights & Biases Weave traces LLM apps; sipi.bot gates agent spend. Observability vs enforcement.",
        h1="sipi.bot vs W&B Weave",
        lead="Weave is W&B's LLM observability and tracing platform. sipi.bot is a pre-spend firewall. One shows what happened; the other decides what may.",
        sections=[
            ("What Weave does well",
             ["Deep LLM tracing and evaluation inside the W&B ecosystem.",
              "Great for teams already on W&B."]),
            ("Where it falls short",
             ["Post-hoc observability — no pre-spend decision on transactions."]),
            ("Where sipi.bot wins",
             ["Deterministic pre-spend decisions across every merchant.",
              "Approval workflow for edge cases."]),
            ("When to use which",
             ["Weave for tracing; sipi.bot for enforcement. Feed the audit log into Weave for context."]),
        ],
        table=dict(
            headers=["Dimension", "W&B Weave", "sipi.bot"],
            rows=[
                ["Role", "LLM observability", "Pre-spend firewall"],
                ["When it acts", "After requests", "Before transactions"],
                ["Controls", "Traces, evals", "Caps, allowlists, approvals"],
                ["Decision", "Insights", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Are they competitors?",
             "No — observability and enforcement are different layers."),
            ("Can decisions feed Weave?",
             "Yes — the audit log is API-queryable."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs Langfuse", "/vs/langfuse"), ("sipi.bot vs PromptLayer", "/vs/promptlayer")],
    ),
    dict(
        slug="promptlayer",
        name="PromptLayer",
        title="sipi.bot vs PromptLayer — LLM Observability vs Spend Firewall",
        desc="PromptLayer tracks prompts and costs; sipi.bot blocks runaway agent spend. The observability vs enforcement split.",
        h1="sipi.bot vs PromptLayer",
        lead="PromptLayer is LLM observability — prompt tracking, logging, and cost analytics. sipi.bot is a pre-spend firewall. One logs; the other gates.",
        sections=[
            ("What PromptLayer does well",
             ["Prompt logging and versioning with cost tracking.",
              "Useful for debugging and optimizing LLM usage."]),
            ("Where it falls short",
             ["Observability is post-hoc — no pre-spend decision on transactions."]),
            ("Where sipi.bot wins",
             ["Decides before settlement: caps, allowlists, velocity, approvals."]),
            ("When to use which",
             ["PromptLayer for logs and cost analytics; sipi.bot for enforcement."]),
        ],
        table=dict(
            headers=["Dimension", "PromptLayer", "sipi.bot"],
            rows=[
                ["Role", "LLM observability", "Pre-spend firewall"],
                ["When it acts", "After requests", "Before transactions"],
                ["Controls", "Logs, cost analytics", "Caps, allowlists, approvals"],
                ["Decision", "Insights", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Do they overlap?",
             "Minimally — logging vs enforcement."),
            ("What's the compose pattern?",
             "Log with PromptLayer, gate with sipi.bot."),
        ],
        related=[("Best observability tools", "/best/best-ai-agent-observability-tools"), ("sipi.bot vs W&B Weave", "/vs/weave"), ("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs")],
    ),
]

INTEGRATIONS = [
    dict(
        slug="lovable",
        title="Lovable App Builder Spend Control — sipi.bot Integration",
        desc="Lovable generates apps on a credit model. sipi.bot guards the agents running inside and around what you build.",
        h1="Spend Control for Lovable",
        lead="Lovable builds apps from prompts on a credit-based model. The credits are the visible bill; the agents your built apps run are the hidden one.",
        sections=[
            ("Why built-app agents spend",
             ["Apps generated with Lovable run agents that call paid APIs.",
              "Usage-based credits compound as apps scale.",
              "No built-in dollar-level budget for the agents inside."]),
            ("How it works",
             ["Wire the guard into the agents your built apps run: before any spend, they ask sipi.bot and get a deterministic decision."]),
            ("Rules that fit",
             ["Per-app daily ceiling.",
              "Merchant allowlist for the APIs the app calls.",
              "Velocity limit on retry loops."]),
        ],
        code=dict(
            title="Guard call",
            lang="typescript",
            body='const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n  method: "POST", headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ amount: 5, merchant: "api.vendor.com", category: "api" }),\n});\nconst { decision } = await res.json();',
            caption="The built app gets a budget.",
        ),
        faqs=[
            ("Does sipi.bot affect Lovable credits?",
             "No — it governs the agents your app runs, not the builder's credits."),
            ("Can I cap per app?",
             "Yes — per-agent rules per app."),
        ],
        related=[("Bolt", "/integrations/bolt"), ("Replit Agent", "/integrations/replit-agent"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="bolt",
        title="Bolt AI App Builder Spend Control — sipi.bot Integration",
        desc="Bolt builds full-stack apps from prompts. sipi.bot guards the agent spend inside your Bolt-built apps.",
        h1="Spend Control for Bolt",
        lead="Bolt generates and deploys full-stack apps from prompts — and the apps you ship run agents that spend. The guard rides along.",
        sections=[
            ("Why Bolt-built apps spend",
             ["Generated apps call external APIs and run agentic features.",
              "Usage scales with your user base — so does API spend."]),
            ("How it works",
             ["Add the guard to the agents in your Bolt-built app: one HTTP call before any purchase."]),
            ("Rules that fit",
             ["Per-app ceiling, merchant allowlist, velocity limit."]),
        ],
        code=dict(
            title="Guard call",
            lang="typescript",
            body='const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n  method: "POST", headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ amount: 12, merchant: "api.vendor.com", category: "api" }),\n});\nconst { decision } = await res.json();',
            caption="Ship apps with budgets.",
        ),
        faqs=[
            ("Does this integrate with Bolt itself?",
             "sipi.bot is HTTP/MCP — it wires into the agents your app runs."),
            ("What about the build credits?",
             "Those are Bolt's billing; sipi.bot governs runtime agent spend."),
        ],
        related=[("Lovable", "/integrations/lovable"), ("v0", "/integrations/v0"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
    dict(
        slug="replit-agent",
        title="Replit Agent Spend Control — sipi.bot Integration",
        desc="Replit Agent builds and deploys software autonomously. sipi.bot gates the spend its deployments generate.",
        h1="Spend Control for Replit Agent",
        lead="Replit Agent writes, deploys, and provisions — autonomous software delivery that can spend on the way. A guard keeps the deploy budget real.",
        sections=[
            ("Why Replit Agent deployments spend",
             ["Deployments provision resources and call APIs.",
              "Autonomous iterations multiply tool and compute spend."]),
            ("How it works",
             ["Attach the guard as a tool: before any spend during build or deploy, the agent gets a deterministic decision."]),
            ("Rules that fit",
             ["Per-deploy or per-day ceiling.",
              "Merchant allowlist for provisioned vendors.",
              "Velocity limit on iteration loops."]),
        ],
        code=dict(
            title="Guard call",
            lang="typescript",
            body='const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n  method: "POST", headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ amount: 20, merchant: "provisioning-api.com", category: "compute" }),\n});\nconst { decision } = await res.json();',
            caption="Deploy with a budget.",
        ),
        faqs=[
            ("Can I cap per project?",
             "Yes — per-agent rules per project."),
            ("Is this about Replit's own billing?",
             "No — it governs the spend your deployments generate."),
        ],
        related=[("Bolt", "/integrations/bolt"), ("OpenAI Codex", "/integrations/openai-codex"), ("How to stop runaway agents", "/how-to/how-to-stop-runaway-agents")],
    ),
    dict(
        slug="trae",
        title="Trae AI IDE Spend Control — sipi.bot Integration",
        desc="Trae is the AI-native IDE. sipi.bot gives its agents a real spending policy.",
        h1="Spend Control for Trae",
        lead="Trae ships AI-native editing with agentic coding. Agents that code can also buy — the guard makes the budget real.",
        sections=[
            ("Why Trae agents overspend",
             ["Agentic sessions consume usage and call tools fast.",
              "Paid tool calls happen mid-task without review."]),
            ("How it works",
             ["Register the guard as a tool: before any spend, the agent gets APPROVED, BLOCKED, or FLAGGED."]),
            ("Rules that fit",
             ["Per-transaction cap, merchant allowlist, velocity limit."]),
        ],
        code=dict(
            title="Guard tool",
            lang="typescript",
            body='const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n  method: "POST", headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ amount: 60, merchant: "gpu-provider.com", category: "compute" }),\n});\nconst { decision } = await res.json();',
            caption="One tool, enforced policy.",
        ),
        faqs=[
            ("Does this slow Trae?",
             "No — ~5 ms per check, spend actions only."),
            ("Is this like the Cursor integration?",
             "Same pattern — see the Cursor page."),
        ],
        related=[("Cursor", "/integrations/cursor"), ("Cline", "/integrations/cline"), ("sipi.bot vs Trae", "/vs/trae")],
    ),
    dict(
        slug="v0",
        title="v0 (Vercel) Spend Control — sipi.bot Integration",
        desc="v0 generates UI and full-stack features. sipi.bot guards the agent spend in apps built with v0.",
        h1="Spend Control for v0",
        lead="v0 turns prompts into UI and full-stack features. The features you ship run agents that spend — the guard covers them.",
        sections=[
            ("Why v0-built apps spend",
             ["Generated features call APIs and run agentic flows.",
              "Deployments on Vercel bill per usage."]),
            ("How it works",
             ["Add the guard to the agents in your v0-built app — HTTP or MCP, one call before any purchase."]),
            ("Rules that fit",
             ["Per-app ceiling, merchant allowlist, category rule."]),
        ],
        code=dict(
            title="Guard call",
            lang="typescript",
            body='const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n  method: "POST", headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ amount: 8, merchant: "api.vendor.com", category: "api" }),\n});\nconst { decision } = await res.json();',
            caption="Ship features with budgets.",
        ),
        faqs=[
            ("Does this work with Vercel AI SDK?",
             "Yes — and there's a dedicated AI SDK integration."),
            ("What about Vercel's own billing?",
             "sipi.bot governs agent spend; Vercel bills your deployments."),
        ],
        related=[("Vercel AI SDK", "/integrations/vercel-ai-sdk"), ("Bolt", "/integrations/bolt"), ("sipi.bot vs v0", "/vs/v0")],
    ),
]

SECTORS = [
    dict(
        slug="construction",
        title="AI Spend Control for Construction | sipi.bot",
        desc="Construction AI agents: estimating, safety, and project-documentation bots that spend on data and inference per project.",
        h1="Spend Control for Construction AI Agents",
        lead="Construction runs agents for estimating, safety documentation, and project management — each with paid data and inference per project.",
        sections=[
            ("Where construction agents spend",
             ["Estimating agents pulling material and labor data.",
              "Safety-documentation agents generating reports.",
              "Project-management bots hitting scheduling APIs.",
              "Document review (plans, contracts) inference."]),
            ("The failure modes",
             ["An estimating loop re-pulling data multiplies per-call charges.",
              "Unknown data vendors bypass procurement.",
              "Overnight documentation runs without review."]),
            ("Which rules to start with",
             ["Per-project daily ceiling.",
              "Merchant allowlist for data vendors.",
              "Time-of-day rule for overnight runs."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in construction"],
            rows=[
                ["Per-project ceiling", "Each job has its own budget"],
                ["Merchant allowlist", "Unvetted data vendors blocked"],
                ["Time-of-day rule", "Overnight runs need review"],
            ],
        ),
        faqs=[
            ("Can I budget per job site?",
             "Yes — per-agent rules per project."),
            ("Does it slow estimating?",
             "No — ~5 ms per check."),
        ],
        related=[("Data pipelines", "/for/data-pipelines"), ("DevOps automation", "/for/devops-automation"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="agriculture",
        title="AI Spend Control for Agriculture | sipi.bot",
        desc="Agri-tech AI agents: yield forecasting, drone analytics, and supply-chain bots that spend on data and compute per season.",
        h1="Spend Control for Agriculture AI Agents",
        lead="Agri-tech runs agents for yield forecasting, drone analytics, and supply chain — each with paid data and compute at field scale.",
        sections=[
            ("Where agri agents spend",
             ["Yield-forecasting models pulling weather and soil data.",
              "Drone-analytics processing per flight.",
              "Supply-chain agents querying market APIs.",
              "Documentation and compliance bots."]),
            ("The failure modes",
             ["A forecast loop re-pulling data multiplies per-call charges.",
              "Unknown data vendors bypass procurement.",
              "Seasonal processing spikes hit overage tiers."]),
            ("Which rules to start with",
             ["Per-season or per-operation ceiling.",
              "Merchant allowlist for data vendors.",
              "Category rule: data vs compute."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in agriculture"],
            rows=[
                ["Per-operation ceiling", "Each workflow has its own budget"],
                ["Merchant allowlist", "Unvetted vendors blocked"],
                ["Category rule", "Data vs compute budgets"],
            ],
        ),
        faqs=[
            ("Can I budget per crop season?",
             "Yes — per-agent rules per season or operation."),
            ("Does it slow analytics?",
             "No — ~5 ms per check."),
        ],
        related=[("Data pipelines", "/for/data-pipelines"), ("ML engineers", "/for/ml-engineers"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
]

ANSWERS = [
    dict(
        slug="why-do-ai-agents-cost-so-much",
        title="Why Do AI Agents Cost So Much?",
        desc="The honest reasons AI agent bills run high: volume, retries, context, and ungoverned tools. And the levers that bring them down.",
        h1="Why Do AI Agents Cost So Much?",
        lead="Agents aren't expensive per call — they're expensive per hour. The bill is volume, retries, context, and ungoverned tools, not the token rate.",
        sections=[
            ("The real cost drivers",
             ["Volume: agents call tools hundreds of times per task.",
              "Retries: loops multiply single failures.",
              "Context: long sessions re-send big contexts.",
              "Ungoverned tools: paid APIs and data called without review."]),
            ("Why it feels sudden",
             ["The per-call cost is tiny; the multiplier is the surprise.",
              "A $12,400 night is 40 retries of one purchase — not one big charge."]),
            ("The levers",
             ["Velocity limits kill the multipliers. Caps bound the totals. Allowlists control the vendors. Model selection and caching cut the rate."]),
        ],
        table=dict(
            headers=["Driver", "Lever"],
            rows=[
                ["Volume", "Per-agent ceilings"],
                ["Retries", "Velocity limits"],
                ["Context", "Trimming + caps"],
                ["Tools", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Is it the model cost?",
             "Partly — but volume and retries dominate. Rate shopping alone won't fix the bill."),
            ("What's the fastest fix?",
             "A velocity limit — it kills the most common multiplier in seconds."),
        ],
        related=[("How much does an agent cost", "/blog/how-much-does-an-agent-cost-to-run"), ("Runaway cost average", "/benchmarks/agent-runaway-cost-average"), ("How to reduce AI API costs", "/how-to/how-to-reduce-ai-api-costs")],
    ),
    dict(
        slug="how-to-track-ai-agent-costs",
        title="How to Track AI Agent Costs",
        desc="Track AI agent costs per agent, merchant, and category: the audit log, provider dashboards, and the weekly review.",
        h1="How to Track AI Agent Costs",
        lead="Tracking agent costs means per-agent attribution, per-merchant detail, and a review cadence — not one monthly number.",
        sections=[
            ("The layers",
             ["Per-agent: every decision logged with the agent that made it.",
              "Per-merchant: who got paid, how much.",
              "Per-category: compute vs data vs inference."]),
            ("The tools",
             ["Provider dashboards show their slice; the audit log shows the whole — including blocked attempts.",
              "A weekly review turns the log into decisions."]),
        ],
        table=dict(
            headers=["View", "Answers"],
            rows=[
                ["Per-agent", "Who spends"],
                ["Per-merchant", "Who gets paid"],
                ["Per-category", "What it's spent on"],
                ["Per-rule", "What got blocked/flagged"],
            ],
        ),
        faqs=[
            ("What's the ground truth?",
             "The audit log — it records every decision with the rule that fired."),
            ("How often should I review?",
             "Weekly for spend; monthly for rules."),
        ],
        related=[("How to monitor spend in real time", "/answers/how-to-monitor-agent-spend-in-real-time/"), ("Weekly spend review", "/templates/weekly-spend-review-template"), ("Agent audit trail", "/glossary/agent-audit-trail")],
    ),
    dict(
        slug="what-is-agent-spend",
        title="What Is Agent Spend?",
        desc="Agent spend is every dollar an autonomous agent spends: inference, tools, data, and payments. Definition with the control implication.",
        h1="What Is Agent Spend?",
        lead="Agent spend is the money autonomous agents move — inference tokens, tool calls, data purchases, and payments on machine rails.",
        sections=[
            ("The four buckets",
             ["Inference: LLM tokens per call.",
              "Tools: paid APIs and services called mid-task.",
              "Data: vendors and datasets agents buy.",
              "Payments: settlements on x402, AP2, AgentKit."]),
            ("Why it's different",
             ["No human reviews each transaction — autonomy is the point.",
              "Spend compounds: retries, fan-out, and loops multiply."]),
            ("The control",
             ["A spend firewall evaluates every proposed transaction before it happens: APPROVED, BLOCKED, or FLAGGED."]),
        ],
        faqs=[
            ("Is agent spend just API costs?",
             "No — API costs are one bucket. Tools, data, and payments are the rest."),
            ("Who controls it?",
             "Deterministic rules in front of the money path — not prompts."),
        ],
        related=[("Spend firewall", "/glossary/spend-firewall"), ("How agents spend money", "/learn/how-autonomous-agents-spend-money"), ("Agentic payment", "/glossary/agentic-payment")],
    ),
]

CHECKLISTS = [
    dict(
        slug="voice-agent-launch-checklist",
        title="Voice Agent Launch Checklist",
        desc="The go-live checklist for voice agents: telephony budget, token caps, retry limits, and monitoring.",
        h1="Voice Agent Launch Checklist",
        lead="Voice agents bill per minute and per token. This checklist covers the money before the first call.",
        sections=[
            ("The checklist",
             ["1. Telephony ceiling: per-call and per-day limits set?",
              "2. Token budget: category cap on inference per call?",
              "3. Retry limit: velocity limit on failed-call retries?",
              "4. Mid-call tools: allowlist for tools the agent can trigger?",
              "5. Hours: time-of-day rule for after-hours calling?",
              "6. Monitoring: audit log reviewed daily for the first week?",
              "7. Owner: one person accountable for the voice budget?"]),
        ],
        faqs=[
            ("What's the minimum?",
             "Items 1, 2, and 3 — telephony ceiling, token cap, retry limit."),
            ("How do I size the ceiling?",
             "Estimate minutes × rate + tokens per call × expected calls, × 1.5."),
        ],
        related=[("Voice agents", "/use-cases/voice-agents"), ("Vapi pricing", "/cost-of/vapi-pricing"), ("Agent launch checklist", "/checklists/agent-launch-checklist/")],
    ),
    dict(
        slug="mcp-security-checklist",
        title="MCP Security Checklist",
        desc="The vetting checklist for every MCP server your agents use: source, permissions, paid calls, and the spend gate.",
        h1="MCP Security Checklist",
        lead="MCP servers are dependencies with tool access. This checklist is the security review before your agents trust one.",
        sections=[
            ("The checklist",
             ["1. Source: repo, author, stars, maintenance reviewed?",
              "2. Permissions: least privilege confirmed?",
              "3. Paid calls: every paid endpoint identified?",
              "4. Network: destinations audited?",
              "5. Credentials: no keys stored that shouldn't be?",
              "6. Spend gate: server's tools behind the allowlist + caps?",
              "7. Version: pinned, with upgrade path?"]),
        ],
        faqs=[
            ("How often should I re-vet?",
             "Annually, or when the server updates significantly."),
            ("What's the enforcement?",
             "The allowlist — unvetted servers simply can't be paid."),
        ],
        related=[("MCP server vetting template", "/templates/mcp-server-vetting-template"), ("How to vet MCP servers", "/how-to/how-to-vet-mcp-servers"), ("Red flags in MCP servers", "/redflags/red-flags-in-mcp-servers")],
    ),
]

# --- hub metadata -----------------------------------------------------------
