"""Round 27 pSEO data — sipi.bot (2026-08-08).

Eighth round. 23 static pages + 2 blog posts (via lib/generate_content.py):
  integrations +5: mastra, letta, elizaos, ag2, google-genai-sdk
  vs +3: azure-cost-management, google-cloud-budgets, aws-cost-explorer
  sectors +2: hospitality, energy
  use-cases +3: recruiting-agents, property-management-agents, restaurant-agents
  guides +2: guide-to-the-eval-gym, guide-to-self-hosting
  templates +2: budget-approval-matrix, incident-communication-template
  answers +2 (public/): how-to-monitor-agent-spend-in-real-time,
                        how-to-set-up-agent-spend-controls
  checklists +2 (public/): agent-launch-checklist, firewall-rule-tuning-checklist

All in existing dirs — no plumbing. Content rules unchanged (honest, no
fabricated stats; cost figures approximate with verify-current caveats).
"""

INTEGRATIONS = [
    dict(
        slug="mastra",
        title="Mastra Agent Spend Control — sipi.bot Integration",
        desc="Add deterministic spend control to Mastra agents. The guard tool returns APPROVED, BLOCKED, or FLAGGED before any purchase.",
        h1="Spend Control for Mastra",
        lead="Mastra is the TypeScript agent framework for building stateful, tool-using agents — and tools are how agents spend. A guard keeps the tools honest.",
        sections=[
            ("Why Mastra agents overspend",
             ["Tool-calling agents hit paid endpoints as part of their loop.",
              "Workflow steps can trigger purchases without a budget check.",
              "Retries and reflection loops multiply tool calls."]),
            ("How it works",
             ["Register the guard as a tool (or call the HTTP API from a custom tool). Before any spend, the agent asks sipi.bot: APPROVED, BLOCKED, or FLAGGED."]),
            ("Rules that fit Mastra workloads",
             ["Per-transaction cap on tool purchases.",
              "Merchant allowlist for known paid tools.",
              "Velocity limit so loops die fast."]),
        ],
        code=dict(
            title="Guard tool",
            lang="typescript",
            body='import { tool } from "mastra/core/tool";\n\nconst guardSpend = tool({\n  id: "guardSpend",\n  inputSchema: { amount: "number", merchant: "string", category: "string" },\n  execute: async ({ amount, merchant, category }) => {\n    const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n      method: "POST", headers: { "Content-Type": "application/json" },\n      body: JSON.stringify({ amount, merchant, category }),\n    });\n    return (await res.json()).decision; // APPROVED | BLOCKED | FLAGGED\n  },\n});',
            caption="One tool, deterministic policy.",
        ),
        faqs=[
            ("Does this work in TS runtimes?",
             "Yes — it's a plain fetch to an HTTPS endpoint."),
            ("Can I cap a whole workflow?",
             "Yes — per-agent rules apply to everything the agent spends."),
        ],
        related=[("Pydantic AI", "/integrations/pydantic-ai"), ("How to set spend limits", "/how-to/how-to-set-spend-limits"), ("Merchant allowlist", "/glossary/merchant-allowlist")],
    ),
    dict(
        slug="letta",
        title="Letta Agent Spend Control — sipi.bot Integration",
        desc="Letta gives agents persistent memory — and persistent memory means persistent tool spend. Gate it with the sipi.bot guard.",
        h1="Spend Control for Letta",
        lead="Letta (formerly MemGPT) agents keep memory across sessions — which means they keep calling tools across sessions. Long-lived agents need long-lived budgets.",
        sections=[
            ("Why Letta agents overspend",
             ["Persistent agents call tools repeatedly across days.",
              "Memory-heavy workflows re-run paid lookups.",
              "Autonomous background agents spend without review."]),
            ("How it works",
             ["Attach the guard as a tool. Before any spend — lookup, purchase, subscription — the agent gets a deterministic decision."]),
            ("Rules that fit Letta workloads",
             ["Per-agent daily ceiling (persistent agents spend daily).",
              "Merchant allowlist for paid tools.",
              "Approval threshold for new vendor spend."]),
        ],
        code=dict(
            title="Guard call",
            lang="python",
            body='from sipi_guard import sipi_guard\n\n# Inside a tool that spends:\ndecision = sipi_guard(amount=25, merchant="enrichment-api.com", category="data")\n# APPROVED | BLOCKED | FLAGGED',
            caption="Long-lived agents, enforced budgets.",
        ),
        faqs=[
            ("Do persistent agents need different rules?",
             "Yes — they spend daily by design, so daily ceilings fit better than one-off caps."),
            ("Is the decision model-free?",
             "Yes — deterministic rules, ~5 ms."),
        ],
        related=[("LlamaIndex", "/integrations/llama-index"), ("Agent budget", "/glossary/agent-budget"), ("Daily spend limits", "/limits/daily-spend-limits")],
    ),
    dict(
        slug="elizaos",
        title="ElizaOS Agent Spend Control — sipi.bot Integration",
        desc="ElizaOS agents run autonomous crypto and trading workflows that move money. sipi.bot gates every transaction before settlement.",
        h1="Spend Control for ElizaOS",
        lead="ElizaOS powers autonomous agents in the crypto economy — trading, tipping, and transacting onchain. Speed is the point; a gate is the requirement.",
        sections=[
            ("Why ElizaOS agents need a gate",
             ["Autonomous agents transact onchain where settlement is fast and irreversible.",
              "A retry loop on a payment rail is damage at settlement speed.",
              "No native budget enforcement in the agent runtime."]),
            ("How it works",
             ["Call sipi.bot before any transaction: amount, merchant, category → APPROVED, BLOCKED, or FLAGGED in ~5 ms, fully logged."]),
            ("Rules that fit ElizaOS workloads",
             ["Per-transaction cap for onchain payments.",
              "Merchant allowlist for known counterparties.",
              "Velocity limit so loops die before settlement."]),
        ],
        code=dict(
            title="Guard call",
            lang="typescript",
            body='const res = await fetch("https://sipi.bot/v1/transactions/evaluate", {\n  method: "POST", headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ amount: 0.5, currency: "ETH", merchant: "counterparty.eth", category: "transfer" }),\n});\nconst { decision } = await res.json();',
            caption="The rail settles; sipi.bot decides.",
        ),
        faqs=[
            ("Does sipi.bot hold crypto?",
             "No — it's a decision API. Your wallet and rail still settle."),
            ("Is 5 ms fast enough for trading?",
             "The gate is on the payment path, not the market-data path — 5 ms is fine."),
        ],
        related=[("sipi.bot vs AgentKit", "/vs/openai-agentkit"), ("Agentic payment", "/glossary/agentic-payment"), ("Trading bots", "/use-cases/hft-trading")],
    ),
    dict(
        slug="ag2",
        title="AG2 (AutoGen) Agent Spend Control — sipi.bot Integration",
        desc="AG2 (the AutoGen successor) runs multi-agent conversations that call tools in parallel. A shared ceiling stops fleet compounding.",
        h1="Spend Control for AG2",
        lead="AG2 builds multi-agent systems where agents converse, delegate, and call tools — parallel spend by design. The firewall gives the fleet one budget.",
        sections=[
            ("Why AG2 systems overspend",
             ["Multi-agent conversations spawn many tool calls per turn.",
              "Parallel agents compound spend during a single task.",
              "No built-in dollar-level budget."]),
            ("How it works",
             ["Add the guard as a tool available to the agents that spend. Decisions are deterministic and shared across the fleet."]),
            ("Rules that fit AG2 workloads",
             ["Shared daily ceiling across the conversation's agents.",
              "Velocity limit per agent.",
              "Category rule for inference vs data vs payments."]),
        ],
        code=dict(
            title="Guard tool",
            lang="python",
            body='from sipi_guard import sipi_guard\n\n# Agents call this before spending:\ndecision = sipi_guard(amount=80, merchant="api.vendor.com", category="api")\n# APPROVED | BLOCKED | FLAGGED',
            caption="One fleet, one budget.",
        ),
        faqs=[
            ("Does the shared ceiling cover all agents?",
             "Yes — rules scoped to the group share one budget."),
            ("What about legitimate parallel work?",
             "Set the ceiling at a level that fits legit fan-out; the cap only bites when the fleet exceeds it."),
        ],
        related=[("Multi-agent budgets", "/use-cases/multi-agent-budgets"), ("Multi-agent compounding", "/scenarios/multi-agent-compounding-scenario"), ("Multi-agent governance", "/guides/multi-agent-spend-governance")],
    ),
    dict(
        slug="google-genai-sdk",
        title="Google GenAI SDK Spend Control — sipi.bot Integration",
        desc="The Google GenAI SDK builds agents on Gemini. sipi.bot adds dollar-level policy on top of the SDK's tool calls.",
        h1="Spend Control for the Google GenAI SDK",
        lead="The GenAI SDK is the official Python/Go path to Gemini — and Gemini agents call tools that spend. The guard makes the spend policy real.",
        sections=[
            ("Why GenAI SDK agents overspend",
             ["Tool-calling agents hit paid endpoints per turn.",
              "Long agentic sessions multiply inference and tool costs.",
              "Gemini's own limits cover Gemini; the rest is ungoverned."]),
            ("How it works",
             ["Register the guard as a tool (or call the HTTP API). Before any spend, the agent gets APPROVED, BLOCKED, or FLAGGED."]),
            ("Rules that fit GenAI SDK workloads",
             ["Per-agent daily ceiling.",
              "Merchant allowlist for paid tools.",
              "Velocity limit for retry loops."]),
        ],
        code=dict(
            title="Guard call",
            lang="python",
            body='from google import genai\nfrom sipi_guard import sipi_guard\n\n# Before a paid tool call:\ndecision = sipi_guard(amount=40, merchant="data-api.com", category="data")',
            caption="Gemini for the model; the firewall for the money.",
        ),
        faqs=[
            ("Does this replace Gemini's usage limits?",
             "No — keep them for Gemini. The firewall covers every merchant, including outside Google."),
            ("Is there a Go client?",
             "sipi.bot is HTTP — any language works."),
        ],
        related=[("Google Gemini", "/integrations/google-gemini"), ("Google ADK", "/integrations/google-adk"), ("Gemini API cost", "/cost-of/google-gemini-api-cost")],
    ),
]

VS = [
    dict(
        slug="azure-cost-management",
        name="Azure Cost Management",
        title="sipi.bot vs Azure Cost Management — Cloud Bills vs Agent Spend",
        desc="Azure Cost Management tracks your Azure bill. sipi.bot gates agent transactions before they settle. Compare scope.",
        h1="sipi.bot vs Azure Cost Management",
        lead="Azure Cost Management shows you what your Azure estate costs. sipi.bot decides whether an agent's transaction may happen. Visibility vs enforcement.",
        sections=[
            ("What Azure Cost Management does well",
             ["Deep Azure cost visibility, budgets, and alerts.",
              "Solid for understanding and allocating Azure spend."]),
            ("Where it falls short",
             ["It reports spend; it doesn't stop it. Alerts arrive after the money moves.",
              "No pre-spend decision on agent transactions.",
              "No merchant allowlist, approval queue, or category budgets for agent spend."]),
            ("Where sipi.bot wins",
             ["Pre-spend APPROVED / BLOCKED / FLAGGED.",
              "Dollar-level controls across every merchant.",
              "Approval workflow for edge cases.",
              "Deterministic, ~5 ms."]),
            ("When to use which",
             ["Azure Cost Management for the cloud bill; sipi.bot for agent transactions. They compose."]),
        ],
        table=dict(
            headers=["Dimension", "Azure Cost Management", "sipi.bot"],
            rows=[
                ["Role", "Cloud cost visibility", "Pre-spend enforcement"],
                ["When it acts", "After spend", "Before spend"],
                ["Scope", "Azure services", "All agent merchants"],
                ["Controls", "Budgets, alerts", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Is Azure Cost Management a firewall?",
             "No — it's visibility. Nothing sits in front of an agent's transaction."),
            ("Can sipi.bot control Azure agent spend?",
             "Yes — agents provisioning Azure services go through the same rules."),
        ],
        related=[("Best cloud cost tools", "/best/best-cloud-cost-management-tools"), ("sipi.bot vs Kubecost", "/vs/kubecost"), ("sipi.bot vs Vantage", "/vs/vantage")],
    ),
    dict(
        slug="google-cloud-budgets",
        name="Google Cloud Budgets",
        title="sipi.bot vs Google Cloud Budgets — Cloud Alerts vs Agent Firewall",
        desc="Google Cloud Budgets alerts you when cloud spend crosses thresholds. sipi.bot blocks agent spend before it happens.",
        h1="sipi.bot vs Google Cloud Budgets",
        lead="Google Cloud Budgets tells you when you've crossed a line. sipi.bot decides before a transaction crosses anything. Different moments, different jobs.",
        sections=[
            ("What Google Cloud Budgets does well",
             ["Simple threshold alerts on Google Cloud spend.",
              "Free and built into the console."]),
            ("Where it falls short",
             ["Alerts are post-hoc — the money already moved.",
              "No pre-spend decision, no merchant allowlist, no approval queue."]),
            ("Where sipi.bot wins",
             ["Decides before settlement.",
              "Covers every merchant, not just Google Cloud.",
              "Approval workflow for edge cases."]),
            ("When to use which",
             ["Budgets for cloud alerts; sipi.bot for agent transaction enforcement. Complementary."]),
        ],
        table=dict(
            headers=["Dimension", "Google Cloud Budgets", "sipi.bot"],
            rows=[
                ["Role", "Spend alerts", "Pre-spend enforcement"],
                ["When it acts", "After thresholds crossed", "Before transactions"],
                ["Scope", "Google Cloud", "All merchants"],
                ["Decision", "Alert", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Can Budgets stop a runaway?",
             "No — it alerts. The firewall blocks before settlement."),
            ("Does sipi.bot work with GCP agents?",
             "Yes — any agent that spends, including on GCP, goes through the same rules."),
        ],
        related=[("sipi.bot vs GCP Billing", "/vs/gcp-billing"), ("Best cloud cost tools", "/best/best-cloud-cost-management-tools"), ("How to prevent runaway agents", "/how-to/how-to-prevent-runaway-agents")],
    ),
    dict(
        slug="aws-cost-explorer",
        name="AWS Cost Explorer",
        title="sipi.bot vs AWS Cost Explorer — Cost Charts vs Spend Control",
        desc="AWS Cost Explorer charts your AWS bill. sipi.bot gates agent spend before it lands on that bill.",
        h1="sipi.bot vs AWS Cost Explorer",
        lead="Cost Explorer is where you discover the damage. sipi.bot is where you prevent it. One charts, the other gates.",
        sections=[
            ("What Cost Explorer does well",
             ["Comprehensive AWS cost charts and forecasts.",
              "The standard for understanding an AWS bill."]),
            ("Where it falls short",
             ["Everything it shows happened already.",
              "No pre-spend decision layer, no merchant policy, no approval queue."]),
            ("Where sipi.bot wins",
             ["Pre-spend decisions on every transaction.",
              "Caps, allowlists, velocity limits, approvals.",
              "Deterministic and logged."]),
            ("When to use which",
             ["Cost Explorer for the bill; sipi.bot for the gate. Pair them."]),
        ],
        table=dict(
            headers=["Dimension", "AWS Cost Explorer", "sipi.bot"],
            rows=[
                ["Role", "Cost analytics", "Pre-spend enforcement"],
                ["When it acts", "After usage", "Before transactions"],
                ["Scope", "AWS services", "All agent merchants"],
                ["Decision", "Charts & forecasts", "APPROVED / BLOCKED / FLAGGED"],
            ],
        ),
        faqs=[
            ("Does Cost Explorer help prevent runaways?",
             "It shows them after. Prevention needs a decision layer in front of the transaction."),
            ("Is sipi.bot an AWS service?",
             "No — it's a decision API that composes with AWS (and everything else)."),
        ],
        related=[("sipi.bot vs AWS Budgets", "/vs/aws-budgets"), ("Best cloud cost tools", "/best/best-cloud-cost-management-tools"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
]

SECTORS = [
    dict(
        slug="hospitality",
        title="AI Spend Control for Hospitality | sipi.bot",
        desc="Hospitality AI agents: booking, concierge, and revenue-management bots that spend on data and ads. Cap it per property.",
        h1="Spend Control for Hospitality AI Agents",
        lead="Hotels run agents for booking, concierge, and revenue management — each pulling paid data and ad spend per property. Per-property budgets keep the margin.",
        sections=[
            ("Where hospitality agents spend",
             ["Revenue-management agents pulling rate and demand data.",
              "Booking and concierge bots hitting LLM inference at volume.",
              "Ad and OTA spend managed by marketing agents.",
              "Review-response bots at scale."]),
            ("The failure modes",
             ["A rate-data loop re-pulling feeds multiplies per-call charges.",
              "Unknown data vendors bypass procurement.",
              "Seasonal spikes (peak season, events) hit overage tiers."]),
            ("Which rules to start with",
             ["Per-property daily ceiling.",
              "Merchant allowlist for approved data vendors.",
              "Velocity limit on feed loops."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in hospitality"],
            rows=[
                ["Per-property ceiling", "Each property has its own budget"],
                ["Merchant allowlist", "Unvetted data vendors blocked"],
                ["Velocity limit", "Feed loops die fast"],
            ],
        ),
        faqs=[
            ("Can I budget per property?",
             "Yes — per-agent rules per property."),
            ("Does it slow concierge bots?",
             "No — ~5 ms per check."),
        ],
        related=[("Marketing sector", "/sectors/marketing"), ("Customer support bots", "/use-cases/customer-support-bots"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
    dict(
        slug="energy",
        title="AI Spend Control for Energy | sipi.bot",
        desc="Energy AI agents: grid forecasting, trading, and asset-maintenance bots. Hard caps on data and compute spend.",
        h1="Spend Control for Energy AI Agents",
        lead="Energy runs agents for grid forecasting, wholesale trading, and asset maintenance — each pulling live data and running inference at scale.",
        sections=[
            ("Where energy agents spend",
             ["Forecasting agents pulling market and weather data.",
              "Trading agents on exchange and data APIs.",
              "Asset-maintenance agents running inference per unit.",
              "Compliance and reporting bots at volume."]),
            ("The failure modes",
             ["A data-feed loop multiplies per-message charges.",
              "Trading agents in a retry loop during market hours — a financial event.",
              "Unknown vendors bypass procurement."]),
            ("Which rules to start with",
             ["Per-transaction cap on data purchases.",
              "Velocity limit on feed and API loops.",
              "Time-of-day rule for unattended runs."]),
        ],
        table=dict(
            headers=["Rule", "Why it matters in energy"],
            rows=[
                ["Per-transaction cap", "Single runaway purchases blocked"],
                ["Velocity limit", "Loops die before they compound"],
                ["Time-of-day rule", "Overnight runs need review"],
            ],
        ),
        faqs=[
            ("Is 5 ms too slow for trading?",
             "The gate is on the payment path, not the market path — 5 ms is fine."),
            ("Can I cap per trading desk?",
             "Yes — per-agent rules per desk."),
        ],
        related=[("Trading bots", "/use-cases/hft-trading"), ("Fintech sector", "/sectors/fintech"), ("Velocity limit", "/glossary/velocity-limit")],
    ),
]

USE_CASES = [
    dict(
        slug="recruiting-agents",
        title="Recruiting Agent Spend Control | sipi.bot",
        desc="Recruiting agents screen, schedule, and source — against paid tool APIs. Cap the per-hire spend.",
        h1="Spend Control for Recruiting Agents",
        lead="Recruiting agents source, screen, and schedule — each step hits paid tools. At hiring volume, per-candidate costs compound fast.",
        sections=[
            ("Where recruiting agents spend",
             ["Sourcing and enrichment APIs per candidate.",
              "Screening inference per application.",
              "Scheduling and communication APIs per touch.",
              "Background-check vendors per hire."]),
            ("The failure modes",
             ["A screening loop re-running candidates multiplies inference.",
              "Unknown sourcing vendors bypass procurement.",
              "Hiring spikes hit overage tiers."]),
            ("Which rules to start with",
             ["Per-hire or per-campaign cost cap.",
              "Merchant allowlist for sourcing vendors.",
              "Daily ceiling on screening inference."]),
        ],
        table=dict(
            headers=["Recruiting spend", "Control"],
            rows=[
                ["Sourcing APIs", "Per-campaign ceiling"],
                ["Screening inference", "Daily ceiling"],
                ["Scheduling APIs", "Category budget"],
                ["Background checks", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Can I budget per role?",
             "Yes — per-agent rules per role or campaign."),
            ("What about agency vs internal?",
             "Same controls — per-agent budgets work for both."),
        ],
        related=[("HR automation", "/use-cases/hr-automation-agents"), ("Email agents", "/use-cases/email-agents"), ("How to audit agent spending", "/how-to/how-to-audit-agent-spending")],
    ),
    dict(
        slug="property-management-agents",
        title="Property Management Agent Spend Control | sipi.bot",
        desc="Property management agents handle listings, tenant comms, and maintenance — against paid tools per property.",
        h1="Spend Control for Property Management Agents",
        lead="Property bots manage listings, tenant communication, and maintenance — each with paid API calls per property. Per-portfolio budgets.",
        sections=[
            ("Where property agents spend",
             ["Listing syndication APIs per property.",
              "Tenant communication inference at volume.",
              "Maintenance-dispatch tools per ticket.",
              "Market-data feeds for pricing."]),
            ("The failure modes",
             ["A listing loop re-syndicating multiplies per-call charges.",
              "Unknown vendors bypass procurement.",
              "Overnight tenant-comms runs without review."]),
            ("Which rules to start with",
             ["Per-portfolio daily ceiling.",
              "Merchant allowlist for approved tools.",
              "Time-of-day rule for comms."]),
        ],
        table=dict(
            headers=["Property spend", "Control"],
            rows=[
                ["Syndication APIs", "Per-property cap"],
                ["Tenant comms", "Daily ceiling"],
                ["Maintenance tools", "Merchant allowlist"],
                ["Market data", "Category budget"],
            ],
        ),
        faqs=[
            ("Can I budget per portfolio?",
             "Yes — per-agent rules per portfolio."),
            ("Does it slow tenant responses?",
             "No — ~5 ms per check."),
        ],
        related=[("Real estate sector", "/sectors/real-estate"), ("Customer support bots", "/use-cases/customer-support-bots"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
    dict(
        slug="restaurant-agents",
        title="Restaurant AI Agent Spend Control | sipi.bot",
        desc="Restaurant agents handle orders, reservations, and marketing — against paid tools per location. Cap it per store.",
        h1="Spend Control for Restaurant Agents",
        lead="Restaurant bots take orders, manage reservations, and run local marketing — paid API calls per location, at volume.",
        sections=[
            ("Where restaurant agents spend",
             ["Order-processing inference per order.",
              "Reservation and waitlist tools per booking.",
              "Local marketing and ad agents per location.",
              "Review-response bots at volume."]),
            ("The failure modes",
             ["An order loop re-processing multiplies inference.",
              "Local ad agents overspend per location.",
              "Peak-hour spikes hit overage tiers."]),
            ("Which rules to start with",
             ["Per-location daily ceiling.",
              "Category rule: ads vs operations.",
              "Velocity limit on order loops."]),
        ],
        table=dict(
            headers=["Restaurant spend", "Control"],
            rows=[
                ["Order inference", "Per-location ceiling"],
                ["Reservation tools", "Category budget"],
                ["Local ads", "Per-location ad cap"],
                ["Review bots", "Daily ceiling"],
            ],
        ),
        faqs=[
            ("Can I cap per location?",
             "Yes — per-agent rules per store."),
            ("Does it slow order processing?",
             "No — ~5 ms per check."),
        ],
        related=[("Marketing sector", "/sectors/marketing"), ("E-commerce sector", "/sectors/ecommerce"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
]

GUIDES = [
    dict(
        slug="guide-to-the-eval-gym",
        title="Guide to the Eval Gym",
        desc="What the sipi.bot eval gym tests, how the 53 scenarios work, and why a deterministic test harness matters for spend firewalls.",
        h1="Guide to the Eval Gym",
        lead="The eval gym is how sipi.bot proves the firewall works: 53 scenarios, 53/53 passing, machine-readable results. Here's what it actually tests.",
        sections=[
            ("What the scenarios cover",
             ["The six rule types against the documented failure shapes: retry loops, unknown vendors, category drift, overnight runs, key compromise, multi-tenant breaches.",
              "Each scenario defines an agent state, a proposed transaction, and the expected decision."]),
            ("Why a harness matters",
             ["A spend firewall is only as good as its edge cases. The gym encodes the incident database's patterns as tests.",
              "Deterministic scenarios mean the results are reproducible — no model variance."]),
            ("How to read the results",
             ["53/53 passing, published at /eval-report/ and machine-readable JSON at /eval."]),
        ],
        table=dict(
            headers=["Scenario group", "What it tests"],
            rows=[
                ["Retry loops", "Velocity limits"],
                ["Unknown vendors", "Merchant allowlists"],
                ["Category drift", "Category rules"],
                ["Overnight runs", "Time-of-day rules"],
                ["Key compromise", "Auth + caps"],
            ],
        ),
        faqs=[
            ("Are the scenarios real?",
             "They encode documented incident patterns — sourced from the incident database."),
            ("Can I run them myself?",
             "The eval results are public; the core is MIT-licensed, so you can run the engine and the scenarios."),
        ],
        related=[("Eval report", "/eval-report/"), ("Incident database", "/incidents/"), ("The $12,400 story", "/blog/12400-story-eval-gym")],
    ),
    dict(
        slug="guide-to-self-hosting",
        title="Guide to Self-Hosting sipi.bot",
        desc="Why and how to self-host the MIT-licensed sipi.bot core: what you get, what you don't, and the deployment checklist.",
        h1="Guide to Self-Hosting sipi.bot",
        lead="The core is MIT-licensed and self-hosts anywhere. Here's what self-hosting actually includes — and the honest trade-offs.",
        sections=[
            ("What you get",
             ["The complete deterministic decision engine — all six rule types, HTTP API, MCP tool, CLI.",
              "Your rules, your infrastructure, no vendor in the loop."]),
            ("What you don't",
             ["The hosted dashboard, managed approval queue, and stored audit log are hosted-only.",
              "You own uptime, storage, and your approval UI."]),
            ("The checklist",
             ["Persist the store on a volume. Wire /health to your orchestrator. Create the first rule with the admin token. Set per-agent keys."]),
        ],
        code=dict(
            title="Minimum viable deploy",
            lang="bash",
            body='docker build -t sipi-bot .\ndocker run -d -p 8080:8080 -v sipi-data:/data \\\n  -e SPENDFIREWALL_DB=/data/spendfirewall.db sipi-bot\ncurl localhost:8080/health   # 200',
            caption="See /tutorials/self-host-in-docker for the full walkthrough.",
        ),
        faqs=[
            ("Is self-hosting really free?",
             "Yes — MIT license, no gating."),
            ("Should I self-host or go hosted?",
             "Self-host for control and cost; hosted for the dashboard, approval queue, and zero ops."),
        ],
        related=[("Self-host guide", "/self-hosted/"), ("Self-host tutorial", "/tutorials/self-host-in-docker"), ("Can I self-host", "/pricing-questions/can-i-self-host-sipi-bot")],
    ),
]

TEMPLATES = [
    dict(
        slug="budget-approval-matrix",
        title="Agent Budget Approval Matrix Template",
        desc="A copy-paste approval matrix for agent spend: amounts, categories, and who approves what. Set it once, enforce everywhere.",
        h1="Agent Budget Approval Matrix",
        lead="An approval matrix answers 'who decides?' for every spend shape — before it happens. Here's the template.",
        sections=[
            ("The matrix",
             ["Under $100, allowlisted vendor → auto-approve.",
              "$100–$500 → agent owner approves.",
              "$500–$5,000 → budget owner approves.",
              "Over $5,000 → finance + budget owner.",
              "New vendor, any amount → procurement vetting first.",
              "Blocked categories → never approved."]),
            ("Enforcement",
             ["The matrix maps to rules: approval thresholds per tier, merchant allowlist, category blocks."]),
        ],
        code=dict(
            title="Rule sketch",
            lang="json",
            body='{\n  "approval_threshold": {"over": 100, "action": "flag"},\n  "approval_threshold": {"over": 5000, "action": "flag", "queue": "finance"},\n  "merchant_allowlist": {"allowed": ["openai.com", "data-vendor.com"]}\n}',
            caption="The matrix becomes decisions.",
        ),
        faqs=[
            ("What's a good default?",
             "Start with the 100/500/5000 tiers and tune with audit-log data."),
            ("Who maintains it?",
             "The budget owner, reviewed quarterly."),
        ],
        related=[("Approval threshold policy", "/policies/approval-threshold-policy"), ("Approval workflow template", "/templates/approval-workflow"), ("Agent spend approval policy", "/templates/agent-spend-approval-policy")],
    ),
    dict(
        slug="incident-communication-template",
        title="Agent Incident Communication Template",
        desc="A template for communicating an agent incident internally and externally: what happened, impact, fix, and timeline.",
        h1="Agent Incident Communication Template",
        lead="When an agent does something it shouldn't, communication matters as much as the fix. This template structures it.",
        sections=[
            ("Internal communication",
             ["What happened: [incident summary]",
              "Impact: [financial, data, operational]",
              "Root cause: [pattern + missing rule]",
              "Current status: [contained / investigating / resolved]",
              "Next steps: [rule added, review date]"]),
            ("External communication (if needed)",
             ["What we know, what we're doing, when we'll update.",
              "No speculation, no blame — facts and fixes."]),
        ],
        code=dict(
            title="One-liner",
            lang="text",
            body="Agent [X] spent [amount] at [time] due to [pattern]. [Rule] added; [review] scheduled. Full log available in the audit trail.",
            caption="Clear, honest, complete.",
        ),
        faqs=[
            ("When should we communicate externally?",
             "When customers or regulators could be affected — and when your terms require it."),
            ("What's the most important line?",
             "The fix — what rule now prevents the pattern."),
        ],
        related=[("Agent incident report", "/templates/agent-incident-report"), ("Incident response plan", "/templates/incident-response-plan-template"), ("Runaway loop anatomy", "/blog/runaway-loops-anatomy")],
    ),
]

ANSWERS = [
    dict(
        slug="how-to-monitor-agent-spend-in-real-time",
        title="How to Monitor Agent Spend in Real Time",
        desc="Real-time agent spend monitoring: the audit log, alerts, and the difference between watching and stopping.",
        h1="How to Monitor Agent Spend in Real Time",
        lead="Real-time monitoring means seeing each decision as it happens — and knowing the difference between watching spend and stopping it.",
        sections=[
            ("What real-time means",
             ["Every transaction decision logged with amount, merchant, category, and the rule that fired.",
              "The audit log is queryable — filter by agent, merchant, category, decision, time."]),
            ("Alerts and review",
             ["Set up alerts for blocked and flagged transactions; review daily.",
              "The dashboard surfaces anomalies without you querying."]),
            ("The honest distinction",
             ["Monitoring shows you what happened. Stopping it happens before — that's the firewall's decision layer, not the dashboard."]),
        ],
        table=dict(
            headers=["Layer", "Does"],
            rows=[
                ["Audit log", "Records every decision"],
                ["Alerts", "Surfaces anomalies"],
                ["Firewall", "Stops spend before it moves"],
            ],
        ),
        faqs=[
            ("Is the audit log queryable in real time?",
             "Yes — via API and dashboard, as decisions are written."),
            ("Do I need monitoring if I have a firewall?",
             "Yes — monitoring tells you what's happening; the firewall stops the damage. Both."),
        ],
        related=[("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs"), ("Agent audit trail", "/glossary/agent-audit-trail"), ("Weekly spend review", "/templates/weekly-spend-review-template")],
    ),
    dict(
        slug="how-to-set-up-agent-spend-controls",
        title="How to Set Up Agent Spend Controls",
        desc="Set up agent spend controls in an afternoon: caps, allowlists, velocity limits, and approvals. The five-step setup.",
        h1="How to Set Up Agent Spend Controls",
        lead="Five steps, one afternoon: inventory, rules, defaults, approvals, review. Here's the setup.",
        sections=[
            ("Step 1 — Inventory",
             ["List your spend-capable agents: what they buy, from whom."]),
            ("Step 2 — Set the core rules",
             ["Per-transaction cap, merchant allowlist, velocity limit — three rules cover most risk."]),
            ("Step 3 — Set defaults",
             ["New agents inherit caps and allowlists until their own rules exist."]),
            ("Step 4 — Add approvals",
             ["An approval threshold flags material spend for a human."]),
            ("Step 5 — Review weekly",
             ["Read the audit log, tune rules, one change at a time."]),
        ],
        faqs=[
            ("How long does setup take?",
             "An afternoon for the rules; a week of audit-log data to tune them."),
            ("What's the minimum?",
             "A cap, an allowlist, and a velocity limit per spend-capable agent."),
        ],
        related=[("How to create a spend policy", "/how-to/how-to-create-a-spend-policy"), ("Agent onboarding brief", "/templates/agent-onboarding-spend-brief"), ("Firewall deployment checklist", "/checklists/agent-spend-firewall-deployment/")],
    ),
]

CHECKLISTS = [
    dict(
        slug="agent-launch-checklist",
        title="Agent Launch Checklist",
        desc="The go-live checklist for any spend-capable agent: budget, vendors, rules, approvals, owner, and rollback.",
        h1="Agent Launch Checklist",
        lead="Every agent launch gets this checklist before it ships. Fifteen minutes now saves an incident later.",
        sections=[
            ("The checklist",
             ["1. Budget: daily ceiling set?",
              "2. Vendors: allowlist configured?",
              "3. Rules: cap, velocity limit, category rules in place?",
              "4. Approvals: threshold set, queue owner named?",
              "5. Defaults: would this agent inherit sane rules if cloned?",
              "6. Owner: one person accountable for its spend?",
              "7. Rollback: can you disable spending instantly?",
              "8. Logging: is it visible in the audit log?",
              "9. Review: first spend review scheduled?"]),
        ],
        faqs=[
            ("What's the minimum for a pilot?",
             "Items 1, 2, 3, and 6 — budget, allowlist, rules, owner."),
            ("Who signs off?",
             "The budget owner — same person who approves its spend."),
        ],
        related=[("Agent production readiness", "/checklists/agent-production-readiness/"), ("Agent onboarding brief", "/templates/agent-onboarding-spend-brief"), ("New agent scenario", "/scenarios/new-agent-onboarding-scenario")],
    ),
    dict(
        slug="firewall-rule-tuning-checklist",
        title="Firewall Rule Tuning Checklist",
        desc="The monthly rule-tuning checklist: what to review, what to change, and how to measure one change at a time.",
        h1="Firewall Rule Tuning Checklist",
        lead="Rules drift. Monthly tuning keeps them right. Here's the checklist.",
        sections=[
            ("The checklist",
             ["1. Blocked-but-legit: any BLOCKED transactions that should have passed? Raise the rule or add the merchant.",
              "2. Flagged outcomes: all approved → threshold too low. All denied → agents trying the wrong things.",
              "3. Ceiling proximity: spend consistently near the cap → the cap IS the budget, confirm it's right.",
              "4. New merchants: add legitimate ones to the allowlist, block the rest.",
              "5. One change: make ONE rule change this cycle and measure it next cycle.",
              "6. Document: log the change and its rationale."]),
        ],
        faqs=[
            ("How often should I tune?",
             "Monthly, or after any incident."),
            ("What's the risk of tuning too often?",
             "Noise — you can't measure a change you made alongside five others."),
        ],
        related=[("Weekly spend review", "/templates/weekly-spend-review-template"), ("Agent spend audit guide", "/guides/guide-to-agent-spend-audits"), ("Agent cost audit", "/checklists/agent-cost-audit/")],
    ),
]

# --- hub metadata -----------------------------------------------------------
