"""Round 31 pSEO data — sipi.bot (2026-08-08).

Twelfth round. The big-three cloud AI platform cluster (Bedrock / Vertex AI /
Azure AI Foundry) + inference-provider pricing + personas + crypto answers.
15 static pages + 1 blog.

All existing dirs — no plumbing. Content honest: cloud-platform comparisons
compose (platform for the model, sipi.bot for the money); provider pricing
marked verify-current.
"""

VS = [
    dict(
        slug="aws-bedrock",
        name="AWS Bedrock",
        title="sipi.bot vs AWS Bedrock — Cloud AI Platform vs Spend Firewall",
        desc="AWS Bedrock hosts foundation models; sipi.bot gates what agents spend. Bedrock for the model, a firewall for the money.",
        h1="sipi.bot vs AWS Bedrock",
        lead="AWS Bedrock is the managed foundation-model platform — hosting, serving, and security for models. sipi.bot is a pre-spend firewall. One serves the model; the other governs the spend.",
        sections=[
            ("What Bedrock does well",
             ["Managed access to many foundation models under one AWS surface.",
              "IAM, VPC, and enterprise controls for the model layer."]),
            ("Where it falls short for agent spend",
             ["Bedrock governs model access; it doesn't gate what your agents buy beyond it.",
              "No merchant allowlist or approval queue for agent purchases.",
              "Its budgets cover AWS usage — not your other vendors."]),
            ("Where sipi.bot wins",
             ["Decides before the money moves, across every merchant.",
              "Caps, allowlists, velocity limits, approvals — model-agnostic."]),
            ("When to use which",
             ["Bedrock for the model layer; sipi.bot for the money layer. They compose."]),
        ],
        table=dict(
            headers=["Dimension", "AWS Bedrock", "sipi.bot"],
            rows=[
                ["Role", "Model hosting + access", "Pre-spend firewall"],
                ["Scope", "AWS + Bedrock models", "All agent merchants"],
                ["When it acts", "Serves requests", "Before transactions"],
                ["Controls", "IAM, budgets", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Is Bedrock a spend firewall?",
             "No — it's a model platform with AWS budgets. Nothing sits in front of an agent's transaction."),
            ("Does sipi.bot work with Bedrock agents?",
             "Yes — there's a dedicated integration for Bedrock Agents."),
        ],
        related=[("Bedrock Agents integration", "/integrations/aws-bedrock-agents"), ("sipi.bot vs Azure AI Foundry", "/vs/azure-ai-foundry"), ("sipi.bot vs Google Vertex AI", "/vs/google-vertex-ai")],
    ),
    dict(
        slug="google-vertex-ai",
        name="Google Vertex AI",
        title="sipi.bot vs Google Vertex AI — Model Platform vs Spend Firewall",
        desc="Vertex AI builds and serves models and agents; sipi.bot gates the spend. Different layers of the same pipeline.",
        h1="sipi.bot vs Google Vertex AI",
        lead="Vertex AI is Google's platform for building and serving models and agents. sipi.bot is a pre-spend firewall. One builds the pipeline; the other budgets it.",
        sections=[
            ("What Vertex AI does well",
             ["End-to-end model and agent building on Google Cloud.",
              "Tight integration with Gemini and GCP services."]),
            ("Where it falls short for agent spend",
             ["Vertex governs Google usage; it doesn't gate agent purchases elsewhere.",
              "No merchant allowlist or approval queue for agent spend."]),
            ("Where sipi.bot wins",
             ["Pre-spend decisions across every merchant.",
              "Caps, allowlists, velocity limits, approvals."]),
            ("When to use which",
             ["Vertex for building; sipi.bot for the spend. Complementary."]),
        ],
        table=dict(
            headers=["Dimension", "Google Vertex AI", "sipi.bot"],
            rows=[
                ["Role", "Model/agent platform", "Pre-spend firewall"],
                ["Scope", "Google Cloud", "All agent merchants"],
                ["When it acts", "Serves requests", "Before transactions"],
                ["Controls", "GCP budgets", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Is Vertex a firewall?",
             "No — it's a platform. Its budgets cover Google usage only."),
            ("Does sipi.bot integrate with Vertex?",
             "Yes — via the GenAI SDK and ADK integrations."),
        ],
        related=[("Google ADK integration", "/integrations/google-adk"), ("GenAI SDK integration", "/integrations/google-genai-sdk"), ("sipi.bot vs AWS Bedrock", "/vs/aws-bedrock")],
    ),
    dict(
        slug="azure-ai-foundry",
        name="Azure AI Foundry",
        title="sipi.bot vs Azure AI Foundry — Microsoft AI Platform vs Spend Firewall",
        desc="Azure AI Foundry builds and serves AI apps; sipi.bot gates what agents spend. Platform for the app, firewall for the money.",
        h1="sipi.bot vs Azure AI Foundry",
        lead="Azure AI Foundry is Microsoft's platform for building and serving AI applications and agents. sipi.bot is a pre-spend firewall. One ships the app; the other governs its spend.",
        sections=[
            ("What AI Foundry does well",
             ["Managed model access, agents, and evaluation on Azure.",
              "Strong enterprise integration with the Microsoft stack."]),
            ("Where it falls short for agent spend",
             ["Foundry governs Azure usage; it doesn't gate agent purchases beyond it.",
              "No merchant allowlist or approval queue for agent spend."]),
            ("Where sipi.bot wins",
             ["Pre-spend decisions across every merchant.",
              "Caps, allowlists, velocity limits, approvals."]),
            ("When to use which",
             ["Foundry for the platform; sipi.bot for the spend. They compose."]),
        ],
        table=dict(
            headers=["Dimension", "Azure AI Foundry", "sipi.bot"],
            rows=[
                ["Role", "AI app platform", "Pre-spend firewall"],
                ["Scope", "Azure + Microsoft", "All agent merchants"],
                ["When it acts", "Serves requests", "Before transactions"],
                ["Controls", "Azure budgets", "Caps, allowlists, approvals"],
            ],
        ),
        faqs=[
            ("Is AI Foundry a firewall?",
             "No — it's a platform. Its budgets cover Azure usage only."),
            ("Can sipi.bot control agents on Foundry?",
             "Yes — any agent that spends goes through the same rules."),
        ],
        related=[("Azure Cost Management", "/vs/azure-cost-management"), ("sipi.bot vs AWS Bedrock", "/vs/aws-bedrock"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
]

INTEGRATIONS = [
    dict(
        slug="vertex-ai",
        title="Vertex AI Agents Spend Control — sipi.bot Integration",
        desc="Gate what Vertex AI agents spend: Gemini tokens, tool calls, and paid services per task.",
        h1="Spend Control for Vertex AI Agents",
        lead="Vertex AI agents run on Gemini with tool access — and tools spend. The guard makes the budget real on Google's platform.",
        sections=[
            ("Why Vertex agents overspend",
             ["Gemini token costs per turn at agentic volume.",
              "Tool calls hit paid APIs and services mid-task.",
              "GCP budgets cover Google; the rest is ungoverned."]),
            ("How it works",
             ["Add the guard as a tool (or call the HTTP API from a custom tool). Before any spend, the agent gets a deterministic decision."]),
            ("Rules that fit",
             ["Per-agent daily ceiling.",
              "Merchant allowlist for paid tools.",
              "Category rule: Gemini vs tool spend."]),
        ],
        code=dict(
            title="Guard call",
            lang="python",
            body='from sipi_guard import sipi_guard\n\ndecision = sipi_guard(amount=35, merchant="data-api.com", category="data")\n# APPROVED | BLOCKED | FLAGGED',
            caption="Gemini for the model; the firewall for the money.",
        ),
        faqs=[
            ("Does this replace GCP budgets?",
             "No — keep GCP budgets for Google. The firewall covers every merchant."),
            ("Is there a language SDK?",
             "sipi.bot is HTTP — any language works."),
        ],
        related=[("GenAI SDK", "/integrations/google-genai-sdk"), ("Google ADK", "/integrations/google-adk"), ("sipi.bot vs Google Vertex AI", "/vs/google-vertex-ai")],
    ),
    dict(
        slug="azure-ai-foundry",
        title="Azure AI Foundry Agents Spend Control — sipi.bot Integration",
        desc="Gate what Azure AI Foundry agents spend: model tokens, tool calls, and connected services.",
        h1="Spend Control for Azure AI Foundry Agents",
        lead="Foundry agents combine Azure models with tool access — and tools spend. The guard enforces the budget on Microsoft's platform.",
        sections=[
            ("Why Foundry agents overspend",
             ["Azure model token costs at agentic volume.",
              "Tool calls hit paid APIs and services mid-task.",
              "Azure budgets cover Microsoft; the rest is ungoverned."]),
            ("How it works",
             ["Add the guard as a tool. Before any spend, the agent gets APPROVED, BLOCKED, or FLAGGED."]),
            ("Rules that fit",
             ["Per-agent daily ceiling.",
              "Merchant allowlist for paid tools.",
              "Velocity limit on retry loops."]),
        ],
        code=dict(
            title="Guard call",
            lang="python",
            body='from sipi_guard import sipi_guard\n\ndecision = sipi_guard(amount=45, merchant="api.vendor.com", category="api")\n# APPROVED | BLOCKED | FLAGGED',
            caption="Foundry for the app; the firewall for the money.",
        ),
        faqs=[
            ("Does this replace Azure budgets?",
             "No — keep Azure budgets. The firewall covers every merchant."),
            ("Can I cap per agent?",
             "Yes — per-agent rules."),
        ],
        related=[("Azure Cost Management", "/vs/azure-cost-management"), ("sipi.bot vs Azure AI Foundry", "/vs/azure-ai-foundry"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
]

COST_OF = [
    dict(
        slug="fireworks-api-cost",
        title="Fireworks AI API Cost — Pricing and Agent Spend Control",
        desc="Fireworks AI API cost: token pricing for fast inference and how to control agent spend on Fireworks models.",
        h1="How Much Does the Fireworks AI API Cost?",
        lead="Fireworks sells fast inference with per-token pricing. Speed at volume is still a bill — and fast models invite more calls.",
        sections=[
            ("How Fireworks pricing works",
             ["Per-token pricing by model.",
              "Speed is the selling point; the bill is rate × volume.",
              "Verify current pricing on Fireworks' site."]),
            ("The hidden cost",
             ["Fast inference invites more calls — agents loop faster.",
              "Retry loops at speed multiply volume."]),
            ("What it really costs",
             ["Rate × volume. Velocity limits and per-agent caps control the volume."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Token rates", "Model selection"],
                ["Fast loops", "Velocity limit"],
                ["Fleet volume", "Per-agent ceilings"],
            ],
        ),
        faqs=[
            ("Is Fireworks cheaper?",
             "Rates vary by model — verify current pricing. Total cost is rate × volume."),
            ("Can sipi.bot control Fireworks spend?",
             "Yes — category rules and per-agent caps apply to any merchant."),
        ],
        related=[("Cost per 1M tokens", "/benchmarks/cost-per-1m-tokens-2026"), ("Groq API cost", "/cost-of/groq-api-cost"), ("How to reduce AI API costs", "/how-to/how-to-reduce-ai-api-costs")],
    ),
    dict(
        slug="baseten-api-cost",
        title="Baseten API Cost — Pricing and Agent Spend Control",
        desc="Baseten API cost: model deployment and inference pricing, and how to control agent spend.",
        h1="How Much Does Baseten Cost?",
        lead="Baseten deploys open-source models as APIs with per-token or per-minute pricing. The bill follows your deployment and volume.",
        sections=[
            ("How Baseten pricing works",
             ["Deployments billed per model with inference on top.",
              "Per-token or per-second pricing depending on the model.",
              "Verify current pricing on Baseten's site."]),
            ("The hidden cost",
             ["Agentic volume drives inference — and retries compound it."]),
            ("What it really costs",
             ["Deployment + rate × volume. Caps and velocity limits control the volume."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Deployment", "Right-size models"],
                ["Inference", "Per-agent ceilings"],
                ["Retries", "Velocity limit"],
            ],
        ),
        faqs=[
            ("Is Baseten cheaper than hosted APIs?",
             "Depends on volume — verify current pricing."),
            ("Can sipi.bot govern Baseten spend?",
             "Yes — per-agent caps and category rules."),
        ],
        related=[("Cost per 1M tokens", "/benchmarks/cost-per-1m-tokens-2026"), ("Together AI cost", "/cost-of/together-api-cost"), ("How to monitor AI costs", "/how-to/how-to-monitor-ai-costs")],
    ),
    dict(
        slug="together-api-cost",
        title="Together AI API Cost — Pricing and Agent Spend Control",
        desc="Together AI API cost: open-model inference pricing and how to control agent spend.",
        h1="How Much Does the Together AI API Cost?",
        lead="Together AI serves open models with per-token pricing. The bill follows volume — and agentic volume is exactly what needs gating.",
        sections=[
            ("How Together pricing works",
             ["Per-token pricing by model, input and output.",
              "Open-model serving with fast inference.",
              "Verify current pricing on Together's site."]),
            ("The hidden cost",
             ["Agentic loops and fan-out multiply per-token volume."]),
            ("What it really costs",
             ["Rate × volume. Per-agent caps and velocity limits control the volume."]),
        ],
        table=dict(
            headers=["Cost bucket", "How to control it"],
            rows=[
                ["Token rates", "Model selection"],
                ["Fan-out", "Per-agent ceilings"],
                ["Retries", "Velocity limit"],
            ],
        ),
        faqs=[
            ("Is Together competitive?",
             "Rates vary by model — verify current pricing."),
            ("Can sipi.bot govern Together spend?",
             "Yes — per-agent caps and category rules."),
        ],
        related=[("Cost per 1M tokens", "/benchmarks/cost-per-1m-tokens-2026"), ("Baseten API cost", "/cost-of/baseten-api-cost"), ("How to reduce AI API costs", "/how-to/how-to-reduce-ai-api-costs")],
    ),
]

FOR = [
    dict(
        slug="chief-financial-officers",
        title="AI Agent Spend Control for CFOs | sipi.bot",
        desc="CFOs: agent spend is a new cost line with no ledger. Budget, control, and audit it like any other spend.",
        h1="AI Agent Spend Control for CFOs",
        lead="Agent spend is a new cost line — decentralized, autonomous, and invisible to traditional controls. CFOs need it budgeted, gated, and auditable.",
        sections=[
            ("Why CFOs should care",
             ["Agents spend like employees but aren't on any expense policy.",
              "Runaway incidents are real financial events.",
              "Traditional controls (POs, approvals) don't exist on machine rails."]),
            ("What to put in place",
             ["Budgets: per-agent ceilings and category budgets.",
              "Controls: allowlists, approval thresholds, velocity limits.",
              "Audit: a logged decision trail for every agent transaction."]),
            ("The reporting angle",
             ["The audit log is the ledger — queryable by agent, merchant, category, and rule."]),
        ],
        table=dict(
            headers=["CFO lever", "sipi.bot answer"],
            rows=[
                ["Budget", "Per-agent ceilings"],
                ["Control", "Allowlists + approvals"],
                ["Audit", "Queryable decision log"],
                ["Forecast", "Spend trends from the log"],
            ],
        ),
        faqs=[
            ("Is agent spend material?",
             "It's the fastest-growing software line for many teams — and the least governed."),
            ("What's the CFO-level control?",
             "Ceilings, allowlists, approval thresholds — enforced deterministically."),
        ],
        related=[("Finance teams", "/for/finance-teams"), ("Accounting teams", "/for/accounting-teams"), ("Agent spend audit guide", "/guides/guide-to-agent-spend-audits")],
    ),
]

USE_CASES = [
    dict(
        slug="claims-processing-agents",
        title="Claims Processing Agent Spend Control | sipi.bot",
        desc="Insurance claims agents: document review, fraud checks, and payouts — cap the spend per claim.",
        h1="Spend Control for Claims Processing Agents",
        lead="Claims agents review documents, run fraud checks, and route payouts — each with paid data and inference per claim.",
        sections=[
            ("Where claims agents spend",
             ["Document review inference per page.",
              "Fraud-check databases per claim.",
              "Payout routing on payment rails.",
              "Notification APIs per touch."]),
            ("The failure modes",
             ["A review re-run after a prompt change multiplies inference.",
              "Unknown vendors bypass procurement.",
              "Payout automation without a per-claim cap."]),
            ("Which rules to start with",
             ["Per-claim ceiling.",
              "Merchant allowlist for data vendors.",
              "Approval threshold for payouts."]),
        ],
        table=dict(
            headers=["Claims spend", "Control"],
            rows=[
                ["Document review", "Per-claim ceiling"],
                ["Fraud checks", "Category budget"],
                ["Payouts", "Approval threshold"],
                ["Notifications", "Merchant allowlist"],
            ],
        ),
        faqs=[
            ("Can I cap per claim?",
             "Yes — per-agent rules per claim type."),
            ("Does it slow claims?",
             "No — ~5 ms per check."),
        ],
        related=[("Insurtech", "/use-cases/insurtech"), ("Legal sector", "/sectors/legal"), ("How to implement spend controls", "/how-to/how-to-implement-spend-controls")],
    ),
]

ANSWERS = [
    dict(
        slug="can-ai-agents-pay-with-crypto",
        title="Can AI Agents Pay with Crypto?",
        desc="Yes — x402, AP2, and AgentKit put payments on machine rails. What that means for spend control.",
        h1="Can AI Agents Pay with Crypto?",
        lead="Yes. Payment protocols built for agents — x402, AP2, AgentKit — let agents settle in crypto autonomously. The rails are the easy part; the control is the job.",
        sections=[
            ("The agent payment rails",
             ["x402: HTTP-based agent-to-agent payments.",
              "AP2: the agent-pay protocol for agentic commerce.",
              "AgentKit: Coinbase's framework for agent payments."]),
            ("Why it matters",
             ["Payments move at machine speed, with no human review.",
              "A retry loop on a payment rail is spend at settlement speed."]),
            ("The control",
             ["Per-transaction caps, velocity limits, and merchant allowlists apply to crypto rails exactly like fiat."]),
        ],
        faqs=[
            ("Is crypto agent payment real?",
             "Yes — x402 and AP2 are live protocols; AgentKit is Coinbase's implementation."),
            ("Does sipi.bot hold crypto?",
             "No — it's a decision API. Your wallet settles."),
        ],
        related=[("x402", "/glossary/x402"), ("AP2", "/glossary/ap2"), ("AgentKit", "/vs/openai-agentkit")],
    ),
    dict(
        slug="how-does-a-spend-firewall-work",
        title="How Does a Spend Firewall Work?",
        desc="The mechanics of a spend firewall: evaluate before settle, deterministic rules, and the audit trail.",
        h1="How Does a Spend Firewall Work?",
        lead="A spend firewall sits between your agent and the money: it evaluates every proposed transaction before settlement and returns a deterministic decision.",
        sections=[
            ("The decision",
             ["Every spend attempt is evaluated against your rules: caps, allowlists, velocity limits, categories, time-of-day, approval thresholds."]),
            ("The outcome",
             ["APPROVED: let it through. BLOCKED: stop it. FLAGGED: pause for a human."]),
            ("The audit",
             ["Every decision is logged with the rule that fired — a complete, queryable trail."]),
        ],
        table=dict(
            headers=["Layer", "Job"],
            rows=[
                ["Rules engine", "Evaluate the transaction"],
                ["Decision", "APPROVED / BLOCKED / FLAGGED"],
                ["Audit log", "Record every decision"],
            ],
        ),
        faqs=[
            ("How fast is it?",
             "~5 ms — deterministic rules, no model in the path."),
            ("Why deterministic?",
             "Rules can't be argued with or injected; a model-based path can."),
        ],
        related=[("Spend firewall", "/glossary/spend-firewall"), ("The six rule types", "/how-to/how-to-create-a-spend-policy"), ("Eval report", "/eval-report/")],
    ),
]

GLOSSARY = [
    dict(
        slug="tool-calling",
        term="Tool calling",
        title="What is Tool Calling? | sipi.bot Glossary",
        desc="Tool calling is how agents act on the world — and the root of almost all agent spend.",
        h1="What is Tool Calling?",
        lead="Tool calling is how an LLM invokes external functions and APIs — the mechanism by which agents actually do things. It's also where the spend lives.",
        sections=[
            ("How it works",
             ["The model outputs a structured call; the runtime executes the tool and returns the result.",
              "Tools can be read-only (lookups) or side-effecting (purchases, payments)."]),
            ("Why it matters for cost",
             ["Every tool call can be a paid API call.",
              "Retry loops are tool calls repeating the same failure."]),
            ("The control",
             ["Gate side-effecting tools with caps, allowlists, and velocity limits."]),
        ],
        faqs=[
            ("Is tool calling the same as function calling?",
             "Effectively — function calling is the structured-interface form of tool calling."),
            ("Where does the spend risk live?",
             "In side-effecting tools — anything that purchases, pays, or provisions."),
        ],
        related=[("MCP", "/glossary/mcp"), ("Retry loop", "/glossary/retry-loop"), ("Merchant allowlist", "/glossary/merchant-allowlist")],
    ),
    dict(
        slug="budget-exhaustion",
        term="Budget exhaustion",
        title="What is Budget Exhaustion? | sipi.bot Glossary",
        desc="Budget exhaustion is what happens when an agent hits its ceiling mid-task — and why it matters for design.",
        h1="What is Budget Exhaustion?",
        lead="Budget exhaustion is the moment an agent's spend ceiling is reached — and the agent must stop, degrade, or ask. How you design for it decides the outcome.",
        sections=[
            ("What happens",
             ["The ceiling is a per-agent or per-category cap.",
              "When reached, further spend is BLOCKED or FLAGGED."]),
            ("Why it matters",
             ["Exhaustion is a feature, not a failure — it's the firewall doing its job.",
              "Well-designed agents handle it: finish with what they have, or ask for more."]),
            ("The design principle",
             ["Make exhaustion explicit and reviewable — the audit log shows exactly where and why it happened."]),
        ],
        faqs=[
            ("Is hitting the cap a bug?",
             "No — it's the control working. The review loop is the escape hatch."),
            ("How do I size ceilings?",
             "From the audit log: legitimate spend + headroom."),
        ],
        related=[("Daily spend ceiling", "/glossary/daily-spend-ceiling"), ("Overage tier", "/glossary/overage-tier"), ("How to set spend limits", "/how-to/how-to-set-spend-limits")],
    ),
]

# --- hub metadata -----------------------------------------------------------
